### ISSUE TITLE
Example in karma/jasmine

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [pact-foundation/pact-js#100]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact JS v2.6.0
* **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
* **Node Version**: `node --version`

## Expected behaviour

TBC

## Actual behaviour

TBC

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
What's the ask here?

**Comment by isayneigh** [comment]
Uhm, I'm sorry. I don't know how this got filed, I had it sitting in an open window preemptively as I pressed through the example.  I was confused about where `Pact` was coming from, but I figured that out on my own.  I had no intention of filing this, it can be closed.

**Comment by isayneigh** [comment]
Also, I'm on my personal account hence the different username.

**Comment by mefellows** [comment]
And you stole the 100th issue 😁
