### ISSUE TITLE
Unable to run Pact 10 in Alpine: gnu_get_libc_version: symbol not found

### ISSUE THREAD

**Issue by danymarques** [pact-foundation/pact-js#1026]
### Software versions

- **OS**:  node:14.21-alpine3.16
- **Consumer Pact library**:  Pact 10.4.0
- **Node Version**: 14.21

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Pact tests should run

### Actual behaviour

Pact tests don't run with the following log: 
```
Test suite failed to run
    Error relocating /builds/test/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.so: gnu_get_libc_version: symbol not found
      at Runtime._loadModule (../../node_modules/jest-runtime/build/index.js:1218:29)
      at bindings (../../node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (../../node_modules/@pact-foundation/pact-core/src/ffi/index.ts:6:21)
```

### Steps to reproduce

Run Pact tests an Alpine docker image.

**Comment by mefellows** [comment]
Hi @danymarques, Alpine is not a supported runtime (see the troubleshooting guide in this repo and docs.pact.io/docker for more).
