### ISSUE TITLE
Add uniquePactFileNames option to mock service options

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#103]
This requires version 1.7.0 of the standalone package.

This option allows multiple mock service instances for the same consumer/provider pair to run in parallel on different ports without the pact files overwriting each other at the end.

```
  -u, [--unique-pact-file-names], [--no-unique-pact-file-names]  # Set to true when running multiple mock service instances in parallel for the same consumer/provider pair
```

**Comment by lirantal** [comment]
@mefellows I assume this needs to be implemented in the pact-js version to wrap this option and expose it the user?

**Comment by bethesque** [comment]
Hold off on this until we get a solution that works for @lirantal Matt.

**Comment by bethesque** [comment]
Closing, not going with this solution.
