### ISSUE TITLE
Change invocation of pact-provider-verifier to pass in pacts as arguments instead of options

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#104]
Remove comma separated `--pact-urls` and provide the URLs as space separated, double quoted (in case of spaces) arguments. eg `pact-provider-verifier "http://foo" "http://bar" --provider-base-url http://provider ...`

```
Usage:
  pact-provider-verifier PACT_URL ... -h, --provider-base-url=PROVIDER_BASE_URL
```

**Comment by mefellows** [comment]
cc: @mboudreau I assume this needs to go in pact-node?

**Comment by mboudreau** [comment]
@mefellows yarp.

**Comment by mefellows** [comment]
This has been implemented in pact node. Closing.
