### ISSUE TITLE
Provider testing - long-running `afterEach` hook does not complete execution

### ISSUE THREAD

**Issue by james-kuihi** [pact-foundation/pact-js#1068]
### Software versions

- **OS**:  Ubuntu 20 (via WSL2)
- **Consumer Pact library**:  Pact JS 10.4.1
- **Provider Pact library**: Pact JS 10.4.1
- **Node Version**: v18.12.1

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

In the provider tests, when executing a long-running function in the `afterEach` hook, such as a database clean-up activity, then the function should complete execution before the test runner terminates.

### Actual behaviour

Test runner terminates before the function completes execution.

### Steps to reproduce

1. Clone down the reproducing repository - https://github.com/james-kuihi/pact-js-aftreEach-bug-demo
2. Run the tests which reproduce the issue:
```
cd examples/v3/afterEach-bug
npm install
npm test
```

You should see log output including:

```
Starting afterEach
...
Finished afterEach
```

However, only the first line is present. The pertinent provider test which reproduces this is [here](https://github.com/james-kuihi/pact-js-aftreEach-bug-demo/blob/b6244059a03f3b2a2b01d101c16379030063521f/examples/v3/afterEach-bug/test/provider.spec.js#L25-L30).

### Relevant log files

[test.log](https://github.com/pact-foundation/pact-js/files/10899732/test.log)

### Other

This was raised and discussed on the [PactJS Slack channel](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1677060601328999), and a improvement idea for the core framework raised in [Canny](https://pact.canny.io/feature-requests/p/framework-wide-verification-beforeeach-aftereach-hooks).

**Comment by TimothyJones** [comment]
I think this is the same bug as reported here: https://pact-foundation.slack.com/archives/C9VBGLUM9/p1677060601328999

**Comment by TimothyJones** [comment]
Oh, you reported it the first time. Carry on!

**Comment by lhokktyn** [comment]
Just picking up on this as we too have come across this behaviour of `afterEach` being prematurely called in the latest version (`13.1.13`).

Log snippet:
```
DEBUG ThreadId(02) verify_interaction{interaction="a sample status description"}: hyper_util::client::legacy::pool: reuse idle connection for ("http", 127.0.0.1:58805)
DEBUG (37023): pact@13.1.3: incoming request: {"body":{},"headers":{"accept":"application/json","accept-encoding":"gzip, deflate","host":"127.0.0.1:58805"},"method":"GET","path":"/find"}
DEBUG (37023): pact@13.1.3: Proxying GET: /find
DEBUG (37023): pact@13.1.3: executing 'afterEach' hook
DEBUG (37023): pact@13.1.3: outgoing response: {"body":"[]","headers":{"content-type":"application/json","content-length":"2","connection":"close"},"status":200}
```

`afterEach` appears to be executed in between the `Proxying GET: /find` activity, and the `outgoing response...` activity, whereas I'd expect `afterEach` to be mentioned _after_ the response had completed.

This means we're unable to use `afterEach` to perform any state clean up because doing do will clear out the state before the response has had a chance to be built.

**Comment by YOU54F** [comment]
Should be resolved by https://github.com/pact-foundation/pact-js/pull/1242

Feel free to comment back or raise a new issue if not sorted
