### ISSUE TITLE
'log' does not exist in type 'PactV3Options'

### ISSUE THREAD

**Issue by stevenKirill** [pact-foundation/pact-js#1080]
### Software versions

- **OS**: _e.g. Mac Ventura OSX 13.2.1 (22D68)
- **Consumer Pact library**:"@pact-foundation/pact": "^11.0.2",
- **Provider Pact library**: "@pact-foundation/pact": "^11.0.2",
- **Node Version**: `18`

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
correct type fot log property

### Actual behaviour
log doesn't exist

### Steps to reproduce

export const provider = new PactV3({
  consumer: 'gpb-expert-consumer',
  provider: 'gpb-expert-provider',
  logLevel: 'info',
  log: path.resolve(process.cwd(), 'logs', 'pact.log'),
  dir: path.resolve(process.cwd(), 'pacts'),
  spec: SpecificationVersion.SPECIFICATION_VERSION_V2,
});

### Relevan
<img width="870" alt="Screenshot 2023-03-31 at 16 09 37" src="https://user-images.githubusercontent.com/47239173/229128848-9cdec332-1fe4-4b4b-91d1-f847dc6e4ea6.png">
t log files

**Comment by mefellows** [comment]
Yes, Log doesn't exist on that type. Have we documented it somewhere that we have?

**Comment by mefellows** [comment]
There is an open feature request for logging to file here: #954. Closing this (unless it's a different big/feature, please reopen and clarify if that's the case).

**Comment by TimothyJones** [comment]
The missing `log` parameter isn't mentioned in the [migration instructions](https://github.com/pact-foundation/pact-js/blob/master/docs/migrations/9-10.md#migrating-from-9xx-to-10xx). 

It looks like the migration instructions aren't a distillation of the notes on breaking changes - for example, the verifier instructions say [no changes required](https://github.com/pact-foundation/pact-js/blob/master/docs/migrations/9-10.md#provider), but there were actually several changes to the options [detailed here](https://github.com/pact-foundation/pact-js/blob/master/MIGRATION.md#verifier-options)

**Comment by mefellows** [comment]
Yes that's a good point, i'll raise a separate tracking issue for that now.
