### ISSUE TITLE
Documentation no longer says you need to delete the pacts before each run

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#1085]
Pact-JS 11.0.2

From [slack conversation here](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1681285666137429?thread_ts=1681284075.287849&cid=C9VBGLUM9).

As far as I can tell, the documentation doesn't currently say that you need to delete the pact directory before each run. I know it used to say this.

Unless I'm missing something, this is still required, as otherwise removing interactions would cause ghost interactions from the previous time the pact file was written.

**Comment by mefellows** [comment]
It was listed in the [migration](https://github.com/pact-foundation/pact-js/blob/master/docs/migrations/9-10.md) guide, but should be added to the consumer docs.

I've updated the consumer guide just now also.
