### ISSUE TITLE
Mocha timeout issue while running "npm run test:provider"

### ISSUE THREAD

**Issue by akshaychouhan** [pact-foundation/pact-js#111]
## Software versions

* **OS**: e.g. Windows 10 Pro
* **Consumer Pact library**: e.g. Pact JS v Latest as on today
v2.6.0
* **Node Version**: v8.6.0

## Problem Statement
I was trying to run the E2E test, I followed the steps described there but first error I get on running consumer side "mocha --timeout 20000 test/consumer.spec.js" but it get executed successfully.
![image](https://user-images.githubusercontent.com/4429439/31442772-15d37acc-aeb5-11e7-84c4-8965238a68c6.png)

After that when I ran the provider side, I get the error " Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves."
![image](https://user-images.githubusercontent.com/4429439/31442867-62a9c842-aeb5-11e7-9276-33939c85009a.png)

Can you please check the issue and help me to resolve it.

P.S. I looked into two issues #5 #49 , but it doesn't help me to resolve the isusue.

**Comment by mefellows** [comment]
I'm a bit confused with your first statement, you seemed to indicate there was an error but said it ran successfully and the tests are green. Please clarify.

Any reason you haven't tried upgrading to `3.0.1` (current latest) to see if that resolves it?

If you could please provide an reproduceable project, that will help us fix it.

**Comment by akshaychouhan** [comment]
Issue has been resolved.. Closing this issue.
Thanks!

**Comment by mefellows** [comment]
No worries, would you mind sharing your solution for others?
