### ISSUE TITLE
Error: Pact publication failed due to windows file path limit exceeded 

### ISSUE THREAD

**Issue by SamLeachSky** [pact-foundation/pact-js#1116]
I have enabled the long file paths in windows already. This issue does not happen on mac.

If I move the code to a folder with  a shorter path, it does not error

### Software versions

- **OS**: Windows 10 22H2
- **Consumer Pact library**:  12.1.0
- **Provider Pact library**:  12.1.0
- **Node Version**: v18.17.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Published successfully

### Actual behaviour

Error: Pact publication failed with non-zero exit code. Full output was:
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

 ❯ ChildProcess.<anonymous> node_modules/.pnpm/@pact-foundation+pact-core@14.0.4/node_modules/@pact-foundation/pact-core/src/publisher.ts:129:27
 ❯ Object.onceWrapper node:events:629:26
 ❯ ChildProcess.emit node:events:526:35
 ❯ ChildProcess.cp.emit node_modules/.pnpm/cross-spawn@7.0.3/node_modules/cross-spawn/lib/enoent.js:34:29

### Steps to reproduce

Run on Windows with long file path

**Comment by mefellows** [comment]
It's a known issue with Ruby, and is documented in several open issues (search this project and `pact-core` repos).

The current bundled Ruby core uses version `3.2.0`, and the [fix](https://github.com/ruby/ruby/pull/4505) for long path was introduced in `3.0.2`, so there's not much else we can do to support this if Ruby doesn't.

Would you mind checking you followed the instructions in [this link](https://github.com/ruby/ruby/pull/4505) to see if it works?

Also, the logs above aren't super helpful in determining that this is indeed the issue, is that all there is? I've not seen the "side by side" error before.

Can you please also confirm that the same issue is present with `npm`?

**Comment by mefellows** [comment]
Closing as `wontfix`. There are other options for publication and the windows long path issue is well known.
