### ISSUE TITLE
Create Windows (Appveyor) build

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#112]
We currently suffer from a lack of visibility into Windows issues and reproduceability when there are issues.

We need to create a working Appveyor build as per other projects and make Windows a first class citizen!

**Comment by mefellows** [comment]
@thombergs if you're keen?! :)

**Comment by mboudreau** [comment]
@mefellows I might be able to get this done tomorrow

**Comment by thombergs** [comment]
Thanks for asking @mefellows. If it's still open next week or so I'll have a look. Since we're using pact-js and pact-jvm in my current (large-scale) project, you'll probably hear from me again, anyways :).

**Comment by Davidsoff** [comment]
seems to be broken now :cry:

**Comment by mefellows** [comment]
As in, pact js is _not_ working on Windows @Davidsoff ?

**Comment by Davidsoff** [comment]
no sorry my bad, appveyor build is not working because of a missing powershell script

**Comment by mefellows** [comment]
Cool. There is a branch that contains a starting point, but any help would be much appreciated. Marked as "help wanted".
