### ISSUE TITLE
verification error message is swallowed

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/pact-js#113]
When a consumer verification fails, the error message is logged, but not passed upwards to the caller. This means that you always have to look into the logs to find out what went wrong. 

For example, using `karma-pact`, when the tests are run in the browser, you get the output "verification failed" in the browser, but nothing else. Especially when you're starting with Pact, this makes for long bug hunts. It would be nice if the error message directly states what part of the verification failed.

**Comment by mefellows** [comment]
The design should be to throw an Error which should bubble up through any Promise chain. To be investigated.
