### ISSUE TITLE
Proposal: use @pact-foundation scope for pact dependency for consistency

### ISSUE THREAD

**Issue by mboudreau** [pact-foundation/pact-js#116]
All other pact-foundation packages are using this scoping, which can also prevent people from confusing the real pact libraries vs fake ones or [malicious ones, which has been shown to be attached to certain popular packages, but with a mispelling](https://iamakulov.com/notes/npm-malicious-packages/).

**Comment by mefellows** [comment]
Let's do this when we cut over to TS.

**Comment by mefellows** [comment]
We should also take into consideration #64 as this may have unintended consequences. The work you've done removing optional dependencies is probably going to mitigate this though, thankfully.

**Comment by mefellows** [comment]
See https://www.npmjs.com/package/@pact-foundation/pact - done :)
