### ISSUE TITLE
Add 'InteractionObject' to declared namespace in 'pact.d.ts'

### ISSUE THREAD

**Issue by argos83** [pact-foundation/pact-js#117]
Hi!

In some of our tests in a TypeScript codebase we require some logic to build an `InteractionObject` before passing it to the `addInteraction` function on the `PactProvider` object. I.e.:

```js
const interaction: InteractionObject = { ... };
if (someCondition) {
  interaction.willRespondWith.body = {some: 'value'};
}
mockProvider.addInteraction(interaction);
```

We are currently importing the type definitions this way:

```js
import * as pact from 'pact';
import {InteractionObject} from 'pact/src/dsl/interaction';
```

However since we upgraded `ts-lint` from `5.6.0` to `5.7.0` it started complaining about the second import line:

```
Submodule import paths from this package are disallowed; import from the root instead. (no-submodule-imports)
```

I was wondering if you would be willing to include the `InteractionObject` interface to the namespace declared in `pact.d.ts`. If you agree I can submit a PR with the changes.

## Software versions
* **Consumer Pact library**: Pact JS v3.0.1

## Expected behaviour

It should allow importing the `InteractionObject` interface from the main module

## Actual behaviour

`InteractionObject` needs to be imported from a submodule (outside the root).

**Comment by mefellows** [comment]
Thanks @argos83 - I would happily accept a PR (we're converting the repo to TypeScript, but this would be much appreciated in the meanwhile).

**Comment by mefellows** [comment]
FYI my current plan is to re-export the type out of the `pact` interface. See the branch `feat/typescript` if you're keen to review or help out.

**Comment by mefellows** [comment]
Closing, this has been in the codebase since `5.x.x` release.
