### ISSUE TITLE
Because Maths: invalid pact specification version supplied: 5

### ISSUE THREAD

**Issue by rholshausen** [pact-foundation/pact-js#1185]
I got me some of this:
![image](https://github.com/pact-foundation/pact-js/assets/38309842/513c99b0-f23a-4c70-ab59-7f11fa0ad23c)

I assume this is just for the hell of it:
```typescript
export enum SpecificationVersion {
  SPECIFICATION_VERSION_V2 = 3,
  SPECIFICATION_VERSION_V3 = 4,
  SPECIFICATION_VERSION_V4 = 5,
}
```
https://github.com/pact-foundation/pact-js/blob/master/src/v3/types.ts#L3C1-L7C2

**Comment by JP-Ellis** [comment]
Isn't this the counterpart of the `PactSpecification` enum defined in `pact.h`?

```C
/**
 * Enum defining the pact specification versions supported by the library
 */
typedef enum PactSpecification {
  /**
   * Unknown or unsupported specification version
   */
  PactSpecification_Unknown,
  /**
   * First version of the pact specification
   */
  PactSpecification_V1,
  /**
   * Second version of the pact specification 
   */
  PactSpecification_V1_1,
  /**
   * Version two of the pact specification
   */
  PactSpecification_V2,
  /**
   * Version three of the pact specification 
   */
  PactSpecification_V3,
  /**
   * Version four of the pact specification
   */
  PactSpecification_V4,
} PactSpecification;
```

**Comment by rholshausen** [comment]
No, the issue is that PactV3Options has 
```typescript
  /**
   * Specification version to use
   */
  spec?: SpecificationVersion;
```
https://github.com/pact-foundation/pact-js/blob/master/src/v3/types.ts#L102

If you try use that enum value SPECIFICATION_VERSION_V4 , you get that error.

**Comment by JP-Ellis** [comment]
It seems correct to me to use `spec?: SpecificationVersion` with an enum. I'm guessing then that the num is incorrectly handled elsewhere and is converted to an integer in a somewhat naive way? Or perhaps some confusion between ints and enum values in:

https://github.com/pact-foundation/pact-js/blob/59081f2b08d7258abe9b2969c4affa0cbb0c95d1/src/common/spec.ts#L3-L21

**Comment by mefellows** [comment]
Can you please show the `MessageConsumerPact` constructor you used?

**Comment by mefellows** [comment]
I can see the problem, I think.

**Comment by rholshausen** [comment]
Ah, you are correct. 
```typescript
  // Specification Version (should be 3 for messages)
  spec?: number;
```

This is confusing. Also not having V4 support for asynchronous messages.

**Comment by mefellows** [comment]
Yeah, I have an open branch with partial support for the updated asynchronous interface (this was the original one that supported the Ruby messaging API, and doesn't support plugins etc.).

I'll update the comment for now.

**Comment by mefellows** [comment]
I'll close this and open a feature request for Async Messages
