### ISSUE TITLE
Pact-js doesn't support date matching

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#120]
## Software versions

* **OS**: Mac OSX 10.12.6
* **Consumer Pact library**: pact-js 4.0.0
* **Node Version**: v8.4.0

## Issue

I'm not sure if this is the right repository for this issue. I'm opening it here, because I'm hitting it while using `pact-js`.

As far as I can see we currently have to roll our own matchers when trying to match dates. I'd prefer not to think about date formats and be able to express "match a date that is compliant with [RFC-2822](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15)" or something similar.

Unfortunately, the RFC/ISO formats are [not a good fit](https://stackoverflow.com/a/25362759/790070) for regex, and the resulting regex can be [long](https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/). Even if we just want to stick the ES standard (which is a [subset of ISO 8601](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15)), a regex is not easy. 

If we don't want to roll our own regex, it's good to find one that someone else has written and tested. However, that there aren't many premade Ruby regexes for dates. I think this is because Ruby provides a bunch of nice date parsing methods already.

There are [these helpers](
https://github.com/pact-foundation/pact-support/blob/master/lib/pact/helpers.rb
), which almost do what we want, but I'm not across the Pact ecosystem enough to know if they can be easily exposed to `pact-js`.

## Current behaviour

Even simple date formats end up with a long regex: 

      willRespondWith: {
            status: 200,
            headers: headers.response,
            body: {
                 startDate: term({
                     matcher: 'dddd-[0-1]d-[0-3]d',
                     generate: '2012-01-12'
                 })
            }
       }

Matching or requiring timezones would result in a much more complex regex. This is a disadvantage, because communicating dates without timezone information easily leads to bugs. So, I'd like to be able to express dates with a format:

## Proposals

It would be nice to be able to say:

      willRespondWith: {
            status: 200,
            headers: headers.response,
            body: {
                  // require a specific date format
                  startDate: likeDate({ 
                      format: 'YYYY-MM-DD Z',
                      generate: '2012-01-12 +10:00'
                  })
            }
       }

I could also see a use for something like this:

      willRespondWith: {
            status: 200,
            headers: headers.response,
            body: { 
             // Allow any ISO 8601 date
             startDate:  likeIso8601Date('2009-05-19 14:39:22-06:00')
            }
       }

or even cooler, for flexible matching:

      willRespondWith: {
            status: 200,
            headers: headers.response,
            body: {
                  // Allow any ISO 8601 date that includes a timezone
                  startDate: likeIso8601Date({
                    requireTimezone: true,
                    generate: '2009-05-19 14:39:22-06:00'
                  }),
            }
       }

**Comment by mefellows** [comment]
Thanks Tim, we'll add a bunch of matchers similar to PactJVM. Perhaps this could be added as a recommendation to the pact-specification.

I'll mark for enhancement, but won't start work on this until the TypeScript implementation is finished.

**Comment by TimothyJones** [comment]
I think it's in the version 4 roadmap: https://github.com/pact-foundation/pact-specification/tree/version-4

**Comment by mefellows** [comment]
I like your `likeDate` proposal, however that looks like it might be a stretch to implement. I'll have to think on it. The trick would be to be able to automatically generate an enforceable regex from your date format string (in this case, `YYYY-MM-DD Z`) to send over the wire. Granted, it is almost 3am, but my brain will need some time to come up with a way of doing this. I
 
Certainly, a series of `iso8601DateTime` type matchers would be doable. I'll be adding these in soon anyway to match JVM at least as close as I can.

**Comment by abubics** [comment]
Libraries like `date-fns` might help with implementation, and/or inspiration :)

**Comment by mefellows** [comment]
FYI have created a number of simple matchers as per your second option. These will be available in the next release, which I hope to push out in the next week or so.

| method | description |
|--------|-------------|
| `boolean` | Match a boolean value (using equality) |
| `integer` | Will match all numbers that are integers (both ints and longs)|
| `decimal` | Will match all real numbers (floating point and decimal)|
| `hexadecimal` | Will match all hexadecimal encoded strings |
| `iso8601Date` | Will match string containing basic ISO8601 dates (e.g. 2016-01-01)|
| `iso8601DateTime` | Will match string containing ISO 8601 formatted dates (e.g. 2015-08-06T16:53:10+01:00)|
| `iso8601DateTimeWithMillis` | Will match string containing ISO 8601 formatted dates, enforcing millisecond precision (e.g. 2015-08-06T16:53:10.123+01:00)|
| `rfc3339Timestamp` | Will match a string containing an RFC3339 formatted timestapm (e.g. Mon, 31 Oct 2016 15:21:41 -0400)|
| `iso8601Time` | Will match string containing times (e.g. T22:44:30.652Z)|
| `ipv4Address` | Will match string containing IP4 formatted address |
| `ipv6Address` | Will match string containing IP6 formatted address |
| `uuid` | Will match strings containing UUIDs |

For the v4 matching, we'll have to wait a bit longer I'm afraid (nothing we can do from JS land I can think of to address it, as it's not pure regex based).

**Comment by TimothyJones** [comment]
Thanks! Those new matchers will suit our needs perfectly!

**Comment by mefellows** [comment]
You're welcome! ;)

**Comment by bethesque** [comment]
These are all string matchers, right? Because we don't currently do matching on numbers or booleans. We can add it, but it won't work until the change is made in the Ruby impl.

**Comment by mefellows** [comment]
Correct. The `integer` and `decimal` matchers are simply convenience matchers for the `like` matcher (the `decimal` defaults to `13.01` to ensure it's a float!!)

**Comment by mefellows** [comment]
Are you happy for me to close this now @TimothyJones ? `5.x.x` is now in train 
 https://www.npmjs.com/package/@pact-foundation/pact (will run concurrently with the `4.x.x` branch for a little bit as there were some significant changes).

**Comment by TimothyJones** [comment]
Sounds good! Thanks!

**Comment by mefellows** [comment]
👍

**Comment by vlaraort** [comment]
Hi @mefellows, good work here!! Can you provide some examples about how to use those matchers, I can't find anything in the documentation

**Comment by mefellows** [comment]
All the matchers really are, are "standard" regular expressions.

So doing something like this: 

```js
provider.addInteraction({
  ...
   "date": Matchers.iso8601DateTimeWithMillis()
  ...
})
``` 

will ensure that a provider must return a string in the `date` field that looks like `2015-08-06T16:53:10.123+01:0`.

**Comment by seyfer** [comment]
In js, the most popular way to transfer the full date to BE and back to FE is to use an ISO string.
It can be created with the use of `Date.toISOString()` method, and the format 
`2023-03-01T23:00:00.000Z`

It does not match to available v2 matches `iso8601DateTimeWithMillis` and `iso8601DateTime`
the format that Date gives for ISO is more of a combination of matchers iso8601Date and iso8601Time in one.
And such a matcher does not exist.

is there a way to combine them with matching `2023-03-01T23:00:00.000Z`? 
or would it be better to use the v4 matcher `datetime` with the matching format in the first argument?

**Comment by TimothyJones** [comment]
If you're experiencing a bug, could you open an issue? This issue was about supporting the date matchers originally, and has (appropriately) been long closed.

Also, why doesn't `iso8601DateTime` work for you? The string you've given appears to be in simplified extended ISO 8601 format, and matches the `iso8601DateTime` regular expression perfectly.

(Aside: I did notice that the regular expression doesn't cover [expanded years](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-expanded-years), which is definitely a bug and should be corrected - but this is only a problem if you're trying to represent years before 0 or after 9999).
