### ISSUE TITLE
MatchersV3.reify doesn't extract payload from MatchersV3.nullValue()

### ISSUE THREAD

**Issue by ledniov** [pact-foundation/pact-js#1229]
I'm using `MatchersV3.reify` in the project to strip Matchers from the object and use payload for assertion.
However, `MatchersV3.nullValue()` is not processed.

### Software versions

- **OS**: 22.04.2-Ubuntu
- **Consumer Pact library**: Pact JS v13.1.0
- **Node Version**: v18.19.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

`MatchersV3.nullValue()` is processed correctly and value is transformed to `null`

### Actual behaviour

The `reify` method doesn't process `MatchersV3.nullValue()` matcher

```
Expected value to deeply and strictly equal to:
    {"nullProp": null, "stringProp": "sample string"}
Received:
    {"nullProp": {"pact:matcher:type": "null"}, "stringProp": "sample string"}
```

### Steps to reproduce

See test - https://github.com/ledniov/pact-js-repro-template/blob/reify-bug/reify.spec.ts

### Relevant log files

Github Actions runs - https://github.com/ledniov/pact-js-repro-template/actions/runs/9905937116

**Comment by mefellows** [comment]
Thanks for spotting @ledniov, appreciate the repro too. I think the fix is straightforward, testing a build now.

**Comment by mefellows** [comment]
This should be fixed now, please let us know how you get on.

**Comment by ledniov** [comment]
@mefellows , appreciate the quick fix! 
I already upgraded to the new version and everything works as expected.
Thank you!

**Comment by mefellows** [comment]
Excellent, thanks!
