### ISSUE TITLE
Please add --monkeypatch option to pact mock service start up command and pact-provider-verifier command

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#123]
Requires standalone version pact-1.19.0.

This is to support: https://github.com/pact-foundation/pact-mock_service/issues/78 and another issue that I can't currently find.

The feature that the user is requesting is not something that should be changed for all users, as it is a non-standard behaviour, and breaks the Rack spec. However, we can allow the underlying code to be monkey patched for his specific use case. The value supplied to `--monkeypatch` will be an absolute path to a ruby file that will monkeypatch the underlying header logic.

This is not something that we need to document, but we can use it to deal with edge cases when necessary!

**Comment by mefellows** [comment]
Moving this to `pact-node` as that is where the the CLI is integrated.

**Comment by bethesque** [comment]
Thanks, I'll close this then.
