### ISSUE TITLE
Issue while installing version 11.x in Vercel

### ISSUE THREAD

**Issue by sagar-go** [pact-foundation/pact-js#1255]
I am facing issue while installing pact js in Vercel. I am currently using version 11 and would like to stick with it. 

I feel issue while using Node Js 20.0.0, however, it work fine for lower versions. Is there a way I can use version 11 with Node 20? 

Documentation suggests to use pact 12+ , but I due to company limitations I can’t upgrade it…

**Comment by YOU54F** [comment]
I would use the latest version pact-js. why can you not upgrade to pact-js v12+?

**Comment by mefellows** [comment]
To help us fix the issue, we'd need to understand the problem - could you please provide some of the steps suggested in the issue template?

**Comment by sagar-go** [comment]
@mefellows 

All I am trying to do is install pact foundation version 11.x with Node version 20.

![Uploading IMG_1305.png…]()

**Comment by sagar-go** [comment]
Issue fixed after upgrading to version 12+
