### ISSUE TITLE
Slash in consumer name results in folders being created

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#126]
## Software versions

* **OS**: Mac OSX 10.11.6 (15G1611)
* **Consumer Pact library**: Pact JS 4.2.1
* **Provider Pact library**: NA
* **Node Version**:  v8.3.0

When the consumer or provider names contain a slash, the slash is passed through to the file system, which creates folders:

## Expected behaviour

Full pact filename is present in the `pacts/` folder, something like: `pacts/a_b client-a_b api.json`

Alternatively, some kind of error that provider/consumer names are not allowed to contain slashes.

## Actual behaviour

Pact file in a few folders deep: `pacts/a/b client-a/b api.json`

## Steps to reproduce

Use the following `pact()` call:

```
  const provider = pact({
    consumer: 'A/B Client',
    provider: 'A/B API',
    port,
    done: error => expect(error).to.be.null
  });
```

**Comment by bethesque** [comment]
I'm trying to think of an example where a service name would have a slash in it! But yes, we should do one of the two.

**Comment by bethesque** [comment]
Can you raise this in the pact-mock_service repository? That's where the logic is.

**Comment by TimothyJones** [comment]
The example we have is an API for A/B testing. I'll raise the issue over there now.

**Comment by TimothyJones** [comment]
Done: https://github.com/pact-foundation/pact-mock_service/issues/81

I suppose we should close this one now?

**Comment by mefellows** [comment]
I think it's an acceptable string to use, I would suggest we properly escape the names and let it be used (and not created the subfolders).

**Comment by mefellows** [comment]
Let's leave this open for the time being until we understand if changes are required here also.

**Comment by TimothyJones** [comment]
Changes were not required :)
