### ISSUE TITLE
PactJs not support Jest@21.2.1

### ISSUE THREAD

**Issue by dongxiaonan** [pact-foundation/pact-js#132]
## Software versions

* **Windows 8
* **Consumer Pact library**: Pact JS v4.2.1
* **Node Version**: node  v8.2.1
* **Testing framework and version**: Jest@21.2.1

## Actual behaviour
![image](https://user-images.githubusercontent.com/5782358/33697996-c35871dc-db44-11e7-97ee-6bdcd21f718b.png)

## Steps to reproduce
Setup the example given by pactJs - Jest.
Install the jest with latest package.
run the test, it will fail.

When try to install Jest@20.0.0
run the test, could get correct result

**Comment by mefellows** [comment]
This sounds like more a problem with Jest than with Pact. What's changed between those two versions?

**Comment by mefellows** [comment]
OK just took a quick look. Looks like the way Jests resolve promises in tests now fail if there is content returned to the successful promise. Modified the tests and bumped version to `v21.x.x`. Check examples.
