### ISSUE TITLE
logLevel option not being honored

### ISSUE THREAD

**Issue by BenSayers** [pact-foundation/pact-js#139]
## Software versions

* **OS**: 10.12.6
* **Consumer Pact library**: pact@4.3.1
* **Provider Pact library**: N/A
* **Node Version**: 8.9.3

## Expected behaviour

When a pact mock is created using `logLevel` set to `error` that only error or more severe logs lines appear.

## Actual behaviour

An info log line is appearing:

```
Creating Pact Server with options:
    host = 127.0.0.1,
    port = 9000,
    log = /path/to/pact.log,
    dir = /path/to/dir,
    spec = 2,
    ssl = false,
    sslcert = false,
    sslkey = false,
    cors = false,
    pactFileWriteMode = overwrite
```

## Steps to reproduce

Create a pact mock with the log level set to `error`. For example:
```
pact({
    consumer: 'my-consumer',
    dir: 'pacts',
    log: 'pacts/pact.log',
    logLevel: 'error',
    port: 9000,
    provider: 'my-provider',
    spec: 2
});
```

Simply executing this one line of code will result in a log line.

It looks to me like the issue is on this line:
https://github.com/pact-foundation/pact-js/blob/4.x.x/src/pact.js#L71

The log level needs to be set prior to creating the server as creating the server logs.

I tried to put together a PR to fix this myself but I couldn't get a local dev environment setup where the tests all pass.

**Comment by mefellows** [comment]
Thanks @BenSayers, I'll see if I can fix this today - good spot!

**Comment by mefellows** [comment]
I've published 4.3.2, which contains the fix for above. Closing, and thanks again.

**Comment by mefellows** [comment]
Oh, and I'm porting this fix to the 5.x.x branch also.

**Comment by BenSayers** [comment]
Thanks @mefellows, I just bumped and tested, looks good 👍
