### ISSUE TITLE
Pact startup failed

### ISSUE THREAD

**Issue by lemon123456** [pact-foundation/pact-js#140]
## Software versions

* **OS**: Mac 10.12.6
* **Consumer Pact library**: Pact@4.3.1
* **Node Version**: `node --8.5.0`

## Expected behaviour

Pact startup a mock server.

## Actual behaviour

Following is the error info: 
```
pact-exercise git:(master) ✗ npm run ctest

> pact-exercise@1.0.0 ctest /Users/twer/Documents/AutoTest/Contract test/pact-exercise
> mocha --timeout 15000 test/**/consumer.spec.js

[2018-01-03T07:01:36.485Z]  INFO: pact-node@6.7.0/7060 on xxj.local:
    Creating Pact Server with options:
    host = localhost,
    port = 8080,
    log = /Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log,
    dir = /Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts,
    spec = 2,
    ssl = false,
    sslcert = false,
    sslkey = false,
    cors = false,
    pactFileWriteMode = overwrite


  Pact
    when there is matched user
[2018-01-03T07:01:36.527Z]  INFO: pact-node@6.7.0/7060 on xxj.local: Created './platforms/darwin/bin/pact-mock-service service --host 'localhost' --port '8080' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'' process with PID: 7061
error { Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080,
  response: undefined }
      1) should response with user with id and name


  0 passing (51ms)
  1 failing

  1) Pact
       when there is matched user
         should response with user with id and name:
     Error: connect ECONNREFUSED 127.0.0.1:8080
      at Object._errnoException (util.js:1026:11)
      at _exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)



(node:7060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:8080
(node:7060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-01-03T07:01:36.565Z]  WARN: pact-node@6.7.0/7060 on xxj.local: Pact exited with code 1.
[2018-01-03T07:01:36.565Z]  INFO: pact-node@6.7.0/7060 on xxj.local: Removing Pact with PID: 7061
(node:7060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Pact startup failed; tried calling service 10 times with no result.
^@^@^@^@^@^@^@
```

Also, run the following on my machine:

``` pact-exercise git:(master) ✗ ./node_modules/@pact-foundation/pact-standalone/platforms/darwin/bin/pact-mock-service service --host '127.0.0.1' --port '2202' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'```

the output is:

```/Users/twer/Documents/AutoTest/Contract test/pact-exercise/node_modules/@pact-foundation/pact-standalone/platforms/darwin/lib/ruby/bin/ruby: line 14: test/pact-exercise/node_modules/@pact-foundation/pact-standalone/platforms/darwin/lib/ruby/lib/ruby/gems/2.2.0: No such file or directory```

My ruby version is 2.2.3.

```
 pact-exercise git:(master) ✗ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

## Steps to reproduce

The repository [pact-exercise](https://github.com/lemon123456/contract-test-pactjs.git)
Clone the code and execute commands below:
```
npm install
npm run ctest
```

**Comment by mefellows** [comment]
Thanks for this, I'll see if I can repro tomorrow

**Comment by dj-niobium** [comment]
@mefellows I had the same problem. The reason was that pact-mock_service gem was not installed. After `sudo gem install pact-mock_service` it started to work. Maybe it makes sense adding this to readme?

**Comment by mefellows** [comment]
@dj-niobium woah! No, you shouldn't have to do anything with Ruby. In fact, you should basically be unaware Ruby is involved in this process altogether. 

We package a Ruby runtime in the project, including all required gems. So this indicates another issue (worth digging into).

**Comment by dj-niobium** [comment]
@mefellows yeah, looks odd. However, the fact is that I've got the ECONNREFUSED and after digging I've found out that the server was not being started. I assumed that it had something to do with the WebRick server and installing of pact-mock-service truly did help. So I think what happens is that even in the case of Node not installing the ruby ecosystem correctly, the pact package is being installed anyway. And on the point of the pact setting up the mock server, it fails silently and we're getting the  ECONNREFUSED because of the server absence afterwards. But this is just a guess.

**Comment by mefellows** [comment]
I'm not doubting that the fix worked, but obviously this isn't going to be a solution we want going forward. 

So ideally, it would be good to understand the state before and after running this command. 

Pact JS starts the mock service from a very specific path, so the fact that running a `gem install` works, tells us that it must either modify the local Ruby environment (in the npm package) or a global one, that is accessible by the local env (possible, although by design of Traveling Ruby this should not be able to happen).

**Comment by mefellows** [comment]
@lemon123456 there were a number of issues with your setup that you need to address:

1. You have both the new `@pact-foundation/pact` and old `pact` dependency, but are only referencing the old one (and using the old constructor). You should obviously use one or the other (I'd suggest latest)
2. You don't return the promise in your `before` block, so it immediately exits and runs your test (`it`) where you get a connection refused, as the mock server has not yet started. *This is why you are getting a connection refused error.*
3. You are logging the error from your API call to the mock server, which is fine, but as you'll note you aren't getting the rich diff that Pact displays. If you were to execute the `provider.verify()` function always, it will tell you what was wrong. In your case, you've told Pact to expect a particular header (via `headers: { 'Accept': 'application/json' }`) but are not passing it through, and thus Pact _does not match on this_ and fails.

Lastly, and of particular importance/note, all of the sequencing of this information is in the `pact.log` file:

```
...
E, [2018-01-15T08:02:16.047162 #20532] ERROR -- : No matching interaction found for GET /user/1
E, [2018-01-15T08:02:16.047187 #20532] ERROR -- : Interaction diffs for that route:
E, [2018-01-15T08:02:16.047635 #20532] ERROR -- : Diff with interaction: "a request for get user" given "have a matched user"
Diff
--------------------------------------
Key: - is expected
     + is actual
Matching keys and values are not shown

 {
   "headers": {
-    "Accept": "application/json"
   }
 }

Description of differences
--------------------------------------
* Could not find key "Accept" (keys present are: Host, Accept-Encoding, User-Agent, Connection, Version) at $.headers

W, [2018-01-15T08:02:16.059133 #20532]  WARN -- : Verifying - actual interactions do not match expected interactions.
Incorrect requests:
	GET /user/1 (request headers did not match)


W, [2018-01-15T08:02:16.059171 #20532]  WARN -- : Incorrect requests:
	GET /user/1 (request headers did not match)

```

**Comment by mefellows** [comment]
I've also submitted a PR for your example to show you how to fix it. Hope this helps!
