### ISSUE TITLE
Provider test verification using json file uploaded in pact server

### ISSUE THREAD

**Issue by 210178** [pact-foundation/pact-js#144]
I would like to know, how provider retrieves the json file uploaded in pact server and compare against the actual provider response. Once it's validated, how the provider test results are published in pact server??

Following is my provider test code snippet,

const Verifier = require('pact').Verifier
const options = {
    provider: 'Receive',
    providerBaseUrl: 'http://localhost:8080',
    pactBrokerUrl: 'http://test-broker-url:30038/',
    tags: [ 'prod', 'test' ],
    pactFilesOrDirs: [ 'http://test-broker-url:30038/pacts/provider/testProvider/consumer/testConsumer/latest' ],
    providerVersion: '1.0.0'
}

I have started my provider service and get the response, now i have the following piece of code to extract the json file that was uploaded in pact server. While logging the response in console, I am not getting the actual response.  Please let me know what I am missing or doing wrong here?? Also, how can I see the provider test verification status in pact server after I have validated my test.

            Verifier.verifyProvider(options)
                    .then((pactResponse) => {
                        console.log('pact response:', JSON.stringify(pactResponse))
                    })
                    .catch((error) => {
                         console.log('error:', JSON.stringify(error.message))
                    })

**Comment by mefellows** [comment]
I'm not sure what you are asking for, sorry. Is there a bug, or are you looking for getting started type information?

As per the README, i'd start with:
* Reviewing one of the E2E examples in the `examples` directory of this repository.
* Completing a 60 minute workshop to understand all of the concepts: https://github.com/DiUS/pact-workshop-js

**Comment by 210178** [comment]
@mefellows - Thanks for your quick response. I have gone through the provider example and I don't see any where in the test that end point (/provider) has been called. Considering that, 
1. How come that endpoint will be called in the test?
2. I could see that the test has pack broker url, how it will fetch the exact pact file which was uploaded by consumer?
3. I assume that the pact file will be compared against our actual service response (meaning http://localhost:8080/provider response). No where in the code, we are doing that ...

Please clarify ...

**Comment by 210178** [comment]
@jcarlos / @lirantal / @screamish  - I have some questions on the pact provider test, is somebody available to clarify that?

**Comment by mefellows** [comment]
> I have gone through the provider example and I don't see any where in the test that end point (/provider) has been called

Pact is responsible for doing this. We start the provider server in the provider tests here https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js#L33-L35

...and invoke Pact (which in turn calls that provider for all of the interactions captured in the pact file) here: https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js#L61-L64

Our "code" isn't calling that endpoint, Pact is!

> How come that endpoint will be validated in the test?

As per above. If you don't believe me, add logging or modify the reponse by removing a field in https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/data/animalData.json


> I could see that the test has pack broker url, so it would fetch the JSON file from pact server. Since we haven't mention the actual JSON file, how it will fetch the exact pact file which was uploaded by consumer?

We have created a consumer test and published to the broker. The Pact verifier is clever, it knows how to find all of the pacts for this Provider given a broker URL: https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js#L42-L59

It will find the latest pact (which we just published from the consumer) and replay the interactions against the provider. If they don't match, it fails.

> I assume that the pact file will be compared against our actual service response (meaning http://localhost:8080/provider response). No where in the code, we are doing that ...

As per above, this is not true.

If you would like further clarification, please seek them on the forums, this is not the place.
