### ISSUE TITLE
Regarding validating the states in provider test

### ISSUE THREAD

**Issue by 210178** [pact-foundation/pact-js#145]
@mefellows - I have a GET endpoint which accept 'id' as path param. my cucumber test is like,
Scenario:1 - (valid student id - meaning id is available in db)
GIVEN I have a student id "123"
WHEN I request student details with student id
THEN I should get a successful response with student details

Scenario:2 -
GIVEN I have a student id "200" (invalid student id - meaning id isn't available in db)
WHEN I request student details with student id
THEN I should get an error response

FYI, I have gone through the E2E tutorial (https://github.com/pact-foundation/pact-js/tree/master/examples/e2e). Still I am not clear about how we can validate those states in our provider.

In the above scenarios, my states are

- I have a student id "123"
- I have a student id "200"

Please give me an example for how to set the 'setup' endpoint in provider test for this scenario ....

**Comment by 210178** [comment]
@mefellows - Sorry I cant share you our repository due to our client policy. 
Please send me your forum link, i will post my questions going forward

I am trying to implement the setup functionality using koa JS framework, please find below code snippet.

const app = require('../index')
const impress = require('impress-router')
const router = new impress()

router.post('/setup', setup)

async function setup(ctx, next) {
    console.log('Entering into setup() !!!!!!!!!!!!!!!!!')
    const state = ctx.request.get('state')
    console.log('state1:', state)
/**
    console.log('state2:', JSON.stringify(ctx.request.body))
    console.log('state3:', ctx.params.state)
**/
    ctx.response.status = 200
    next()
}

app.use(router)
app.listen(8080)

In all my cases, I am getting either a blank or undefined value while printing my state value. I have used the following url in my provider config.

const opts = {
            provider: 'Receive',
            providerBaseUrl: 'http://localhost:8080',
            providerStatesSetupUrl: 'http://localhost:8080/setup',
            pactBrokerUrl: 'my pact broker url',
            tags: [ 'prod', 'test' ],
            pactFilesOrDirs: [ latest pact file url ],
            publishVerificationResult: true,
            providerVersion: '0.0.50'
        }
am i missing anything here? Please send me your forum link, i will post my questions going forward

**Comment by mefellows** [comment]
That's OK, it doesn't need to be your _actual_ application, just a working Koa example that we can reproduce any problem. 

Your above code looks OK to me, albeit I've not used Koa before. ` console.log('state2:', JSON.stringify(ctx.request.body))` looks more correct though, as the request should come through as a JSON body, not a GET parameter.

As per the README, you can ask questions on gitter.im/realestate-com-au/pact.

Just to reiterate, if you can provide a reproducible code base (doesn't need to be a real/sensitive application) here, we'll do our best to fix it.

**Comment by 210178** [comment]
Thanks @mefellows

**Comment by 210178** [comment]
@mefellows - I have fixed this issue, please go ahead and close :-)

**Comment by mefellows** [comment]
Thanks. Is there anything to share with the community on this?

**Comment by 210178** [comment]
No, I am good now. Please go ahead and close this

**Comment by mefellows** [comment]
I understand _you're_ good, is anything you've learned that the community might benefit from your experience?
