### ISSUE TITLE
Non-HTTP consumers and producers

### ISSUE THREAD

**Issue by mkozjak** [pact-foundation/pact-js#15]
Hello,

I've been looking into incorporating Consumer-Driven Contracts into my project microservices which ultimately use [NATS](https://nats.io) at their endpoints.

Is this library supposed to be used only in HTTP API environments or can I use it for other protocols also? I only see you mention HTTP-specific properties...

**Comment by tarciosaraiva** [comment]
hey @mkozjak unforutnately no. There's an [implementation on pact-jvm](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#consumer-test-for-a-message-consumer) for message queues but not on JS at this stage.

You're welcome to send a PR :)

**Comment by mkozjak** [comment]
Is this everything that's currently defined regarding V3's messages?

https://github.com/pact-foundation/pact-specification/tree/version-3#introduces-messages-for-services-that-communicate-via-event-streams-and-message-queues

**Comment by uglyog** [comment]
The spec just introduces the concept of pacts for async message based comminucation. For an implementation example, have a look at https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-groovy#step-1---define-the-message-expectations and https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/README.md#verifying-a-message-provider-version-2212

**Comment by uglyog** [comment]
But we could look at introducing NATS support, we just need to extend the spec to introduce the concept of a protocol. It would be best if you raised an issue against the specification project.

**Comment by mkozjak** [comment]
@uglyog: Did it here: https://github.com/pact-foundation/pact-specification/issues/30

**Comment by mefellows** [comment]
Update on this: we have experimental support for messages pacts!

See https://github.com/pact-foundation/pact-js/tree/feat/message-pact

cc: @mkozjak - hopefully not too late :)

I'm going to close this as we are tracking its progress in #166

**Comment by klyff** [comment]
Hello,
Does Spec v3 support MessageQueue for PACT Java?
I saw that she no longer has the @PactVerification annotation that calls the build method for message consumption.
