### ISSUE TITLE
Update to the latest Typescript

### ISSUE THREAD

**Issue by katerynae** [pact-foundation/pact-js#152]
Hey guys!

After installing the latest version of pact-foundation our project starts getting Typescript errors like this one:

https://github.com/Microsoft/TypeScript/issues/16760

The issue is that we use Typescript 2.5.3 and Pact itself runs the old version which still has this old bug in it.

Is it possible to update pact to work with the latest Typescript?

**Comment by mefellows** [comment]
Yep we'll take a look, thanks!

**Comment by mboudreau** [comment]
Matt, I might have already done this in my other PR.

**Comment by mefellows** [comment]
@katerynae have updated to TS `v2.7.2` in latest version `v5.6.1` of Pact (on its way out). Let us know how you go!

**Comment by katerynae** [comment]
oh, I missed the message. Yeah, it worked fine for me, Thank you!

**Comment by mefellows** [comment]
You're welcome!
