### ISSUE TITLE
Look at reintroducing package-lock.json

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#153]
See https://medium.com/@tomastrajan/how-to-speed-up-continuous-integration-build-with-new-npm-ci-and-package-lock-json-7647f91751a, package lock will start to behave more in line with expectations.

The main thing to consider is cross OS compatibility, see pact-foundation/pact-node/issues/42 for background on this issue.

**Comment by mboudreau** [comment]
Have npm finally fixed their broken algorithm for optional dependencies?

**Comment by mefellows** [comment]
I'm not sure, I saw this link and had some hope. Obviously we won't be doing anything if it still has that issue (i.e. OS specific deps locked up in the `package-lock.json`).

**Comment by mboudreau** [comment]
well, optional dependencies might not be an issue anymore for us with the
new pact-node standalone packaging...
