### ISSUE TITLE
Error when using a Date type in the body

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [pact-foundation/pact-js#156]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact JS v5.3
"" Karma Pact Version**: 2.1.3
**Pact Node Version**: 6.7
**PAct Web Version**: 5.3
* **Node Version**: 6.11

## Expected behaviour

If in the interaction you specify the body like:
```
body: new Date()
```
or
```
body: like(new Date())
```
 it should accept it.

## Actual behaviour

Get an error response like:
```
ERROR: '500 - Internal Server Error {"message":"Error ocurred in mock service: JSON::ParserError - 757: unexpected token at '\"2018-02-28T15:21:34.823Z\"'","backtrace":["C:/Code/GIT/skyux-spa-email/node_modules/@pact-foundation/pact-standalone/platforms/win32/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'","C:/Code/GIT/skyux-spa-email/node_modules/@pact-foundation/pact-standalone/platforms/win32/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'","C:/Code/GIT/skyux-spa-email/node_modules/@pact-foundation/pact-standalone/platforms/win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.6.2/lib/pact/consumer/mock_service/rack_request_helper.rb:31:in `request_as_hash_from'"
```
## Steps to reproduce

1. Write a pact test with a Date in the body, *not* as a JSON object.
2. See the error.

This appears to work just fine with other types like a string of "123" or integers, but Dates are the problem.

**Comment by bethesque** [comment]
Dates are not a native JSON type. You'll need to convert it to a string. I believe there are some nice JS specific matchers for the various date formats. Have a search in the pact-js docs.

**Comment by xiaoningz** [comment]
i meet same problem with set the body as the string "Tag_PACT_1519821131303" with POST method,  by using below code, and i also try to set the content-type as "text/plain", it doesn't work.
`provider.addInteraction({
            state: 'I want to add a value unit tag',
            uponReceiving: 'Step - 1 : add a value unit tag',
            withRequest: {
              method: 'POST',
              path: "/api/v1/tags",
              headers: {
                "Content-Type": "application/json;charset=UTF-8"
              },
              body: "Tag_PACT_1519821131303"
            },
            willRespondWith: {
              status: 200,
              body: {
                  "result": 0
              }
            }
          })`

is there any place i missed? @blackbaud-joshlandi @bethesque

**Comment by bethesque** [comment]
The body won't work in that example with content type of json because a top level string is not valid JSON. You need a map or an array as the top level. The content type of text/plain should work however. If you still have problems with it, please raise a separate issue and fill in all the required information, ideally with a running code example that demonstrates the issue.

**Comment by xiaoningz** [comment]
@bethesque  thanks for reply,  i know the porblem why the text/plain not working, cause the header in addInteraction and request header is not matched, when i set the text/plain both in addInteraction and request header, it works.

**Comment by mefellows** [comment]
@xiaoningz we do have some [date matchers](https://github.com/pact-foundation/pact-js/#matching) available, maybe these would help?

**Comment by blackbaud-joshlandi** [comment]
No matchers or `toString()` on the date resolves the issue.  I understand Date isn't a native JSON type.  Setting body in the many ways below results in the same error:
```
body: new Date().toString(),
body: iso8601Date(new Date()),
body: like(new Date().toString())
```

Our provider doesn't support media type `text/plain` so we can't change the consumer to POST with a content-type header of `text/plain`.  It's weird because we're able to post just a `Date()` using angular's `Http` class, and using Fiddler I can see the body is only the Date string "2018-03-01T15:26:41.649Z".  

Do we have to change our POST data to be in the form of JSON like `{ date: new Date() }`?

**Comment by mefellows** [comment]
Interesting. All of these verifications pass through a Rack application, which I believe is quite strict with how it interprets HTTP messages. It's likely a problem in this processing that is causing the issues. i.e. my theory is that as you are not sending a (or the correct?) media type, the validation in low-level HTTP processing handler is causing this issue.

**Comment by bethesque** [comment]
The rack app does not know or care about the contents of a string. It does not know that the string contains a date. Please provide an executable code example using a fork of the example directory to demonstrate the error.
