### ISSUE TITLE
Single quote in consumer/provider names causes test failures

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#160]
## Software versions

* **OS**: Mac OSX 10.13.2
* **Consumer Pact library**: "@pact-foundation/pact": "^5.7.0" (also current head)
* **Provider Pact library**: NA
* **Node Version**: v8.4.0

## Expected behaviour

Consumer and provider names are allowed to contain single quote characters

## Actual behaviour

If the consumer or provider names contain single quote characters, the pact mock server doesn't spin up correctly, and connections are refused.

## Steps to reproduce

I've provided a branch that [illustrates the problem](https://github.com/TimothyJones/pact-js/blob/single-quote-issue/examples/jest/pactSetup.js#L11) in the Jest example:

```
  git clone git@github.com:TimothyJones/pact-js.git
  cd pact-js
  git checkout single-quote-issue
  npm i && npm run dist && cd examples/jest/ && npm i
  npm run test
```

Observe that the examples fail.

You can observe the example passing with:

```
git checkout master
npm run test
```

## Relevant log files

The following line in the log illustrates the problem - the consumer name is used directly on the command line, when it should be escaped:

```
[2018-03-15T02:21:06.884Z]  INFO: pact-node@6.11.0/63150 on Nightcrawler.dius.local: Created './platforms/darwin/bin/pact-mock-service service --consumer 'MyConsumer's Client' --pact_dir '/Users/work/office/test/pact-js/examples/jest/pacts' --host '127.0.0.1' --log '/Users/work/office/test/pact-js/examples/jest/logs/mockserver-integration.log' --pact-file-write-mode 'update' --port '8989' --provider 'MyProvider's Provider' --pact_specification_version '2'' process with PID: 63156
```

**Comment by TimothyJones** [comment]
I think this is a problem with `pact-node`. PR coming soon.

**Comment by mefellows** [comment]
Thanks Tim, we should be able to test out those spawn theories fairly quickly locally which is a good starting point.

Portability on Windows will be the tricky bit, but this might force is to have a Windows build up and running!

**Comment by TimothyJones** [comment]
I only just noticed that I forgot to open an issue against `pact-node`, so I did that.

I'm going to leave this open, since fixing it will probably mean bumping the version of `pact-node` that this repository depends on (once it is fixed in `pact-node`).

**Comment by mefellows** [comment]
Thanks Tim, yes good idea.

**Comment by TimothyJones** [comment]
This PR will fix this issue https://github.com/pact-foundation/pact-node/pull/196
