### ISSUE TITLE
Match the request with different request path on consumer and provider

### ISSUE THREAD

**Issue by tsharan** [pact-foundation/pact-js#167]
On consumer side the request path is something like `/servicename/user/create` but the provider takes only `/user/create` as we redirect the calls from consumer to specific docker container using nginx where the service is running. Is there any way to remove the `servicename` while generating pact files?

**Comment by mefellows** [comment]
This is not possible at the moment.

I would either a) paramaterise the base path in the consumer (e.g. the `protocol://hostname/servicename` bit) so then your consumer only has to know the path on a given service or b) run the nginx proxy docker container during my provider builds to keep it the same.

**Comment by joshhendo** [comment]
I'm facing the same problem. One way I'm exploring is you might be able to temporarily add new routes to your server for the purposes of the test, which point to the same controller. For example:

https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js#L18

Already shows adding in new routes for the setup script. You could add in something like that:
`server.post('/servicename/user/create', controller.userCreate)`

It's definitely not the best solution, and you need to be careful to ensure that you include any middleware you want tested.

**Comment by mefellows** [comment]
@tsharan how did you go?
