### ISSUE TITLE
PactJS with dependency on pact-node 6.13 fails on Windows.

### ISSUE THREAD

**Issue by dervism** [pact-foundation/pact-js#168]
## Software versions

* **OS**: Windows 10 (running on VMWare behind a firewall)
* **Consumer Pact library**: Pact JS v5.7.0, 5.8.0, 5.9.0, 6.x
* **Provider Pact library**: Using only PactJS
* **Node Version**: 8.9.3

## Expected behaviour

npm install should work without problem.

## Actual behaviour

Node cannot download "pact-ruby-standalone". Additionally:

npm install fails: node-gyp fails to find Python (even though Python is installed and set via env variables). (see attacted logs) (*UPDATE*: This happens when the incorrect version of Python is installed, reqiures v.2.7)

I have made sure that necessary http and https proxy settings are configured before running npm install.

*UPDATE:* Behind a corporate proxy, the following message er outputed:
[npm-install-log-updated.txt](https://github.com/pact-foundation/pact-js/files/1876143/npm-install-log-updated.txt)

`
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
`

## Steps to reproduce

Run npm install on the PactJS-repo on a Windows 10 system. I tried to reproduce this issue on AppVeyor without success.

Reverting pact-node to version 6.8.0 fixes my build. Changing it back to 6.13.0 causes the same failure.

## Relevant log files

[node-debug-log.txt](https://github.com/pact-foundation/pact-js/files/1874761/node-debug-log.txt)
[npm-install-log.txt](https://github.com/pact-foundation/pact-js/files/1874762/npm-install-log.txt)

I can see that Node is trying to connect to GitHub via HTTPS in order to download the zip-file. 

`
https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.33.1/pact-1.33.1-win32.zip
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 192.30.253.112:443
`

It fails on line 24 or 35 in https://github.com/pact-foundation/pact-node/blob/master/standalone/install.ts.

**Comment by mefellows** [comment]
Thanks @dervism. We've recently improved the way pact-node installs the CLI dependencies. It greatly reduces the size of our packages, and improves our time-to-market for fixes.

This line concerns me, but certainly appears to be (one of the main) cause:
```
Error: connect ECONNREFUSED 192.30.253.112:443
```

I've tested this just now (at home) and am able to connect to that ip/port, which is clearly GitHub's as you suggest. I'm wondering if you're behind a corporate proxy or something that might be preventing this from happening? 

As for the Python stuff, that seems to be an upstream dependency issue with `bunyan` (and `dtrace-provider`). It shouldn't be fatal, but weird that it needs/wants python.

**Comment by dervism** [comment]
@mefellows Yes that's correct. I am behind a government firewall. However, we have made sure that GitHub is allowed through our web proxies. I also confirmed that the proxies are set via `npm config list`.

I have tried running `npm install` on my on projects (that worked nicely before)n and the PactJS-repo itself and in both cases triggers dtrace-provider / node-gyp which then looks for Python. 

When the correct version of Python (v2.7) is found, it tries to download the zip-file. Because the systems over here is based on a self signed certificate, Python outputs `unable to verify the first certificate`. So I have to find a way to ignore certificate validation (which is not what I really want to do).

So - I cant understand why and how the dependency to Python and Node-Gyp is required. I do however see (as I described above) that stuff works when I downgrade pact-node to an earlier version.

**Comment by mefellows** [comment]
Thanks @dervism, there are two issues.

Looks like a recent update to Bunyan (logging lib) caused some pythobg issues  and the latest standalonen can't be downloaded.

For the latter, are you about to download this url from the same shell you are installing npm from?

 https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.35.0/pact-1.35.0-win32.zip

We use node to pull this down, so potentially the proxy is not being respected or this URL is not allowed

**Comment by mefellows** [comment]
Thanks @dervism, if you can't do the equivalent of a `curl` in that session (`Invoke-WebRequest` type thing) then there's not much we can do here. But if you can do that, then perhaps `http_proxy` type variables are being ignored on our end.

In any case, we'll await your research and i'll leave this open for now.

**Comment by dervism** [comment]
We have found that our proxy is not allowing direct downloads from GitHub afterall @mefellows 

We can close this issue. Thanks for being so supportive.

**Comment by mefellows** [comment]
Thanks for following up @dervism and no problem. All the best with the proxy :)
