### ISSUE TITLE
How to setup provider state

### ISSUE THREAD

**Issue by zkuang** [pact-foundation/pact-js#17]
The tutorial doesn't say anything about setting up provider state for pact verifying. So how do I do that? Or Do I have to use ruby and the original Pact to do the pact verifying with provider state?

**Comment by mefellows** [comment]
I'll see if we can make the docs a bit more clean.

In the meanwhile, you can use states. On the consumer side you indicate states with the `state` property, and then you need to configure the provider on the verification side later on. The provider must be augmented with two endpoints to list the states, and set the current state - see https://github.com/pact-foundation/pact-node/blob/master/test/integration/provider.js for an example provider setup and https://github.com/pact-foundation/pact-node#run-provider-verification for the verification properties.

**Comment by zkuang** [comment]
thanks, @mefellows , I'll check it out.

**Comment by mefellows** [comment]
I've added an [E2E tutorial](https://github.com/pact-foundation/pact-js/tree/master/examples/e2e) that demonstrates all of the features of Pact JS. Closing this for now.

**Comment by 210178** [comment]
@mefellows - I have a GET endpoint which accept 'id' as path param. my cucumber test is like,
Scenario:1 - (valid student id - meaning id is available in db)
GIVEN I have a student id "123"
WHEN I request student details with student id
THEN I should get a successful response with student details

Scenario:2 -
GIVEN I have a student id "200"  (invalid student id - meaning id isn't available in db)
WHEN I request student details with student id
THEN I should get an error response

FYI, I have gone through the E2E tutorial link which is given above. Still I am not clear about how we can validate those states in our provider. 

Please give me an example of setting the states for this scenario ....

**Comment by mefellows** [comment]
Hi @210178, please either open a separate ticket with a working code example we can modify (i.e. a GitHub repository that we can clone and run) or ask for further clarifications on our forums.
