### ISSUE TITLE
Undefined method gsub error

### ISSUE THREAD

**Issue by dervism** [pact-foundation/pact-js#170]
## Software versions

If a pre-existing pact file already exists in the pact folder, running the mocha test example fails with the following mesasage in the mockserver log:

`undefined method 'gsub' for nil:NilClass (NoMethodError)`

See attached logs.

* **OS**: Windows 10
* **Consumer Pact library**: Pact JS v5.9.0, 6.x.x
* **Provider Pact library**: Not relevant
* **Node Version**: 8.9.3

## Expected behaviour

The tests should run without problem.

## Actual behaviour

The tests are timing out, ref #169. In the mockserver log I see a very long stacktrace.

## Steps to reproduce

Run the mocha example via `npm test` on a fresh copy of pactjs repo on windows.

## Relevant log files

[mockserver-integration.log](https://github.com/pact-foundation/pact-js/files/1898048/mockserver-integration.log)

**Comment by bethesque** [comment]
When you say "a json file", is it a pre-existing pact file? Is there anything in it?

**Comment by bethesque** [comment]
This error is confusing me. I'm not convinced it's the source of your timeout, because it should just be printing the warning and continuing, as you can see from the line `WARN -- : Could not load existing consumer contract from C:/pact-js/examples/mocha/pacts/myconsumer-myprovider.json due to undefined method `gsub' for nil:NilClass. Creating a new file.`

The second reason this error is confusing me is that the error is happening on this line:

```
string.gsub('"producer":', '"provider":').gsub('"producer_state":', '"provider_state":')
```

Presumably, `string` is nil. However, I don't see how the string can be nil because that string is the contents of a file. Even if I create an empty file and read the contents, it returns an empty string, not a nil.

```
pact-support $ touch bethtemp.json
pact-support $ irb
irb(main):001:0> File.read('bethtemp.json')
=> ""
```

I'm wondering if this is a windows specific error. I'll see if I can think of a way to get you to debug it.

**Comment by dervism** [comment]
@bethesque 

Yes you are right, I meant a pre-existing pact-file. I have updated the text.

The readme you refer to contains the following text:

pact gem 1.20.1
pact-mock_service gem 2.6.4
pact-support gem 1.2.5
pact-provider-verifier gem 1.11.0
pact_broker-client gem 1.14.0

**Comment by dervism** [comment]
Yes I agree with you - the timeout error is there anyway (when I delete the pact file fex., ref #169)

**Comment by bethesque** [comment]
@dervism I have a windows specific test that makes sure that the existing file can be read here: https://github.com/pact-foundation/pact-ruby-standalone-windows-test/blob/master/spec/mock_service_with_merge_spec.rb

As you can see, it passes on appveyor https://ci.appveyor.com/project/pact-foundation/pact-ruby-standalone-windows-test

I would be interested in seeing if perhaps it does not work on your machine. You don't happen to have ruby installed do you?

**Comment by dervism** [comment]
I dont have Ruby installed otherwise. This problem occurs only when the pact file is not empty (when it contains the result of a previous successful generation) - deleting the file before I run npm test leaves me with issue #169. I suggest we put this issue on hold for now, it might behave differently when I get rid of the timeout issue.

**Comment by bethesque** [comment]
Here's something you can do to debug this when the other issue is fixed.

Open `C:/pact-js/examples/mocha/node_modules/@pact-foundation/pact/node_modules/@pact-foundation/pact-standalone/platforms/win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.6.4/lib/pact/consumer_contract/consumer_contract_writer.rb` line 65.

Modify it to:

```
        @existing_contents = pact_file.read.tap { |it| puts "The content of the file is #{it.inspect}" }
```

Run the test and see what you get.

**Comment by dervism** [comment]
Not able to figure out the Mocha timeout problem (issue #169). Closing this issue. Will reopen if needed.
