### ISSUE TITLE
Expecting an empty body Vs not caring about the body.

### ISSUE THREAD

**Issue by argos83** [pact-foundation/pact-js#177]
Hi! We've recently had an integration bug that should've been caught by contract testing but it wasn't.

## Software versions

* **OS**: e.g. Mac OSX 10.13.14
* **Consumer Pact library**: e.g. Pact JS v4.3.2
* **Provider Pact library**: -
* **Node Version**: v8.11.1

## Expected behavior

When the consumer is expecting the provider to return an empty body (i.e. content-length = 0)

```
myPactProvider.addInteraction({
       ...
       willRespondWith: {body: '', status: 200},
       ...
});
```
The generated pact file should contain the body property (set to empty string):

```
{
  "interactions": [
    {
       ...
       "response": {
         "body": "",
         "status": 200,
         "headers": {}
       }
    }
  ],
  ...
}
```

## Actual behaviour

The body property is removed altogether which means that it won't be validated:

```
{
  "interactions": [
    {
       ...
       "response": {
         "status": 200,
         "headers": {}
       }
    }
  ],
  ...
}
```

notice that other pact client libraries such as pact-jvm do care about this distinction (i.e. not defining a body vs setting it to empty).

I haven't checked the behavior for request bodies, but the bug might exist there as well.

I'm willing to raise a PR if you agree that this is a bug.

Thanks!

**Comment by mefellows** [comment]
Thanks @argos83, I think you're right. It's probably that we're doing some overly agressive _truthy_ claim on the body, instead of taking it for what was asked - a string.

I think it's an issue, but would like to hear from @bethesque and/or @uglyog. And yes, a PR would be welcome :)

**Comment by bethesque** [comment]
Would it work to expect a response with `Content-Length: 0`?
