### ISSUE TITLE
Jest example not working

### ISSUE THREAD

**Issue by jensraaby** [pact-foundation/pact-js#18]
I can't get the provided Jest example to run in isolation.

This is the output I get:
```
$ npm test

> jest@1.0.0 test ~/Projects/spikes/pact-js/examples/jest
> jest

 FAIL  __tests__/index.spec.js
  ● Test suite failed to run

    Couldn't find preset "es2015" relative to directory "~/Projects/spikes/pact-js"

      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
      at Array.map (native)

Test Summary
 › Ran all tests.
 › 1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 0.351s)
npm ERR! Test failed.  See above for more details.
```

This is on a Mac running Node 7.4.0.

It would be helpful if there was a read me of how to set it up properly.

**Comment by jensraaby** [comment]
I got this to work after I ran `npm install` in the root folder. It would be good if something documented this, or the package.json in the Jest example had all dependencies.

**Comment by mefellows** [comment]
I have updated the docs.
