### ISSUE TITLE
Please update to version 1.43.1 of the standalone

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#180]
This version ensures that underscored headers are preserved. Tagging @oliver-gramberg, @ghost. Any use of the --monkeypatch feature won't be needed to solve this problem any more. I've basically monkeypatched the code myself, but have finally found a way to preserve backwards compatibility. If you're curious, I added an extra header X-Pact-Underscored-Header-Names to the incoming request that contains a list of all the header names with underscores in them, so that when the request object is created from the incoming Rack Env (which turns all headers headers into HTTP_THIS_FORMAT) I can use that list to turn an_underscored_header back into an_underscored_header instead of A-Dasherized-Header. I'm not proud of it, but it works. Any only in Ruby could I get away with such a hack!

**Comment by mefellows** [comment]
Will do, this goes into Pact Node but shouldn't take long. Will try to do this today.

**Comment by mefellows** [comment]
`pact-node` version `6.16.4` will be going out shortly. Anyone installing Pact JS will get this by default now (courtesy of a micro upgrade).

**Comment by bethesque** [comment]
Hooray for semantic versioning.
