### ISSUE TITLE
Server is not being closed when a test run fails

### ISSUE THREAD

**Issue by chris-fa** [pact-foundation/pact-js#181]
## Software versions

* **OS**: e.g. Mac OSX 10.13.3
* **Consumer Pact library**: 5.9.1
* **Provider Pact library**: n/a
* **Node Version**: 8.11.1

## Expected behaviour

Server closes when calling `provider.finalize()`, even if there's an error in the test run.

## Actual behaviour

If there's an error, like an assertion fail, the server doesn't close. So the next run will error saying port unavailable and I have to kill the process using `kill <pid>`

## Steps to reproduce

1. The test is good so it passes.
2. Change `apiClient.test.js` line 37 to `apiClient.getCustomers(1234)` to cause a connection refuse error cause nothing is listening to that port
3. Execute the test suite
4. Change back to normal and execute the test suite.
5. It'd say the port returned by `getPort()` is unavailable, meaning the run where we got a connection refuse did not close the server on `afterEach`

https://gist.github.com/chris-fa/0662f8d4b2c1289e4a5fc49a2348131c

## Relevant log files

Nothing interesting here, it just say "Missing request" because of course, the request didn't happen.

**Comment by chris-fa** [comment]
Nevermind, the problem was that the `verify()` call was throwing an error so the `finalize()` wasn't being executed.

**Comment by mefellows** [comment]
Thanks @chris-fa. I think it would help to visualise this somehow, so others know the lifecycle of the mock service and Interactions. I've been thinking on how to do this, just need to get it done.

**Comment by puneetkumar712** [comment]
We are facing the same error. Can you please share how you resolved it?
