### ISSUE TITLE
Test interactions are not atomic

### ISSUE THREAD

**Issue by Barvor** [pact-foundation/pact-js#185]
## Software versions

* **OS**: Win10
 "@pact-foundation/karma-pact": "2.1.5",
    "@pact-foundation/pact-node": "6.11.0",
    "@pact-foundation/pact-web": "5.7.0",
* **Node Version**: v8.11.1

## Expected behaviour

Every test should run individually and be encapsuled

## Actual behaviour

I have a angular component with 2 UIs that interact with 2 different services.
UI 1 works with service 1 and UI2 with service 2.
Once I run my pact tests service interactions von UI1 are present in pact from test for UI2.

## Steps to reproduce

Setup 2 pact tests within a project and let them run, the resulting pact has interactions from both tests in the same consumer (although in the tests, there a two different consumers)

## Relevant log files

Everything works smoothely. No logs.

**Comment by mefellows** [comment]
Hi Barvor,

Are you saying that there are two different consumers, or just that the two different service components within your app have the same interactions? At a high level, I would expect in this case that the pact file _should_ contain the sum of interactions for both of those services.

If you're saying that the interactions are persisting _between_ individual test runs, then yes, we should see them being cleared between each test run. There are some nuances that control this behaviour, which can vary between test suites. 

The main one is controlling parallelism, and also when the mock service is started. There are some tips in our [troubleshooting](https://github.com/pact-foundation/pact-js/#troubleshooting?) guide, as well as in the examples.

**Comment by Barvor** [comment]
There are two different consumers. 
I expect the resulting pact-files to describe every consumer individually. 

If I run both test after another (both single run) the behaviour is as expected. (xdescribe one test case).
If I enable both tests in the same run (only one Pact Server is started, even though I remove Interactions and finalizy the provider afterAll in each testcase) then the interactions of test1 (with consumer 1) is written in the pactfile of test2 (consumer 2).

I thought that every .spec file should start its own pact server or at least wipe the server if told so)

**Comment by mefellows** [comment]
It should, yes. Can you please share your code so we can see what's happening?

**Comment by mefellows** [comment]
Oh, did you say you're sharing the same pact mock server? If so, this is not supported and you should create a separate mock server for each consumer/provider pair.

**Comment by bethesque** [comment]
@Barvor please read the mock service usage documentation here: https://github.com/pact-foundation/pact-mock_service/blob/master/README.md#mock-service-usage

**Comment by Barvor** [comment]
I am not sharing the same pact server. I am creating a new one for every pair of consumer and provider, but from the console log it does not seem to start2 different servers, even though I end every test case with finalizing.

I can send you the code, but the ticket is already closed. Where should I put it?

Thanks

Von: Matt Fellows <notifications@github.com>
Gesendet: Dienstag, 12. Juni 2018 23:02
An: pact-foundation/pact-js <pact-js@noreply.github.com>
Cc: Philip.Diem@smartinsurtech.de; Author <author@noreply.github.com>
Betreff: Re: [pact-foundation/pact-js] Test interactions are not atomic (#185)


Oh, did you say you're sharing the same pact mock server? If so, this is not supported and you should create a separate mock server for each consumer/provider pair.

**Comment by mefellows** [comment]
Ticket re-opened :)

**Comment by Barvor** [comment]
**Test 1**
`describe('ProductCreationService', () => {
  let provider;

  beforeAll(done => {
    provider = new PactWeb({
      consumer: 'product-creation-ui',
      provider: 'product-management',
      port: 8081,
      host: '127.0.0.1'
    });

    setTimeout(done, 2000);

    provider.removeInteractions();
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientModule],
      providers: [ProductCreationService]
    });
  });

  describe('getData()', () => {
    const expectedProduct: Product = {
      id: 'asdqwerk123-123asd',
      name: 'Best-Product',
      productProviderId: 'asdqwerk123-123asd',
      classOfInsuranceId: 'hhfddg594-091238-665'
    };

    beforeAll(done => {
      provider
        .addInteraction({
          state: 'list with product-providers and product-categories is available',
          uponReceiving: 'a request to POST a product',
          withRequest: {
            method: 'POST',
            path: '/productservice/products',
            headers: {
              'Content-Type': 'application/json',
              userId: 'CountChocula',
              realmName: 'BigBadDungeon',
              clientId: 'Igor-2'
            },
            body: expectedProduct
          },
          willRespondWith: {
            status: 201,
            headers: {
              'Content-Type': 'application/json'
            }
          }
        })
        .then(done, error => done.fail(error));
    });

    it('should create products', done => {
      const productCreationService: ProductCreationService = TestBed.get(ProductCreationService);
      productCreationService.createProduct(expectedProduct).then(
        response => {
          done();
        },
        error => {
          done.fail(error);
        }
      );
    });

    afterEach(done => {
      provider.verify().then(done, error => done.fail(error));
    });

    afterAll(() => provider.finalize());
  });
});`

**Test 2**
`describe('PPService', () => {
  let provider;

  beforeAll(done => {
    provider = new PactWeb({
      consumer: 'product-provider-ui',
      provider: 'product-management',
      port: 8081,
      host: '127.0.0.1'
    });

    setTimeout(done, 2000);

    provider.removeInteractions();
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientModule],
      providers: [PPService]
    });
  });

  describe('getData()', () => {
    const expectedProductProvider: ProductProvider = {
      id: 'asdqwerk123-123asd',
      ppId: 1234,
      category: 'grenzueberschreitender Dienstleister (FDI)',
      conciliationCommittee: 'Hamburg Zentral',
      name: 'Kaiser International',
      zipCode: '64557',
      city: 'Musterhausen',
      street: 'Koenigsweg 1',
      country: 'DE',
      type: 'FINANCIAL_SERVICE_PROVIDER'
    };

    const resultProductProviderArray: ProductProvider[] = [expectedProductProvider];

    beforeAll(done => {
      provider
        .addInteraction({
          state: `list with product-providers is available`,
          uponReceiving: 'a request to GET productproviders',
          withRequest: {
            method: 'GET',
            path: '/productservice/productproviders',
            headers: {
              'Content-Type': 'application/json',
              userId: 'CountChocula',
              realmName: 'BigBadDungeon',
              clientId: 'Igor-2'
            }
          },
          willRespondWith: {
            status: 200,
            body: Matchers.somethingLike(resultProductProviderArray),
            headers: {
              'Content-Type': 'application/json'
            }
          }
        })
        .then(done, error => done.fail(error));
    });

    it('should get a list of productproviders', done => {
      const pPService: PPService = TestBed.get(PPService);
      const params: HttpParams = new HttpParams();
      params.append('name', 'Kaiser International');
      pPService.getData(params).then(
        response => {
          expect(response).toEqual(resultProductProviderArray);
          done();
        },
        error => {
          done.fail(error);
        }
      );
    });

    afterEach(done => {
      provider.verify().then(done, error => done.fail(error));
    });

    afterAll(() => provider.finalize());
  });

  describe('postUnderwritingAgent', () => {
    const expectedUnderwritingAgent: UnderwritingAgent = {
      id: 'a1231345-era4512',
      commercialRegisterNumber: '8898979we',
      conciliationCommittee: 'Berlin Mitte',
      disctrictCourt: 'Berlin',
      name: 'Max Muster Versicherungen',
      zipCode: '99766',
      city: 'Berlin',
      street: 'Kaiserstrasse 10',
      country: 'DE',
      type: 'ISSUER'
    };

    beforeAll(done => {
      provider
        .addInteraction({
          uponReceiving: 'a request to POST an underwritingAgent',
          withRequest: {
            method: 'POST',
            path: '/productservice/productproviders/underwritingAgents',
            headers: {
              'Content-Type': 'application/json',
              userId: 'CountChocula',
              realmName: 'BigBadDungeon',
              clientId: 'Igor-2'
            },
            body: expectedUnderwritingAgent
          },
          willRespondWith: {
            status: 201,
            headers: {
              'Content-Type': 'application/json'
            }
          }
        })
        .then(done, error => done.fail(error));
    });

    it('should create an underwritingAgent', done => {
      const PPService: PPService = TestBed.get(PPService);
      PPService.postAgent(expectedUnderwritingAgent).then(
        response => {
          done();
        },
        error => {
          done.fail(error);
        }
      );
    });

    afterEach(done => {
      provider.verify().then(done, error => {
        done.fail(error);
      });
    });

    afterAll(() => provider.finalize());
  });
});`

If I run the tests one after the other (with xdescribe) the resulting pacts are fine. But if i run both of them at the same time (just ng test with all .spec files) the pact from the second test contains interactions from test 1)

**Comment by Barvor** [comment]
@mefellows  Thank you. Works now, had to get the proxies out and now it opens 2 differenct pactwebs and tests both tests individually.

Can be closed!

**Comment by mefellows** [comment]
Great to hear, thanks @Barvor
