### ISSUE TITLE
default port is used instead of specific 

### ISSUE THREAD

**Issue by cakeinpanic** [pact-foundation/pact-js#186]
Here is one log of my tests running. Look at port ` port = 6789,` specified for pact and then trying to reach `localhost:1234`

```
[2018-06-12T19:33:27.375Z]  INFO: pact-node@6.18.3/1535 on Katerinas-MacBook-Pro.local: 
    Creating Pact Server with options: 
    cors = true,
    port = 6789,
    dir = /Users/cakeinpanic/projects/sme-messenger/pacts,
    spec = 2,
    logLevel = DEBUG,
    log = /Users/cakeinpanic/projects/sme-messenger/mimilog/pact.log,
    pactFileWriteMode = overwrite,
    ssl = false,
    host = localhost

[2018-06-12T19:33:27.381Z]  INFO: pact-node@6.18.3/1535 on Katerinas-MacBook-Pro.local: 
Created './standalone/darwin-1.44.3/bin/pact-mock-service service --cors 'true' 
--port '6789' --pact_dir '/Users/cakeinpanic/projects/sme-messenger/pacts' --pact_specification_version '2' 
--log '/Users/cakeinpanic/projects/sme-messenger/mimilog/pact.log' 
--pact-file-write-mode 'overwrite' --host 'localhost'' process with PID: 1537

....


ERROR: 'Unhandled Promise rejection:', 
'Unable to connect to *"http://127.0.0.1:1234/interactions"*', '; Zone:', '<root>', ';
 Task:', 'Promise.then', '; Value:', PopsicleError{cause: undefined, code: 'EUNAVAILABLE', popsicle: Request
{Url: Url{protocol: ..., slashes: ..., auth: ..., host: ..., port: ..., hostname: ..., 
hash: ..., search: ..., query: ..., pathname: ..., path: ..., href: ...}, 
rawHeaders: [..., ..., ..., ..., ..., ...],
middleware: [..., ...], opened: true, aborted: false, uploaded: 1, 
downloaded: NaN, timeout: 10000, method: 'DELETE',
```

```
node v8.9.4
mac os x el capitan
"@pact-foundation/karma-pact": "2.1.5",
"@pact-foundation/pact-node": "6.18.3",
"@pact-foundation/pact-web": "5.9.1",
```

**Comment by mefellows** [comment]
Can you please share a reproducible working project? You'll need to configure the port in both the Karma config and the test itself

**Comment by cakeinpanic** [comment]
@mefellows hello! sorry, but I can't because it's my huge working projects and I really can't reproduce all configs in some sample

I've never seen this bug again despite the fact I don't specify port in tests.

Maybe you should check source code of pact to figure out what circumstances can lead to this?

**Comment by mefellows** [comment]
@cakeinpanic well, it's going to be very hard to help you without you coming to the party with more information 😄 

> Maybe you should check source code of pact to figure out what circumstances can lead to this?

☝️ Well, yes I know what circumstances that could lead to this, and my suggestion was _"... to configure the port in both the Karma config and the test itself"_

I just modified our mocha test example in the project, and it works just fine.

in `karma.conf.js` you'll need to set the port you want:

![screenshot](https://user-images.githubusercontent.com/53900/41322602-3b654f56-6eed-11e8-90ca-489c7dfcc606.png)

In your test, you'll need to a) tell Pact what port to connect to and b) tell your code that the mock service is another port:

![screenshot](https://user-images.githubusercontent.com/53900/41322627-54b579d6-6eed-11e8-947b-a6fce3567863.png)

Closing this unless you can create me a reproducible issue.

**Comment by cakeinpanic** [comment]
As I have mentioned before, I don't face this problem anymore, so assume it as a bug report)

I guess there is a problem with sharing info about pact between projects. I have downloaded sample project using pact, ran tests once and closed it. 
And then I found pacts from it in my another project pact folder(weird)

Maybe problem with default port lies somewhere near.

**Comment by mefellows** [comment]
Thanks @cakeinpanic, if i comes up again we can re-open this issue.
