### ISSUE TITLE
State change body/params cannot be passed. JVM version has this capability.

### ISSUE THREAD

**Issue by margish** [pact-foundation/pact-js#191]
Interaction class does not seem to accept params for state change. Am I missing something here?
export class Interaction {
  constructor();
  given(providerState: string): Interaction;
  uponReceiving(description: string): Interaction;
  withRequest(requestOpts: RequestOptions): Interaction;
  willRespondWith(responseOpts: ResponseOptions): Interaction;
  json(): object;
}

**Comment by mefellows** [comment]
That's a [v3 spec](https://github.com/pact-foundation/pact-specification/tree/version-3) feature, which is currently not supported I'm afraid. We are working on v3 compatibility, but it's not yet complete.

**Comment by margish** [comment]
Thanks for the clarification.
