### ISSUE TITLE
Unexpected Token 'const'

### ISSUE THREAD

**Issue by AdrianKrebs** [pact-foundation/pact-js#192]
## Software versions

* **OS**: Windows 10
* **Consumer Pact library**: Pact ^6.0.0-alpha.14
* **Node Version**: 10.5.0

I'm getting the following error when running my pact tests with karma:

```
4 06 2018 21:34:55.691:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket 09oR78X_rbcEhoHvAAAA with id 63719910
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/@pact-foundation/pact-node/~/tar/lib/header.js:7:0 <- index.js:36240
```
Any idea what this is?

Besides there are a few errors before this one:

`WARNING in ./~/pact/src/common/config.js
21:19-44 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@pact-foundation/pact-node/standalone/install.js
81:21-41 Critical dependency: the request of a dependency is an expression

ERROR in ./~/pact/src/common/net.js
Module not found: Error: Can't resolve 'net' in 'C:\Projects\app\node_modules\pact\src\common'
 @ ./~/pact/src/common/net.js 8:12-26
 @ ./~/pact/src/pact.js
 @ ./test/unit/specs/consumerPact.spec.js
 @ ./test/unit/specs \.spec$
 @ ./test/unit/index.js
`

**Comment by mefellows** [comment]
Because you're running in Karma, you're not actually running from within a true node environment. You will want to use `pact-web` as described here: https://github.com/pact-foundation/pact-js/#using-pact-in-non-node-environments

(TL;DR - Pact can't start servers and things from a browser environment).

**Comment by AdrianKrebs** [comment]
I added the   '../../node_modules/@pact-foundation/pact-web/pact-web.js', line as described in the readme. But I still get the same errors... what am I missing?

karma.conf:

`var webpackConfig = require('../../build/webpack.test.conf')

module.exports = function (config) {
  config.set({
    // to run in additional browsers:
    // 1. install corresponding karma launcher
    //    http://karma-runner.github.io/0.13/config/browsers.html
    // 2. add it to the `browsers` array below.
    browsers: ['PhantomJS'],
    frameworks: ['mocha', 'sinon-chai', 'phantomjs-shim', 'pact'],
    pact: [{
      port: 1234,
      consumer: "some-consumer",
      provider: "some-provider",
      dir: "pact/files/go/here",
      log: "log/files/go/here"
    }],
    // ensure Pact and default karma plugins are loaded
    plugins: [
      'karma-*',
      '@pact-foundation/karma-pact',
    ],
    reporters: ['spec', 'coverage'],
    // Babel only transpiles, for unit tests to work with PhantomJS
    // we also need to include a polyfill.
    // GH: https://github.com/vuejs-templates/webpack/issues/260
    files: [
      '../../node_modules/babel-polyfill/dist/polyfill.js',
      '../../node_modules/@pact-foundation/pact-web/pact-web.js',
      './index.js'
    ],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    }
  })
}
`

**Comment by AdrianKrebs** [comment]
I did some further investigation:
- the problem seems webpack related (the app uses vue.js)
- when I run the tests without webpack, I don't get the error
- However, my client sources are not transpiled then (babel) and I get the error "SyntaxError: Use of reserved word 'import') 

I was looking for a sample with vue.js or another SPA framework but couldn't find one so far...
Any tips?

**Comment by AdrianKrebs** [comment]
@mefellows thanks for your response. 
Not really... I tried to add a pact test to my vue.js SPA but couldn't make it work. Seems to be a conig issue with webpack/babel/mocha... do you know of any pact sample within a vue.js app? Would love to see such an example

**Comment by mefellows** [comment]
I'll reach out to see if we can find someone who has. Perhaps join us on slack.pact.io also.

That being said, Vue.js shouldn't be any different. If you write your code in such a way that your API services aren't tightly coupled to your UI framework (Vue) then you could just write standard, nodejs style tests.

It's a bit tricker using pact web and I encourage people to avoid it. I can't think of many situations where you absolutely must run these tests in a browser environment. Creating a separate pact testing suite (using mocha/Ava/jest etc) is probably worth the small effort to sidestep these issues.

We have a number of examples in the repo that you can then use as a starting point.
