### ISSUE TITLE
Feature request: clear logs on tests restart

### ISSUE THREAD

**Issue by cakeinpanic** [pact-foundation/pact-js#194]
## Software versions

* **OS**: e.g. Mac OSX 10.12.5
* **Provider Pact library**: 
```
"@pact-foundation/karma-pact": "2.1.5",
"@pact-foundation/pact-node": "6.18.3",
"@pact-foundation/pact-web": "5.9.1",
```
* **Node Version**: 8.9.4

## Request
Add configuration flag for clearing `.log` files each time tests restart to ease debugging.

**Comment by mefellows** [comment]
I have thought about this, I'm not sure it's an option we want to support but happy for others to chime in.

I typically run a `pretest` type script that runs `rimraf` on the output dir (e.g. `logs`, `pacts` etc.)
