### ISSUE TITLE
example karma-pact not working with new versions of pact modules 

### ISSUE THREAD

**Issue by kaparna91** [pact-foundation/pact-js#196]
## Software versions

* **windows 7**: 
* **Node Version**: node  v8.9.4

## Expected behaviour
I am working on a exemplar project that uses karma ,grunt . When I try updating it with new versions of pact the test cases are failing . It used to work with old pact modules and I have changed the client-spec.js file to support new pact modules.
**old pact moduels :**
"pact": "4.3.2",
    "@pact-foundation/pact-node": "6.7.4",
    "@pact-foundation/karma-pact": "2.1.3",
new pact modules:
"@pact-foundation/karma-pact": "^2.1.5",
    "@pact-foundation/pact": "^5.9.1",
    "@pact-foundation/pact-node": "^6.13.0",

## Steps to reproduce

I am using below project as my reference
https://github.com/pact-foundation/pact-js/tree/master/karma/jasmine

**Comment by mefellows** [comment]
So what's not working exactly? The example code you provided is tested with every build so we know that works.

Please provide a reproducible project for us.

**Comment by kaparna91** [comment]
Test cases are failing after updating project with new pact modules.

**Comment by mefellows** [comment]
That's not very helpful for us. Please read https://coderanch.com/wiki/659862/Show-Effort so you can help us help you.

**Comment by mefellows** [comment]
FYI we run the jasmine and mocha karma examples as part of every commit - the tests are currently green (e.g. https://travis-ci.org/pact-foundation/pact-js/jobs/392460714#L3909-L3964)

I'm going to close this issue until evidence of an issue is demonstrated. Will happily investigate then.

**Comment by mefellows** [comment]
Thanks @kaparna91, can you please provide instructions for running the examples? I've tried running `karma start test/karma.config.js` but it fails with a bunch of errors (doesn't match files, for example).

Also, if you could please provide logs/evidence of the problem that would certainly assist.

**Comment by kaparna91** [comment]
Once the grunt tasks are loaded if we run test- pact it should able to run the test cases. But  In my project pact exits with code 1 ,this behavior is seen after I updated the project with new pact node modules. Below are the attached error logs 
                                                                                                                                                             (node:368540) ExperimentalWarning: The http2 module is an experimental API.
13 08 2018 12:09:02.891:ERROR [plugin]: Error during loading "C:\devl\demo-dojo.webapp\node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
13 08 2018 12:09:05.933:INFO [framework.browserify]: registering rebuild (autoWatch=true)
[2018-08-13T16:09:05.950Z]  INFO: pact-node@6.13.0/368540 on MYWINDOWS: 
    Creating Pact Server with options: 
    port = 1234,
    consumer = KarmaJasmineConsumer,
    provider = KarmaJasmineProvider,
    logLevel = DEBUG,
    log = C:\devl\demo-dojo.webapp\logs\pact.log,
    dir = C:\devl\demo-dojo.webapp\pacts,
    pactFileWriteMode = overwrite,
    ssl = false,
    cors = false,
    host = localhost
[2018-08-13T16:09:05.980Z]  INFO: pact-node@6.13.0/368540 on MYWINDOWS:Created 'standalone\win32-1.33.1\bin\pact-mock-service.bat service --port '1234' --consumer 'KarmaJasmineConsumer' --provider 'KarmaJasmineProvider' --log 'C:\devl\demo-dojo.webapp\logs\pact.log' --pact_dir 'C:\devl\demo-dojo.webapp\pacts' --pact-file-write-mode 'overwrite' --host 'localhost'' process with PID: 365796
(node:368540) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2018-08-13T16:09:06.262Z]  WARN: pact-node@6.13.0/368540 on MYWINDOWS: Pact exited with code 1.

**Comment by mefellows** [comment]
I'm not getting that error, this is what I get:

```

**Comment by mefellows** [comment]
Looking at your logs, this appears to be the issue:

```
13 08 2018 12:09:02.891:ERROR [plugin]: Error during loading "C:\devl\demo-dojo.webapp\node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
```

I also don't have grunt installed on my machine, and don't know which versions you have either.

Please provide more detail so that I can help you.

**Comment by kaparna91** [comment]
This is the version of "grunt": "^0.4.5". I observed that you are using pact-node@6.19.0 and I am using  pact-node@6.13.0 could that be an issue.

**Comment by mefellows** [comment]
We recently released a version of karma-pact that fixes an issue with the latest deasync package, maybe give that a go first.

Also, until I can download your package and actually run it with clear step-by-step instructions, I can't help you. The package you've provided simply doesn't run.

**Comment by kaparna91** [comment]
The step by step instructions to run the project  
1. Do "npm install " after you clone the project.
2. After all the node modules loaded , check for grunt tasks.
3. After grunt tasks loads run  "test pact "  task .

**For  previous versions of pact the logs used to look like this** 

[2018-08-22T15:23:12.470Z]  INFO: pact-node@6.7.4/92724 on MYWINDOWS: 
    Creating Pact Server with options: 
    port = 1234,
    consumer = KarmaJasmineConsumer,
    provider = KarmaJasmineProvider,
    logLevel = DEBUG,
    log = C:devl\UI\cucumber-js-dojo.webapp\logs\pact.log,
    dir = C:devl\UI\cucumber-js-dojo.webapp\pacts,
    pactFileWriteMode = overwrite,
    ssl = false,
    cors = false,
    host = localhost
[2018-08-22T15:23:12.544Z]  INFO: pact-node@6.7.4/92724 on MYWINDOWS: Created 'platforms\win32\bin\pact-mock-service.bat service --port '1234' --consumer 'KarmaJasmineConsumer' --provider 'KarmaJasmineProvider' --log 'C:\Desktop\UI\cucumber-js-dojo.webapp\logs\pact.log' --pact_dir 'C:\Desktop\UI\dojo.webapp\pacts' --pact-file-write-mode 'overwrite' --host 'localhost'' process with PID: 94096
22 08 2018 11:23:19.748:INFO [pact]: **Pact Mock Server running on port: 1234**

**After updating my project with new pact modules pact exits with code 1**

**Comment by mefellows** [comment]
OK, for starters that doesn't work - I don't have grunt installed locally, so you need to either a) add it to your `package.json` or specify it. Which version of node? which directory to run it from (it fails for me).

I should literally be able to checkout the project locally, and blindly run your instructions.
