### ISSUE TITLE
Pact server hangs on docker machine

### ISSUE THREAD

**Issue by jchapelle** [pact-foundation/pact-js#199]
On my local machine, I'm running pact tests which work properly. Below, you'll find a trace of a test that succeed. You can see that the server is removed after test

> [2018-07-18T12:13:44.345Z] DEBUG: pact-node@6.18.3/6564 on P00WS903:
> [2018-07-18 14:13:44] INFO  WEBrick 1.3.1
> [2018-07-18T12:13:44.346Z] DEBUG: pact-node@6.18.3/6564 on P00WS903:
> [2018-07-18 14:13:44] INFO  ruby 2.2.2 (2015-04-13) [i386-mingw32]
> [2018-07-18T12:13:44.347Z] DEBUG: pact-node@6.18.3/6564 on P00WS903:
> [2018-07-18 14:13:44] INFO  WEBrick::HTTPServer#start: pid=10692 port=8080
> [2018-07-18T12:13:47.496Z]  INFO: pact-node@6.18.3/6564 on P00WS903: Removing Pact with PID: 9596
> [2018-07-18T12:13:49.009Z]  INFO: pact-node@6.18.3/6564 on P00WS903:

On my CI, a linux docker machine is running the exact same test. There, the test succeed as well but the pact server is never deleted. The pact test report is never written neither. This cause my CI to hang and never stops ... Any idea how to solve ?

> [2018-07-18T12:41:23.055Z] DEBUG: pact-node@6.18.3/21025 on aa58004a3575: 
> [2018-07-18 14:41:23] INFO  WEBrick 1.3.1
> [2018-07-18 14:41:23] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
> [2018-07-18 14:41:23] INFO  WEBrick::HTTPServer#start: pid=21038 port=8080

**Comment by mefellows** [comment]
Thanks for the report, however please fill out the issue template before we respond. We need more information to help you.

**Comment by jchapelle** [comment]
## Software versions

* **OS**: Docker machine. Custom image started from java:8
* **@pact-foundation/pact": "^5.9.1",
* **@pact-foundation/pact-node": "^6.18.3",
* **Node Version**: 8.11.1

## Expected behaviour

I expect pact server to be deleted and pact report file to be written in destination directory

## Actual behaviour

Pact server on docker machine is never deleted and report file is never written, even if the test succeed

## Steps to reproduce

Hard to give a snippet or such ... I think it is related to docker

## Relevant log files

See above

**Comment by bethesque** [comment]
Can you provide a minimal docker file to allow us to recreate this issue locally please?

**Comment by jchapelle** [comment]
Please find a archive in annex.
The archive contains a README.txt file explaining how to reproduce.

I have to say that the error encountered here is not exactly the same as in my CI.
Anyway, we can first try to debug this test first.
It seems here that the interaction is never received.
If I run the test outside docker, it works
If I run the test inside docker, it fails.

Link to archive
[https://we.tl/jKZhEQSYMA]

**Comment by mefellows** [comment]
Thanks @jchapelle, I've been able to pull down your repository.

When I remove the proxy configurations from the Dockerfile, your tests pass for me. This makes perfect sense - your consumer tests are going to be making a call to the mock service _via the proxy_. Does your proxy allow this?

In any case, your problem definitely lies in that network connectivity space.

One option, is to _disable the proxy_ for the `npm t` phase - there is no reason to have the proxy enabled for local tests. It's probably needed to get out to the npm registry etc.

You can bypass the proxy settings by setting environment variables first, or running your tests like so:
```sh
http_proxy='' npm t
```

**Comment by mefellows** [comment]
Closing stale issue. Please re-open if you can re-produce the problem outside of your specific environment, or can conclusively show that pact is the issue.
