### ISSUE TITLE
Analog of "generate" field for eachLike matcher

### ISSUE THREAD

**Issue by cakeinpanic** [pact-foundation/pact-js#200]
## Software versions

* **OS**: e.g. Mac OSX 10.12.5
* **Provider Pact library**: 
```
"@pact-foundation/karma-pact": "2.1.5",
"@pact-foundation/pact-node": "6.18.3",
"@pact-foundation/pact-web": "5.9.1",
```
* **Node Version**: 8.9.4

## Expected behaviour
I want to provide mock response with an array of strings. I want to specify for counsumer that it is array of strings with min length of 1. But I also want to provide mock response with array with three elements. How can I do this? Something like
```
 willRespondWith: {
            status: 200,
            body: Matchers.like(["marc", "john", "ann"], {min:1})
}
```
## Actual behaviour

I couldn't fine any possibility to do that

**Comment by bethesque** [comment]
This currently isn't supported by the underlying library, but it wouldn't be hard to do, and I have in fact gotten half way through doing it at one stage, then backed it out for some reason. You'll need to raise it in the pact-foundation/pact-support repository.

**Comment by camory** [comment]
Hello 
I am interesting by this feature.
I want to use Pact in BDD scenario. 
So imagine we have a client A which should display a list of users ordered by age. The list of user is provided by a service B. So basically, A calls B and sort the list of users. Of course, the business logic could be more complicated. Here is the related BDD scenario

```
Given a the folloging users:
   |name  |age|
   |Linda | 30|
   |Jeff  | 15|
   |John  | 29|

When I go the users page

Then I would have the list of users in the following order
   |name  |age|
   |Jeff  | 15|
   |John  | 29|
   |Linda | 30|
```
The `Given` step registers the interaction. So the response body should contain an array of the 3 users objects and in the meantime the response should match an array of a least one user object which is of type `{name: 'Linda', age: 30}`. 
On the client side, the 3 users are used in the BDD to pass the test. 
On the provider side, I only need to check that the response contains an array of object which has a property called 'name' of type String and a property called age of type Integer.
So something like:
```
willRespondWith: {
 status: 200,
 body: Matchers.like(
   [
    Matchers.like({ name: "Linda", age: 30}), 
    Matchers.like({ name: "Jeff", age: 15}), 
    Matchers.like({ name: "John", age: 29})
   ], 
    {min:1}
 )
}
```
So finally, it is like to separate the body response and the matcher rules

**Comment by bethesque** [comment]
> which should display a list of users ordered by age

Testing that the arrays are sorted by age would be functional testing that belongs in the provider's codebase. All you should care about is that the types match - have a read of https://docs.pact.io/best_practices/consumer/contract_tests_not_functional_tests

**Comment by camory** [comment]
Maybe, sorting by age is not the best example. 
The idea is to make some tests on business logic which only belongs to the client with the narrow integration testing strategy described by Martin Fowler (https://martinfowler.com/bliki/IntegrationTest.html).
 In this case, I have to mock the provider and then verify that the reponse of the mock is the same as the real provider. I think Pact is the perfect tool for that and it covers 90% of my needs. 
The issue I have is when the provider return a list of items. In one hand, I would like to define different items in this list to fullfill the business test case and in the other hand, I would like to verify the type of the attributes of the item. 
In the example, I would like to verify that response return a list of item and each item has a "name" attribute of type String and an "age" attribute of type integer

**Comment by mefellows** [comment]
I can see the value in having it, because then you can re-use the pact files for UI stubs in other parts of the test lifecycle.

I can see why the values don't matter from a functional perspective, but it is nice when working on UI's to have varied sets of data.

What I typically do in more complicated environments, is run something like Mountebank, or even just a simple express app with data stubs to fulfil this need. But in simpler environments, using pact stubs would be nice.

Is there a good reason _not_ to implement it Beth, aside from time / effort :)

**Comment by mefellows** [comment]
See also #402. Closing this and marking the other for potential v4 enhancement.
