### ISSUE TITLE
Provider not passing body from generated json file.

### ISSUE THREAD

**Issue by shivanshuit914** [pact-foundation/pact-js#201]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact JS v5.9.1
* **Node Version**: `8.9.4`

## Expected behaviour

Make request with json body to provider to verify contract.

## Actual behaviour

Not Making request with Json body so provider contracts are failing.

## Steps to reproduce

When I am running provder test with options its not passing the request with the body.

Request Log:
```
info: Request:  {"url":"/batch","body":"{\"consumer\":\"Fe portal\",\"state\":\"Component not present\",\"states\":[\"Component not present\"]}","timestamp":"2018-07-20T08:00:30.545Z"}
# here its not passing body with fake component.
info: Request:  {"url":"/batch","body":"{}","timestamp":"2018-07-20T08:00:30.550Z"}
```

Provider Code:

```
    test('has a health endpoint', (done) => {
      return new Verifier().verifyProvider(opts)
      .then((output) => {
        console.log('Pact Verification Complete!');
        console.log(output);
        done();
      });
```

## Relevant log files
```
{
  "consumer": {
    "name": "Consumer"
  },
  "provider": {
    "name": "Component Provider"
  },
  "interactions": [
    {
      "description": "Request to get component",
      "provider_state": "Component not present",
      "request": {
        "method": "POST",
        "path": "/batch",
        "headers": {
          "Accept": "application/json"
        },
        "body": {
          "FakeComponent": {
            "name":"FakeComponent",
            "data": {}
          }
        }
      },
      "response": {
        "success": true,
        "error": null,
        "body": {"success":true,"error":null,"results":{"status_code" : 404}}
      }
    }
  ]
}
```

**Comment by mefellows** [comment]
Thanks @shivanshuit914. I can't tell from this where in the process it could be  Please provide a working example (e.g. on github) that we can run to reproduce the issue.

If you fork this repository, there is an e2e example that you can use to create the conditions in which you are seeing the failure.

**Comment by shivanshuit914** [comment]
Thank you @mefellows  Let me try with e2e example and if it doesn't work I will push it to github .

**Comment by mefellows** [comment]
No worries!

**Comment by bethesque** [comment]
Those logs look like they're for the provider state set up call, not the actual request that is being verified.

**Comment by mefellows** [comment]
Indeed.

**Comment by mefellows** [comment]
Thanks for taking the time to create an example @shivanshuit914 .

As per the PR comments, I took a look at your PR, and I'm still confused.

This [line](https://github.com/pact-foundation/pact-js/pull/202/files#diff-2d58c5e8dc0c9becc658373b7b76e7b2R219) adds a new expected API _response body_ on the _provider_ for a `POST on /animals`. Currently, that API endpoint just returns a `200` if successful, or a `400` if a bad request given - not an `animal` object.

Replacing the end of the `/animals` endpoint function with this fixes that test:

```js
73: res.end(JSON.stringify(animal))
```

The verifier is most certainly sending the JSON body to the `/animals` endpoint and is being correctly parsed. Closing as this demonstrates the reported issue is invalid.

**Comment by shivanshuit914** [comment]
Hi @mefellows  thank you!

I have added some comments in PR, I am still facing error. I think I am missing something.

Thanks

**Comment by mefellows** [comment]
Below is a patch file that you can apply to get your tests running.

I can guarantee you that the verifier will send a valid POST body to your API should you require it - i'll get it added to our E2E suite so that it's there!

[issue-201.patch.zip](https://github.com/pact-foundation/pact-js/files/2218985/issue-201.patch.zip)

**Comment by shivanshuit914** [comment]
Thank you @mefellows  Works fine  👍

**Comment by mefellows** [comment]
Great!
