### ISSUE TITLE
GraphQLInteraction doesn't support named queries

### ISSUE THREAD

**Issue by sh3pik** [pact-foundation/pact-js#235]
Apollo allows [naming operations](https://www.apollographql.com/docs/apollo-server/v2/essentials/data.html#operation) for a query or a mutation. It can be specified right after a keyword, e.g. `query`, and goes to `operationName` in [the body of the request](https://www.apollographql.com/docs/apollo-server/requests.html) 

> A valid request must contain either a `query` or an `operationName` (or both, in case of a named query)

```gql
query HomeBookListing {
  getBooks {
    title
  }
}
```
```
{
  "body": {
    "query": "query HomeBookListing { getBooks { title } }",
    "operationName": "HomeBookListing"
  }
}
```

## Expected behaviour

I expect `.withOperation()` to work with named operations.

## Actual behaviour

`.withOperation()` allows only `query` or `mutation`:

```
You must provide a valid HTTP method: query, mutation.
```

**Comment by mefellows** [comment]
Thanks @sh3pik, it makes sense to support this.

Can you please show me exactly what you'd like the DSL to look like and also what you've tried?

**Comment by sh3pik** [comment]
I expect to be able to do something like:
```js
new GraphQLInteraction()
.withOperation('HomeBookListing')
.withQuery('query HomeBookListing { getBooks { title } }')
```
If I run it on the current version, I'll get the error `You must provide a valid HTTP method: query, mutation.`
I tried without `.withOperation('HomeBookListing')`, I saw the error `No matching interaction found` in logs:
```diff
Diff
--------------------------------------
Key: - is expected 
     + is actual 
Matching keys and values are not shown

 {
   "body": {
-    "operationName": null
+    "operationName": "HomeBookListing"
   }
 }

Description of differences
--------------------------------------
* Expected nil but got "HomeBookListing" at $.body.operationName
```

**Comment by mefellows** [comment]
Thanks @sh3pik, having another look at the docs I think we are just being a little bit too strict on what the `withOperation` takes - it's really up to the user. I'll remove the restriction and error message for that field.

**Comment by mefellows** [comment]
I've pushed out a new release with a fix (16df628), let us know how you go!

**Comment by sh3pik** [comment]
The fix works perfectly! Thanks a lot for a quick response!

**Comment by mefellows** [comment]
You're welcome, thanks for the report!
