### ISSUE TITLE
Publishing to Pact Broker

### ISSUE THREAD

**Issue by fosho** [pact-foundation/pact-js#240]
I'm successfully generating a report but when I publish the report to the broker, it's saying 0 passing. 

DEBUG doesn't give any helpful information.

Is my understanding correct that I should first generate a report, publish it to pact broker, then verify?

## Software versions

* **OS**: e.g. Windows 7
* **Consumer Pact library**: @pact-foundation/pact": "5.9.1"
* **Node Version**:  8.12.0

## Expected behaviour

Pact contract publishing complete!

## Actual behaviour

0 passing

## Steps to reproduce

test.js

`const path = require('path')
const { Pact } = require('@pact-foundation/pact')
const axios = require('axios');
const expect = require('chai').expect;

describe("BrowseUI Consumer", () => {
  const url = 'http://localhost';
  const svcEndpoint = '/test';
  const port = 8990

  // (1) Create the Pact object to represent your provider
  const provider = new Pact({
    consumer: "testConsumer",
    provider: "testProvider",
    port: port,
    log: path.resolve(process.cwd(), "logs", "pact.log"),
    dir: path.resolve(process.cwd(), "pacts"),
    logLevel: "INFO",
    spec: 2,
    consumerVersion: '1.0.0'
  })

  // Starts the Mock Server
  before(() => provider.setup())

  // Records the interactions registered to the Mock Server
  // into the pact file and shuts it down.
  after(() => provider.finalize())

  // this is the response you expect from your Provider
  describe("and a call to headerui is made", () => {

    // (2) Add expected response call
    const EXPECTED_BODY = {
      "test": "true"
    }

    before(done => {
      const interaction = {
        // (3) add interactions to the Mock Server, as many as required
        // The 'state' field specifies a "Provider State"
        state: "I have a test",
        uponReceiving: "a request for test",
        withRequest: {
          method: "GET",
          path: svcEndpoint,
          headers: { Accept: "application/json" }
        },
        willRespondWith: {
          status: 200,
          headers: { "Content-Type": "application/json; charset=UTF-8" },
          body: EXPECTED_BODY
        }
      }
      provider.addInteraction(interaction).then(() => {
        done()
      })
    })

    // (4) write your test(s)
    it('it returns the correct response', done => {
      const urlAndPort = {
        url: url,
        port: port,
        context: svcEndpoint
      }
      pactBrokerSVC(urlAndPort)
        .then(response => {
          console.log('response.data --- ' + response.data)
          expect(response.data).to.eql(EXPECTED_BODY)
          done()
        }, done)
    })
  })
})

function pactBrokerSVC(endpoint) {
  const url = endpoint.url
  const port = endpoint.port
  const context = endpoint.context
  console.log('>>>' + url + ":" + port + context);

  return axios.request({
    method: 'GET',
    baseURL: `${url}:${port}`,
    url: `${context}`,
    headers: { 'Accept': 'application/json' },
  })
}
`
publish.js

`const pact = require('@pact-foundation/pact-node')
const path = require('path')
const opts = {
  pactFilesOrDirs: [path.resolve(__dirname, '../../../pacts/testConsumer-testProvider.json')],
  pactBroker: 'http://mypactbrokerurl',
  consumerVersion: '1.0.0',
}

pact.publishPacts(opts)
  .then(() => {
    console.log('Pact contract publishing complete!')
  })
  .catch(e => {
    console.log('Pact contract publishing failed: ', e)
  })
`

## Relevant log files

![debug](https://user-images.githubusercontent.com/37598525/47620430-00611480-dab8-11e8-8e3e-c778580b5d03.PNG)

**Comment by mefellows** [comment]
0 passing tells me you're trying to run it as a test and your test framework isn't finding any tests to run. Publishing to the broker isn't a test, it's justs task. Trying running it with node directly

**Comment by fosho** [comment]
Wow, thank you. Overlooked my script in package.json.
