### ISSUE TITLE
e2e test refers to class not available in released npm package

### ISSUE THREAD

**Issue by EwgB** [pact-foundation/pact-js#251]
## Software versions

* **Pact library**: @pact-foundation/pact-web 7.0.3

## Expected behaviour

pact-web package exports Verifier class

## Actual behaviour

NPM package has Verifier only in pact.d.ts file, but pact.js is missing.

## Steps to reproduce

I was trying to reproduce the code from examples\e2e\test\provider.spec.js in the pact-js repository. The test uses the Verifier class through the import in line 1: `const { Verifier } = require('../../../dist/pact')`. Unfortunately, the file is not present in the released NPM package of pact-web, Verifier is only refered to in the pact.d.ts typings file, but only pact-web.js is present in the node_modules/@pact-foundation/pact-web directory.

**Comment by mefellows** [comment]
The Verifier is only available in the `@pact-foundation/pact` package, not `@pact-foundation/pact-web` (which has a specific purpose and is probably not what you want, at least not for this, see the README).

The E2E test is there to test the first package, not `pact-web`.

**Comment by EwgB** [comment]
The Readme didn't help me unfortunately. I need to run the provider side verification in the browser context, and pact-web seems then to only support consumer side, is this right?

**Comment by mefellows** [comment]
I'm a bit confused as to how a browser based app could be a provider, bit
perhaps you could describe your situation further?

The long and the short of it is that the verifier cannot be run in a
non-node environment due to some runtime dependencies.

**Comment by EwgB** [comment]
Yeah, it is a peculiar situation. We have a web application that is the actual consumer, and a Windows-native container application (Chromium-based, written in C#) that is the provider. But the container is not a REST service that listens to calls on the network interface, so we can't test it using https://github.com/pact-foundation/pact-net. Instead, the container application intercepts calls from the web app that are using a particular protocol or schema and, instead of passing them on to the network, answers them itself and sends the response to the web app. So the consumer and provider talk to each other using a REST API, but the do it not over the normal network interface.
So my idea was to run the provider verification from a dummy web app that is run inside the container just like our normal one and sends the requests the same way. The container then intercepts them and sends the response back to the dummy app, which can then verify them. But for that I would have to run the verifier not in a node app, but in a web app.

**Comment by mefellows** [comment]
For verification to work, the provider must start up a server listening on a port. If that's the case, then it probably doesn't need to be run from pact-web.

If not, I don't think pact-web can help you. If you could provide some more detail as to how the provider listens on an interface we might be able to come up with another strategy and see if we can help. 

You might want to checkout https://github.com/pact-foundation/pact-ruby-standalone/releases and look at the provider verifier - this is what Pact JS will invoke to perform the provider side verification. The `pact-web` variant can't run this process, as browser based environments do not have access to the file system to do this.
