### ISSUE TITLE
when i run the test examples of mocha,it throw an error

### ISSUE THREAD

**Issue by itlixiaolong** [pact-foundation/pact-js#256]
## Software versions

* **OS**: window 10
* **Consumer Pact library**:     "@pact-foundation/pact": "^7.2.0"
* **Provider Pact library**:none
* **Node Version**: `v8.11.2`

## Expected behaviour
2passing
TBC

## Actual behaviour
   
[2018-12-12T10:55:56.596Z] ERROR: pact-node@6.20.0/25780 on SYS-20180608SQD:
    Pact Binary Error: C:/Users/Administrator/Desktop/pact-js-master/pact-js-master/examples/mocha/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/settings.rb:40: warning: failed to load encoding (CP936); use ASCII-8BIT instead
2018-12-12T10:55:57.711Z]  WARN: pact-node@6.20.0/25780 on SYS-20180608SQD: Pact exited with code 1.
[2018-12-12T10:55:57.712Z]  INFO: pact-node@6.20.0/25780 on SYS-20180608SQD: Removing Pact with
PID: 32736
����: û���ҵ����� "32736"��
    1) "before all" hook

  0 passing (10s)
  1 failing

  1) The Dog API
       "before all" hook:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Administrator\Desktop\pact-js-master\pact-js-master\examples\mocha\test\get-dogs.spec.js)
TBC

## Steps to reproduce
"use strict";

const expect = require("chai").expect;
const path = require("path");
const { Pact } = require('@pact-foundation/pact')
const { getMeDogs, getMeDog } = require("../index");

describe("The Dog API", () => {
  let url = "http://localhost";
  const port = 8992;

  const provider = new Pact({
    port: port,
    log: path.resolve(process.cwd(), "logs", "mockserver-integration.log"),
    dir: path.resolve(process.cwd(), "pacts"),
    spec: 2,
    consumer: "MyConsumer",
    provider: "MyProvider",
    pactfileWriteMode: "merge"
  });

  const EXPECTED_BODY = [
    {
      dog: 1
    },
    {
      dog: 2
    }
  ];

  // Setup the provider
  before(() => provider.setup());

  // Write Pact when all tests done
  after(() => provider.finalize());

  // verify with Pact, and reset expectations
  afterEach(() => provider.verify());

  describe("get /dogs", () => {
    before(done => {
      const interaction = {
        state: "i have a list of dogs",
        uponReceiving: "a request for all dogs",
        withRequest: {
          method: "GET",
          path: "/dogs",
          headers: {
            Accept: "application/json"
          }
        },
        willRespondWith: {
          status: 200,
          headers: {
            "Content-Type": "application/json"
          },
          body: EXPECTED_BODY
        }
      };
      provider.addInteraction(interaction).then(() => {
        done();
      });
    });

    it("returns the correct response", done => {
      const urlAndPort = {
        url: url,
        port: port
      };
      getMeDogs(urlAndPort).then(response => {
        expect(response.data).to.eql(EXPECTED_BODY);
        done();
      }, done);
    });
  });

  describe('get /dog/1', () => {
    before(done => {
      const interaction = {
        state: 'i have a list of dogs',
        uponReceiving: 'a request for a single dog',
        withRequest: {
          method: 'GET',
          path: '/dogs/1',
          headers: {
            'Accept': 'application/json'
          }
        },
        willRespondWith: {
          status: 200,
          headers: {
            'Content-Type': 'application/json'
          },
          body: EXPECTED_BODY
        }
      }
      provider.addInteraction(interaction).then(() => {
        done()
      })
    })

    it('returns the correct response', done => {
      const urlAndPort = {
        url: url,
        port: port
      }
      getMeDog(urlAndPort)
        .then(response => {
          expect(response.data).to.eql(EXPECTED_BODY)
          done()
        }, done)
    })
  })
});

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Your issue states that your using Mac osx, but i can see that it's worrie Windows, right?

I also note a comment on encoding, so my guess is that's something to look into. Might be worth doing a search through our issues to see if there anything there

**Comment by itlixiaolong** [comment]
i am so sorry about my carelessness, i forgot to rewrite the os of the issue template

**Comment by itlixiaolong** [comment]
i saw the issues but i can not find the solution of this, a similar issues is base on react,but there is not a clear solution to resolve this, if you can provide a  help, i will thanks for your kind

**Comment by mefellows** [comment]
Have you seen any of these?

* https://github.com/pact-foundation/pact-node/issues/75
* https://github.com/pact-foundation/pact-go/issues/41, and
* https://github.com/pact-foundation/pact-go/issues/36

My guess is there is an explicit encoding set in your environment that is overriding ours, which is causing an issue.

**Comment by itlixiaolong** [comment]
Thanks for your reply,but I have checked my code,There is no obvious code to set encoding , and all files default to utf-8!

**Comment by mefellows** [comment]
It's not the code I'm thinking is setting it, but the OS environment itself.

Could you please print out the values of your current shell environment?

**Comment by malongqi** [comment]
Pact Binary Error: WARN: No content type found, performing text diff on body
![image](https://user-images.githubusercontent.com/13143170/50130042-c097fb80-02b6-11e9-8e1a-0dc1b7751bb9.png)

Why is this error reported when the run succeeds

**Comment by itlixiaolong** [comment]
Is this what you said?

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Administrator\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SYS-20180608SQD
ComSpec=C:\Windows\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\Administrator
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
LOGONSERVER=\\SYS-20180608SQD
NPM_HOME=E:\软件\nvmNode\install
NUMBER_OF_PROCESSORS=4
NVM_HOME=C:\Users\Administrator\AppData\Roaming\nvm
NVM_SYMLINK=C:\Program Files\nodejs
OneDrive=C:\Users\Administrator\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\软件\Git\cmd;E:\mysql\bin;E:\软件\nvmNode\install;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\;E:\软件\Scripts\;E:\软件\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;E:\软件\Microsoft VS Code\bin;E:\软件\Microsoft VS Code\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\atom\bin;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
TMP=C:\Users\ADMINI~1\AppData\Local\Temp
USERDOMAIN=SYS-20180608SQD
USERDOMAIN_ROAMINGPROFILE=SYS-20180608SQD
USERNAME=Administrator
USERPROFILE=C:\Users\Administrator
VSCODE_CWD=E:\syswin-work
windir=C:\Windows
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.30.0
LANG=en_US.UTF-8

**Comment by mefellows** [comment]
@malongqi is that issue related to this? In any case, it's a warning and obviously the text diff is working so the tests are passing. Set the appropriate `Content-Type` headers and that should go away.

**Comment by mefellows** [comment]
Yes, thanks @itlixiaolong. I'm not sure what's going on specifically, but I'm guessing it has to do with Chinese character encodings. All I can find is https://bugs.ruby-lang.org/issues/1048. Are there any other settings you can think of that might affect encoding?

**Comment by itlixiaolong** [comment]
I can't think of any other Settings that affect the character set right now,but i will keep trying,By the way, what is the correct settings of my current shell environment that  you think

**Comment by almai** [comment]
I know, I'm a little bit late to the party, but for anybody who encounters this error: It occurs when you forget to add a content-type to the request headers like so.

![dsstf-agent-gui_–_test_pact_spec_ts](https://user-images.githubusercontent.com/402692/173159084-1f6a0385-e5b5-4149-b4fe-72052cdadc9a.jpg)
