### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by liangguohun** [pact-foundation/pact-js#258]
this don‘t tell how can i let it work,the pacts do not create.

**Comment by mboudreau** [comment]
This is for issues for the javascript project, not a place to ask how to use Pact.

Have you looked at our [website](https://docs.pact.io/) for an introduction, our [StackOverflow](https://stackoverflow.com/questions/tagged/pact) for technical questions you might have, or our [Slack channel](https://slack.pact.io/) for a broader discussion?

I'd suggest you try these first and add a question in the appropriate forum.  Thanks.
