### ISSUE TITLE
if this a bug for the demo

### ISSUE THREAD

**Issue by liangguohun** [pact-foundation/pact-js#260]
if command "test": "jest \_\_tests\_\_/  --runInBand --setupFiles ./pactSetup.js --setupTestFrameworkScriptFile ./pactTestWrapper.js",

contains \_\_tests\_\_/
will response me 
---
No tests found
In g:\shareApp
  12 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 2 matches
  testPathIgnorePatterns: \\node_modules\\ - 12 matches
Pattern: __tests__/ - 0 matches

and don't create pacts folder
---
if command "test": "jest  \_\_tests\_\_ --runInBand --setupFiles ./pactSetup.js --setupTestFrameworkScriptFile ./pactTestWrapper.js",
[2019-01-04T09:09:39.440Z]  INFO: pact@7.0.3/13040 on WIN-CKQKCJMPARV:
    Setting up Pact with Consumer "AppConsumer" and Provider "AppProvider"
       using mock service on Port: "8080"
[2019-01-04T09:09:44.482Z]  INFO: pact-node@6.21.0/13040 on WIN-CKQKCJMPARV:
    Deleting Pact Server with options:
    consumer = AppConsumer,
    cors = false,
    dir = g:\app\shareApp\pacts,
    host = 127.0.0.1,
    log = g:\app\shareApp\logs\pact.log,
    pactFileWriteMode = update,
    port = 8080,
    provider = AppProvider,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey =
 FAIL  __tests__\state-functions.test.js (10.029s)
  ● Console

    console.log pactSetup.js:6
      ---------global.provider create---------------0
    console.log pactTestWrapper.js:4
      ---------beforeAll----------------1
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:194
      Unhandled error
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:195
      Error: listen EACCES 127.0.0.1:8080
          at Server.setupListenHandle [as _listen2] (net.js:1343:19)
          at listenInCluster (net.js:1401:12)
          at doListen (net.js:1510:7)
          at _combinedTickCallback (internal/process/next_tick.js:142:11)
          at process._tickCallback (internal/process/next_tick.js:181:9)
    console.log pactTestWrapper.js:11
      ------------afterAll-------------end
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:194
      Unhandled error
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:195
      undefined

  ● Addition › knows that 2 and 2 make 4

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at ontimeout (timers.js:498:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:290:5)

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        21.845s
Ran all test suites matching /\_\_tests\_\_/i.
npm ERR! Test failed.  See above for more details.

**Comment by mefellows** [comment]
I'm not sure what you're asking sorry. Can you please provide the exact steps to reproduce your issue including code that we can run? Is this your code or one of our examples? Also, it appears there is a port conflict on 8080

**Comment by liangguohun** [comment]
It doesn't matter

**Comment by liangguohun** [comment]
the question maybe the network to bad!
**but** 
**system win7 64
software 
    "@pact-foundation/pact": "^7.0.3",
    "@pact-foundation/pact-node": "^6.20.0",**


 ERROR: pact-node@6.20.0/7624 on WIN-CKQKCJMPARV:
    Pact Binary Error: <internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
        from <internal:gem_prelude>:1:in `<compiled>'

    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:194
      Unhandled error
    console.error node_modules\jest-jasmine2\build\jasmine\Env.js:195
      PopsicleError: Unable to connect to "http://127.0.0.1:8891/pact"
          at Request.Object.<anonymous>.Request.error (g:\App\node_modules\popsicle\dist\request.js:41:16)
          at ClientRequest.<anonymous> (g:\App\node_modules\popsicle\dist\index.js:131:39)
          at ClientRequest.emit (events.js:182:13)
          at Socket.socketErrorListener (_http_client.js:392:9)
          at Socket.emit (events.js:182:13)
          at emitErrorNT (internal/streams/destroy.js:82:8)
          at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
          at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by liangguohun** [comment]
i can't run of the example yours'
if i don't add '/' after \_\_tests\_\_ it can't run like above
> jest \_\_tests\_\_**/**  --runInBand --setupFiles ./pactSetup.js --setupTestFrameworkScriptFile ./pactTestWrapper.js

No tests found
In g:\shareApp
  14 files checked.
  testMatch: **/\_\_tests\_\_/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 2 matches
  testPathIgnorePatterns: \\node_modules\\ - 14 matches
Pattern: \_\_tests\_\_/ - 0 matches

**Comment by liangguohun** [comment]
i found that ，because i am in the spacial country china ,the chinese path make it
this time i print all the stack make logLevel: "trace", and path not contains chinese


Pact Binary Error: g:/shareApp/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/ruby/lib/ruby/2.2.0/fileutils.rb:252: warning: failed to load encoding (CP936); use ASCII-8BIT instead

**but now**
one of the base jest test can't pass

**Comment by liangguohun** [comment]
Pact Binary Error: g:/App/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/ruby/lib/ruby/2.2.0/fileutils.rb:252: warning: failed to load encoding (CP936); use ASCII-8BIT instead

just this question now

**Comment by liangguohun** [comment]
and just now i move the app to mac 10.14
the version don't response different like the package.json

**ERROR**: pact-node@6.21.1/1700 on liangguohundeMac.local:
    Pact Binary Error: /bin/sh: ./standalone/darwin-1.63.0/bin/pact-mock-service: No such file or directory

**Comment by TimothyJones** [comment]
This looks like it is something to do with the encoding in the operating system / environment, rather than in `pact-js` itself. I think this is also reported in issue #256.

You're seeing a ruby error because the javascript pact modules wrap the ruby binaries.

It might be because CP936 is a Microsoft code page - @mefellows , perhaps we can fix this by adding this gem to pact? https://github.com/ConradIrwin/encoding-codepage

**Comment by liangguohun** [comment]
i still don't know how to fixed it i try to contract  @lixiaolong

**Comment by bethesque** [comment]
We need a windows build to try and recreate the issue. Is there any windows CI system you can use like appveyor?

**Comment by mefellows** [comment]
We have an [`appveyor.yml`](https://github.com/pact-foundation/pact-js/blob/master/appveyor.yml) file and example tests. If you can make it fail for the same reasons we can further this ticket.

**Comment by liangguohun** [comment]
ok，i try

**Comment by liangguohun** [comment]
thanks,event thought i don't get the newest version
but i get my target now

 "dependencies": {
    "@babel/core": "^7.0.0",
    "expo": "^31.0.2",
    "react": "^16.5.0",
    "react-native": "^0.57.1",
    "**@pact-foundation/pact-node": "^4.8.3"**
  },
  "jest": {
    "testEnvironment": "node"
  },
  "devDependencies": {
    **"pact": "^2.6.0",
    "mocha": "^3.3.0",**
    "axios": "^0.14.0",
    "babel-jest": "^23.6.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-expo": "^5.0.0",
    "babel-preset-react": "^6.24.1",
    "jest": "^23.6.0",
    "jest-cli": "^21.2.1"
  },
**and the version** 
 "jest-cli": "^21.2.1"

at run_test.js environment.dispose(); not contain, i just annotation it ,and all the test pass and create the pacts'files

**Comment by mefellows** [comment]
Thanks, I'm not sure I completely followed what you did, but glad to hear it's working :)
