### ISSUE TITLE
Is it possible to publish a metaData as contract

### ISSUE THREAD

**Issue by saikrishna321** [pact-foundation/pact-js#262]
@mefellows @bethesque 

Can the consumer provide some metaData details like emailID, contact-info so this makes easy to the provider to communicate

**Comment by mefellows** [comment]
The short answer is no. 

It's a good idea, one that has been [talked about](https://github.com/pact-foundation/pact-specification/issues/34). Perhaps it's worth bumping that thread and seeing where it takes us. For it to be useful

My guess is that if we can get it written to the metadata section, it won't have a functional impact in other libraries so is worth considering outside of the formal specification anyway.

**Comment by mefellows** [comment]
FWIW you could always annotate the pact file manually after it is generated by injecting those details into a `metadata` section yourself.

So for now, I'll close this and if we provide official support via the standard libraries we can bring it back in.
