### ISSUE TITLE
Cannot use matchers in withRequest.query during consumer API testing

### ISSUE THREAD

**Issue by ShepardPinAnda** [pact-foundation/pact-js#263]
## Software versions

* **OS**:  MacOS Mojave 10.14.2 
* **Consumer Pact library**: pact-web :7.2.0
* **Provider Pact library**:  pact-node : 6.2.0
* **Node Version**:  v8.9.3

## Introduction:
The scenario is that a POST request will be sent with nonce in query param , like /xxx/yyy?nonce = 123453423 . The nonce is a timestamp which will be generated automatically.  As it is a some sort of random number , I try to use matchers in withRequest.query .
the set up interaction code will be like :

```js
     beforeAll(done => {
        let interaction:InteractionObject ={
          state: 'testing',
          uponReceiving: ex,
          withRequest: {
            method: 'POST',
            path: '/api/v1/test',
            query:{
              **nonce: Matchers.integer()**
            }
            body:{
            },
            headers:{
              'Content-Type': 'application/json'
            }
          },
          willRespondWith: {
            status: 200,
            body: {
              test :'test'
            }, 
            headers: {
              'Content-Type': 'application/json'
            }
          }

        }; 
```

## Expected behaviour

When the send the request like ` /api/v1/test?nonce=15523423423` , it should pass .

## Actual behaviour

But error occur and tell me that the request para error

**Comment by mefellows** [comment]
All query strings are, well, strings. So you can't do an integer match on a string as they are different types.

What you want to do is this:

```js
nonce: Matchers.regex({generate: '1234', matcher: "\\d+"})
```
