### ISSUE TITLE
pact doesn't seem to honor package.json config settings on CI (debian)

### ISSUE THREAD

**Issue by two7sclash** [pact-foundation/pact-js#264]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact JS v2.6.0
* **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
* **Node Version**: `node --version`

## Expected behaviour

TBC

## Actual behaviour

TBC

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by TimothyJones** [comment]
Which config settings aren’t honoured?

**Comment by mefellows** [comment]
Closing due to inability to qction. Please reopen when you have completed the issue template
