### ISSUE TITLE
pact-js mock-server not starting on CentOS 7

### ISSUE THREAD

**Issue by supasympa** [pact-foundation/pact-js#265]
Running the Mocha / get-dogs example: the Pact mock-server doesn't start (see logs below).

## Software versions
* **OS**: 
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

* **Consumer Pact library**: "@pact-foundation/pact": "7.2.0"
* **Node Version**: 8.10.0

## Expected behaviour

Tests to execute and pass

## Actual behaviour

Tests fail at before hook / 

## Steps to reproduce

Run the Mocha example on CentOS 7

## Relevant log files

```
[2019-01-29T07:40:06.359Z]  INFO: pact-node@6.21.2/15021 on gblinvdi0082: 
    Creating Pact Server with options: 
    consumer = MyConsumer,
    cors = false,
    dir = /w/api/pacts,
    host = 127.0.0.1,
    log = /w/api/logs/pact.log,
    pactFileWriteMode = merge,
    port = 8992,
    provider = MyProvider,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey = 
[2019-01-29T07:40:06.362Z]  INFO: pact@7.2.0/15021 on gblinvdi0082: 
    Setting up Pact with Consumer "MyConsumer" and Provider "MyProvider"
       using mock service on Port: "8992"


  The Dog API
[2019-01-29T07:40:06.399Z]  INFO: pact-node@6.21.2/15021 on gblinvdi0082: Created './standalone/linux-x64-1.63.0/bin/pact-mock-service service --consumer 'MyConsumer' --pact_dir '/w/api/pacts' --host '127.0.0.1' --log '/w/api/logs/pact.log' --pact-file-write-mode 'merge' --port '8992' --provider 'MyProvider' --pact_specification_version '2'' process with PID: 15031
    1) "before all" hook

  0 passing (30s)
  1 failing

  1) The Dog API
       "before all" hook:
     Error: Promise rejected with no or falsy reason
      at /w/api/node_modules/mocha/lib/runnable.js:383:26
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



[2019-01-29T07:40:36.018Z]  INFO: pact@7.2.0/15021 on gblinvdi0082: Pact File Written
[2019-01-29T07:40:36.019Z]  INFO: pact-node@6.21.2/15021 on gblinvdi0082: Removing Pact with PID: 15031
[2019-01-29T07:40:36.020Z]  INFO: pact-node@6.21.2/15021 on gblinvdi0082: 
    Deleting Pact Server with options: 
    consumer = MyConsumer,
    cors = false,
    dir = /w/api/pacts,
    host = 127.0.0.1,
    log = /w/api/logs/pact.log,
    pactFileWriteMode = merge,
    port = 8992,
    provider = MyProvider,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey = 
```

**Comment by mefellows** [comment]
Hmm, this is quite strange. There are no obvious reasons for this, but it does look like a 30s timeout was reached. One possibility is that it was unable to start or communicate with a mock server on port `8992`. 

See if you can manually start the server with the same options. The path should be something like this:

```
./node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.63.0/bin/pact-mock-service service --consumer 'MyConsumer' --pact_dir '/home/INTL/a568720/code/wealth/gdw/api/pacts' --host '127.0.0.1' --log '/home/INTL/a568720/code/wealth/gdw/api/logs/pact.log' --pact-file-write-mode 'merge' --port '8992' --provider 'MyProvider' --pact_specification_version '2'
```

**Comment by supasympa** [comment]
I tried also in a Docker container from Node:8, with the same results. I'm beginning to think that the issue is related to the corporate network I am running on rather than the OS.

**Comment by mefellows** [comment]
Can you interact with localhost on Port 8992 after drinking that command? It looks like it started successfully actually.

Along the corporate network lines, it's also work checking if you have any environment variables such as http_proxy that might he interfering with the requests

**Comment by supasympa** [comment]
> Can you interact with localhost on Port 8992 after running that command? It looks like it started successfully actually.
> 
> Along the corporate network lines, it's also work checking if you have any environment variables such as http_proxy that might he interfering with the requests

Thanks!

It appears my problem was a combination of: Proxy settings, permissions for the logs and pact file and eventually not returning a promise!

**Comment by mefellows** [comment]
😆
