### ISSUE TITLE
Proposal: pact-web provider.addInteraction to also allow Interaction instance

### ISSUE THREAD

**Issue by eijiew** [pact-foundation/pact-js#270]
Currently pact and pact-web `provider.addInteraction` differs by pact accepting `InteractionObject | Interaction` as the argument whereas pact-web only accept `InteractionObject`

Could I propose for pact-web `provider.addInteraction` to also take in `Interaction`? So that it will be more consistent with pact implementation. Another advantage will be allowing pact-web to support interaction such as `GraphQLInteraction`

**Comment by mefellows** [comment]
Thanks, this is a good idea. Happy for you to PR or for somebody to pick this up if they have time.

**Comment by eijiew** [comment]
Thank you. I will proceed to close this Issue 😃

**Comment by mefellows** [comment]
No worries. I'll release this in the next few days
