### ISSUE TITLE
Is there a way to dump all interactions added against a pact server?

### ISSUE THREAD

**Issue by jhenderson2099** [pact-foundation/pact-js#273]
You can add one or more interactions against the mock pact server.  Is there a URL that you can hit to have it dump all the recorded interactions, their associated methods, and their expected responses?

**Comment by mefellows** [comment]
I don't believe so, why? You can read up on its capabilities more here https://github.com/pact-foundation/pact-mock_service

**Comment by jhenderson2099** [comment]
Thanks for that link!  Well I started pawing through the source code and saw some of those endpoints, but given that you can add endpoints and clear end points, it just seemed like a logical extension.  (Something like GET /interactions.)

As I am new to PactJS, does each interaction remain until you clear the interactions?  I believe that this is done automatically after you run a test case and you verify a pact.  Or are they removed at some other point.  (I can see the DELETE /interactions being called in the log.)

I am asking these questions as I am trying to determine what I have available for debugging and what interactions are stored against the mock pact server, and if they are stored, how long are they stored?

**Comment by mefellows** [comment]
> As I am new to PactJS, does each interaction remain until you clear the interactions?

Yes (the mock server is stateful)..

> I believe that this is done automatically after you run a test case and you verify a pact. 

correct, `verify()` will do this.

> I am asking these questions as I am trying to determine what I have available for debugging and what interactions are stored against the mock pact server, and if they are stored, how long are they stored?

The main tool at your disposal is the log file that's generated - it will show you which interactions were registered, when they get cleared, verified etc., and when it receives a request (e.g. from a unit test)

Is there something else we could be doing?

**Comment by jhenderson2099** [comment]
I have found the log tool.  I guess I was looking for a way outside the log to dump the interactions that are available.  You sorta have to pay through the log and look at it at a specific point in time.  

If you use Karma, then you can set a Javascript breakpoint and then dump the available interactions.  That would allow you to determine what the "state of the union" is while trying to debug, rather than run and try and piece together what the interaction(s) were when the tests ran.  I'm sure that most people just deal with the log, so what I was asking about is clearly a "nicety" and not a "necessity".

You have answered my questions, so I appreciate that.  If there are no plans to do what I am requesting, feel free to close out this ticket.  

Thanks again for the feedback.

**Comment by bethesque** [comment]
Pact works best when you use it as a unit test framework for the code that is responsible for calling the provider. When you use it like this, you typically only have one or two interactions mocked at a time, so there isn't really any confusion about the state of the mock. If you have so many interactions mocked that you're having trouble keeping track of the state, you may be using Pact to test from a higher level of abstraction, and this is not recommended, as it leads to Pain (as you are finding). Have a read of this: https://docs.pact.io/best_practices/consumer#use-pact-for-isolated-unit-tests

**Comment by mefellows** [comment]
> If you use Karma, then you can set a Javascript breakpoint and then dump the available interactions. > That would allow you to determine what the "state of the union" is while trying to debug, rather than > run and try and piece together what the interaction(s) were when the tests ran

I think that could still be achieved, albeit only in the context of the current interaction. Pact JS could be modified to have an internal state representation which it stores as per the same lifecycle as to what gets transmitted over the wire to the underlying Ruby process (e.g. in https://github.com/pact-foundation/pact-js/blob/master/src/dsl/mockService.ts). I'm fairly confident that you could then instrument in the usual manners and see this object. I'm not necessarily comfortable in adding this just for that sake, but perhaps it's a line worth pursuing for other reasons - can you think of any?

**Comment by bethesque** [comment]
It would be easier to add another endpoint to the mock server to display the current state of the world in a browser. It would be quite simple.
