### ISSUE TITLE
Problem with Getting url

### ISSUE THREAD

**Issue by krzysztofstepniak-silvair** [pact-foundation/pact-js#276]
## Software versions

* **OS**: e.g. Mac OSX 10.13.6
* **Consumer Pact library**: @pact-foundation/pact": "^7.3.0",
* **Provider Pact library**: "@pact-foundation/pact-node": "^6.21.4",
* **Node Version**: `node --version 10`

## Expected behaviour

Should use path

## Actual behaviour

{"message":"No interaction found for GET /projects/5c7cd78b77807ed3d0b70d16/floors?include=nodesCount","interaction_diffs":[]}

## Relevant log files

expected 200 "OK", got 500 "Internal Server Error"

    -- Request
      URL: http://localhost:50034/projects/5c7cd78b77807ed3d0b70d16/floors?include=nodesCount
      Headers: {
        - user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko)Chrome/63.0.3239.132 Safari/537.36
- authorization: Basic c3p5bW9uLmthY3BlcnNraTpzWTNxR25ZUjg5
      }
    -- Response
      Status: 500
      Headers: {
        - content-type: application/json
- server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13) OpenSSL/1.0.2d
- date: Mon, 04 Mar 2019 07:45:15 GMT
- content-length: 127
- connection: close
      }
      Body:
        {"message":"No interaction found for GET /projects/5c7cd78b77807ed3d0b70d16/floors?include=nodesCount","interaction_diffs":[]}

Test looks like:

describe('Floors consumer', function() {
  this.timeout(10000);
  let platformBFF;
  let portPlatformBff;
  let request;
  let token;
  let setup;
  let projectId;

  before(async () => {
    setup = env.platformService;
    portPlatformBff = await getPort();
    token = await auth0.getToken(USER);
    // await setup.cleanEnv(token);

    platformBFF = new Pact({
      dir: PACTS_DIR,
      consumer: 'spaces-web-floor',
      provider: 'platform-bff',
      port: portPlatformBff,
      logLevel: PACT_LOG_LEVEL,
      pactfileWriteMode: 'update'
    });

    await platformBFF.setup();

  });

  after(async () => {
    return await platformBFF.finalize();
  });

  afterEach(async () => {
    await platformBFF.removeInteractions();
  });

  describe('GET /projects/{id}/floors?include=nodesCount', async () => {
    before(async () => {
      projectId = (await setup.createProject('floor', token)).body._id;
      await Promise.all([platformBFF.addInteraction(getFloors(projectId)),
        request = bffService.create(`http://localhost:${portPlatformBff}`)]);
    });

    it('GET for getting floors /projects/{id}/floors?include=nodesCount', async () => {
      await request.getFloors(projectId, null, 'nodesCount')
        .expect(200);
      await platformBFF.verify();
    });
  });
});
 and Interaction :

const getFloors = (projectId) => {
  return ({
    uponReceiving: 'request for getting all floors',
    withRequest: {
      method: 'GET',
      path: `/projects/${projectId}/floors?include=nodeCount`,
    },
    willRespondWith: {
      status: 200,
      headers: {'Content-Type': 'application/json'},
      body: getResponse
    }
  });
};

Funny thing is that when I use query:  include=nodeCount it starting to works fine. Also I had problem with matcher in path: path: term({generate: `/projects/${projectId}/floors?include=nodeCount`, matcher: '/projects/[a-f0-9]{24}$/floors?include=nodeCount'}) it always returns me ruby log that is not the same url (but it looks the same...).

**Comment by mefellows** [comment]
I think we responded to this in the Slack thread - basically, you need to use the `query` option to specify query args, rather than have them encoded in the `path` parameter as per above. Closing.
