### ISSUE TITLE
Probleme with ruby in docker alpine

### ISSUE THREAD

**Issue by Patafix** [pact-foundation/pact-js#285]
## Software versions

* **OS**: e.g. Alpine
* **Consumer Pact library**: e.g. Pact JS v8.02
* **Node Version**: 8

## Expected behaviour

TBC

## Actual behaviour

I dont understand how can i make my test pipeline work
My unit testing is blocked by this error  : 

```
[2019-03-14T10:49:36.893Z]  WARN: pact-node@6.21.5/51 on runner-s6srzpza-project-8934-concurrent-0z298c: Pact exited with code 127.
[2019-03-14T10:49:36.893Z]  INFO: pact-node@6.21.5/51 on runner-s6srzpza-project-8934-concurrent-0z298c: 
    /foo/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.63.0/lib/ruby/bin/ruby: line 6: /foo/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.63.0/lib/ruby/bin.real/ruby: No such file or directory
```

I understand i need ruby for my unit test, but i dont want to add ruby to my docker-image for production, and i make my test with the production image.

On the npm-install stage the package installation show no errors  : 

```
> node postinstall.js

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.63.0 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.63.0/pact-1.63.0-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Downloaded 0.67%...
Finished downloading binary to /foo/node_modules/@pact-foundation/pact-node/standalone/pact-1.63.0-linux-x86_64.tar.gz
Extracting binary from /foo/node_modules/@pact-foundation/pact-node/standalone/pact-1.63.0-linux-x86_64.tar.gz.
Checksum passed for 'pact-1.63.0-linux-x86_64.tar.gz'.
Extraction done.


### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node


Pact Standalone Binary is ready.
```

I missing something here can you help me ?

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-js/issues/154#issuecomment-368675374, https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker and https://github.com/pact-foundation/pact-mock-service-docker/blob/master/Dockerfile

**Comment by mefellows** [comment]
You don't need to install Ruby - it's bundled into the npm package directly. 

> I understand i need ruby for my unit test, but i dont want to add ruby to my docker-image for production, and i make my test with the production image.

Hopefully that doesn't mean the pact js library is in your production image?

**Comment by Patafix** [comment]
> Hopefully that doesn't mean the pact js library is in your production image?
No

I already try the above ->  https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker 

But for my testing i need a specific image : 

```
test:
  stage: test
  **image: *my-production-image***
  artifacts:
    paths:
      - pacts
  script:
    - npm run test
  services:
    - docker:dind
```

**Comment by mefellows** [comment]
Sorry, I'm not sure what you mean. You have your own custom image with the extra packages added? If you can share the docker image definition we could try and reproduce it.

**Comment by Patafix** [comment]
Thx for you're time i probably miss something big...

I have a docker production image, based on alpine, with some other stuff, not so specific.

I have a previous stage using this image who execute npm install : 

```yaml
npm-install:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}-nodes
    paths:
        - node_modules/
  image: *my-production-image
  script:
    - npm install
```
After some job i have my stage test who using  node_modules cached by the previous job and the same production image.

The solution suggest i need a other image based on => https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker

What should i do use this dockerfile and modify it to add node and other stuff i need ?

**Comment by Patafix** [comment]
I also try this more simple case with no succes : 

```
test:
  stage: test
  image: node:alpine
  script:
    - apk add build-base ruby
    - npm install
    - npm run test
```


Part of the log

```
> @pact-foundation/pact-node@6.21.5 postinstall foo/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.63.0 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.63.0/pact-1.63.0-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Downloaded 0.11%...
Finished downloading binary to foo/node_modules/@pact-foundation/pact-node/standalone/pact-1.63.0-linux-x86_64.tar.gz
Extracting binary from foo/node_modules/@pact-foundation/pact-node/standalone/pact-1.63.0-linux-x86_64.tar.gz.
Checksum passed for 'pact-1.63.0-linux-x86_64.tar.gz'.
Extraction done.


### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node


Pact Standalone Binary is ready.
```

```
$ npm run test

> foo@1.0.31 test bar

[2019-03-14T12:33:52.570Z]  WARN: pact-node@6.21.5/1810 on runner-s6srzpza-project-8934-concurrent-0h8w5b: Pact exited with code 127.
[2019-03-14T12:33:52.571Z]  INFO: pact-node@6.21.5/1810 on runner-s6srzpza-project-8934-concurrent-0h8w5b: 
    /foo/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.63.0/lib/ruby/bin/ruby: line 6:/foo/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.63.0/lib/ruby/bin.real/ruby: No such file or directory
```

**Comment by Patafix** [comment]
The same exact pipeline and test with node:stretch instead of node:alpine work wihout any problem

**Comment by mefellows** [comment]
I think you're still missing build-dependencies, no?

**Comment by Patafix** [comment]
@mefellows its not a package more an argument of --virtual, if I'm not wrong. 

I really think there is an issue with this package on alpine.

**Comment by mefellows** [comment]
I think it's just missing bash. Please follow #296.

**Comment by kjenney** [comment]
I've got bash and I'm still getting the same error.
