### ISSUE TITLE
 We don't fully support proxying remote APIs - from slack talk

### ISSUE THREAD

**Issue by krzysztofstepniak-silvair** [pact-foundation/pact-js#291]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: @pact-foundation/pact": "^8.0.5
* **Node Version**: `node --10.13`

## Expected behaviour
I want check provider side bfrom jenkins, localhost against remote server with project.

## Actual behaviour
It is problem with ssl check. States are starting but when it comes to check against real service  I have such error: `Uncaught Error: write EPROTO 140735494108032:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 40`
OR
`Uncaught Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:platform-dev.silvair.com, DNS:*.platform-dev.silvair.com`
TBC

## Steps to reproduce
Try to check provider side with remote api

more informations are available on slack channel:
https://pact-foundation.slack.com/archives/C9VBGLUM9/p1554102838010100

**Comment by YOU54F** [comment]
I saw the following errors, raised in the below issues

https://github.com/pact-foundation/pact-js/issues/280
https://github.com/pact-foundation/pact-js/issues/281

I added this change in 

https://github.com/pact-foundation/pact-js/pull/282

to include `changeOrigin` flag

**Comment by krzysztofstepniak-silvair** [comment]
So where should I add this flag and what should be there passed?

**Comment by krzysztofstepniak-silvair** [comment]
Ok, I see it. Just change it on true.

**Comment by mefellows** [comment]
Closing as we have a working solution.
