### ISSUE TITLE
Issue with binary while running inside Docker Node Alpine

### ISSUE THREAD

**Issue by halfzebra** [pact-foundation/pact-js#296]
Hello friends!

Thank you for Pact, I like it very much. 👍 

Unfortunately, I'm unable to get it to work inside Docker.
Any ideas on how I might be getting this to work?

Please help!

## Software versions

* **OS**: e.g. Alpine Linux v3.9
* **Consumer Pact library**: e.g. Pact JS v8.2.0
* **Node Version**: `v8.16.0`

## Expected behaviour

I expect the test to fail gracefully with the following:

```
4 interactions, 4 failures

Failed interactions:


* A request for json data given date count > 0
* A request with an invalid date parameter given date count > 0
* A request with a missing date parameter given date count > 0
* A request for json data given date count == 0
```

## Actual behaviour

My test crashes with:

```
[2019-04-23T22:00:08.256Z]  WARN: pact-node@8.1.2/26 on 6ef9934a5998: Pact exited with code 127.
 FAIL  ./pact.test.js
  dummy pact verification
    ✕ should validate the expectations of Our Little Consumer (98ms)

  ● dummy pact verification › should validate the expectations of Our Little Consumer

    /bin/sh: ./standalone/linux-x64-1.64.0/bin/pact-provider-verifier: not found

      at ChildProcess.<anonymous> (node_modules/@pact-foundation/pact-node/src/verifier.ts:156:55)
```

## Steps to reproduce

https://github.com/halfzebra/pact-docker-issue

**Comment by mefellows** [comment]
Thanks for the kind words and repro. Before we investigate further, have you seen any of the following:

* https://github.com/pact-foundation/pact-js/issues/206
* https://github.com/pact-foundation/pact-js/issues/285
* https://github.com/pact-foundation/pact-js/issues/265
* https://github.com/pact-foundation/pact-js/issues/154

**Comment by halfzebra** [comment]
Thanks for the quick reply!

Very helpful links, I've read through all of them and here is what I have found.

I've tried adding build dependencies but did not help.

```
RUN apk add --no-cache --virtual build-dependencies build-base
```

Adding Alpine-specific version of `glibc` as suggested [here](https://github.com/pact-foundation/pact-js/issues/154#issuecomment-405436576) did not cut it as well.

```
RUN  apk --no-cache add ca-certificates wget \
     && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
     && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
     && apk add glibc-2.29-r0.apk
```

Both tries have resulted in the original error.

Using `node:stretch` works and I might go with it as a solution. It does not feel like an elegant  solution, because I use a custom image based on `node:alpine` 😕

**Comment by mefellows** [comment]
I think it just needs bash to run:

```docker
FROM node:8-alpine

RUN apk add --no-cache --virtual build-dependencies build-base

RUN  apk --no-cache add ca-certificates wget bash \
  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
  && apk add glibc-2.29-r0.apk

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app/

RUN npm test
```

Your test fails, but for the obvious reasons. Let me know how you go. If it works, I might just create a base image for use and update docs.

**Comment by halfzebra** [comment]
Adding bash worked for me, thank you for your help! 🎉 

Please let me know if I could help with the docs, otherwise, this issue could be closed.

**Comment by mefellows** [comment]
That's great news. I'll mark as an enhancement and will update the docs / example when I get some time. Thanks for the report and repro 👍

**Comment by TimothyJones** [comment]
Bumping so this doesn’t get closed unnecessarily. Should we remove stalebot?

**Comment by TimothyJones** [comment]
Also, I will check the docs tomorrow and close this off afterwards (if you haven’t already)

**Comment by mefellows** [comment]
I think stalebot is doing its job! Silly old Matt forgot to tag this with "Documentation" and also hasn't updated the docs.

In terms of getting this done, i'm thinking maybe the Wiki is the place for this (or at least, not the README). The README is really growing a bit too large/overwhelming, and I feel this is proverbial straw that justifies the moove.

Ideas?

**Comment by mefellows** [comment]
I have added a section to our docs website on Docker, and will reference it in the README shortly: https://docs.pact.io/docker/

**Comment by qmg-rwaller** [comment]
Hi, thanks for the example and updating the docs! Is there an official docker image for that reference image (and for other node versions)? i.e.
```
FROM node:8-alpine

RUN apk add --no-cache --virtual build-dependencies build-base

RUN  apk --no-cache add ca-certificates wget bash \
  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
  && apk add glibc-2.29-r0.apk
``` 

I tried using https://hub.docker.com/r/dius/pact-provider-verifier-docker instead, but it errored with `line 1: yarn: not found`, so not sure if I'm using it correctly. We want to run `yarn install && yarn test` (which runs pactJS) inside a suitable node alpine docker image

**Comment by mefellows** [comment]
We don't have an official docker image for it sorry. Most people seem to want to customise their own base anyway.

I wouldn't use the verifier docker, because it's for a separate thing that doesn't have JS on it.

Can you not just run your own?

**Comment by qmg-rwaller** [comment]
Thanks for quick reply! Yea just checking if there's something official first, but we can run our own :)

**Comment by mefellows** [comment]
Cool, worth checking. If we weren't maintaining 12 official languages, we probably would have done it because it's fairly easy - but we have enough stuff to maintain now as it is :)

**Comment by bethesque** [comment]
Actually, I did make a node base image of the cli here https://hub.docker.com/r/pactfoundation/pact-cli/tags?page=1&ordering=last_updated

**Comment by mefellows** [comment]
Ah cool - thanks past Beth! I'll add to docs.

**Comment by TimothyJones** [comment]
Slightly off topic, but there's also the pact-node binstubs, so you can:

```
npx -p @pact-foundation/pact-node pact-broker help
```

for no-install pact CLI usage without docker.

**Comment by qmg-rwaller** [comment]
Thanks @bethesque! I may have misunderstood something - that image doesn't have `bash`, and so my build errors when `yarn test` uses  PactJS to verify a consumer pact and write it out to a JSON file:
![image](https://user-images.githubusercontent.com/70145859/110924343-d7a0e900-8319-11eb-8f1e-20ddf2d8dea2.png)

Should the image allow me to do that, or do I need to add bash? :)

**Comment by bethesque** [comment]
You need bash, sorry https://docs.pact.io/docker/#alpine-linux
