### ISSUE TITLE
Bluebird is a dependency, not a devDependency

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [pact-foundation/pact-js#299]
## Software versions

* **OS**: Linux
* **Consumer Pact library**: Pact JS v8.2.2
* **Provider Pact library**: N/A
* **Node Version**: `10.15.3`

## Expected behaviour

`@pact-foundation/pact` package lists its dependencies correctly so that it works without relying on transitive dependencies which tools like `pnpm` block

## Actual behaviour

`src/common/net.ts` imports `bluebird` unconditionally, thus making it a "real" dependency and causing the `require` to fail when used in a `pnpm` environment.

Observe: 
* https://github.com/pact-foundation/pact-js/blob/master/src/common/net.ts#L8
* https://github.com/pact-foundation/pact-js/blob/master/package.json#L124

## Steps to reproduce

Setup a `rush` repo using `pnpm`.  Add `@pact-foundation/pact` as a dependency and have one of your (test) files try to load it.

## Relevant log files

Trimmed output of the above repro case:
```
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/user/src/rush-template/common/temp/node_modules/.registry.npmjs.org/@pact-foundation/pact/8.2.2/node_modules/@pact-foundation/src/common/net.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```
(Note: sourcemaps with bad relative paths are shipped, so the above `.../@pact-foundation/src/common/net.ts` path really means `.../@pact-foundation/pact/common/net.js`

**Comment by mefellows** [comment]
Thanks @mgabeler-lee-6rs, looks to be a mistake. I'll get it updated.

**Comment by mgabeler-lee-6rs** [comment]
FYI `@types` are always a dev dependency -- they're just needed for running `tsc`

**Comment by YOU54F** [comment]
@mefellows @mgabeler-lee-6rs 

Hey Matt & Matthew,

This has broken one of my builds. Is the expectation that we need to include the @types/express in our consuming project?

```
#!/bin/bash -eo pipefail
yarn run build
yarn run v1.15.2
$ rimraf dist && tsc
node_modules/@pact-foundation/pact/dsl/verifier.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'express'. '/home/circleci/app/node_modules/express/index.js' implicitly has an 'any' type.
  Try `npm install @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`


1 import * as express from "express";
                           ~~~~~~~~~
```
https://github.com/YOU54F/jest-pact-typescript/pull/86

**Comment by YOU54F** [comment]
No worries mate, we haven't upgraded to the new release yet, it's just on a PR on my public project, and we will bring it into our clients workflow when its good to go.

Agree type snipping is the correct way to go, I found when I wrote some apps recently, that I needed some types to be shipped, but not everything.

Better to take some time to make sure that the correct approach is being taken, than to race to sort it asap!

Just thought it was worth a heads up 👍

**Comment by mefellows** [comment]
I've had a bit of a play, but I think it's a bit more complex and as you say (you need to sweep the entirety of the public interface types and you won't know what breaks until you try to compile against it - so in your project in only fails because the type is in a frequently used area), no need to rush it. I've reverted the relevant bits for now and added the types for Bluebird which should fix this. 

I'll leave the ticket open to fully clean things up.

**Comment by mefellows** [comment]
Oh, and `v8.3.4` should be going out soon...

**Comment by YOU54F** [comment]
Cheers mate, I'll post back with the results of my test run when its published. I think you meant `8.2.4`

Btw this ticket is closed, so might be worth raising a new one to track 👌 

Thanks again!

**Comment by YOU54F** [comment]
@mefellows sorted 
https://github.com/YOU54F/jest-pact/pull/18
https://github.com/YOU54F/jest-pact-typescript/pull/86

**Comment by mgabeler-lee-6rs** [comment]
Sorry for the over generalization :(

I believe the rule (referenced by @mefellows indirectly), is that you need `@types` as normal dependencies if any of your exports require those types -- e.g. method parameters & return values.

I think some other libraries attempt to solve this by re-exporting such types -- this also makes it easier if consumers want to import & use the specific version of those types that the library is using, which might not be the same as the versions the consumer is using internally.

**Comment by mefellows** [comment]
No worries @mgabeler-lee-6rs - I was only joking. If I took the advice in every issue without thinking/questioning we'd have a pretty crappy tool - so this is my fault.
