### ISSUE TITLE
No matching interaction found for GET 

### ISSUE THREAD

**Issue by L0wry** [pact-foundation/pact-js#307]
## Software versions

* **OS**: e.g. Mac OSX / liux alpine (Ci)
* **Consumer Pact library**: latest
* **Provider Pact library**: latest
* **Node Version**: `node 10--version`

## Expected behaviour

for the test to work

## Actual behaviour

 No matching interaction found for GET /api/translations/en

see the test below

<img width="1056" alt="Screen Shot 2019-05-31 at 12 10 38" src="https://user-images.githubusercontent.com/12037104/58702343-76569280-839d-11e9-864f-e61099b5c4d0.png">

## Steps to reproduce

see screenshot for test

```
export function fetchTranslationsApi(languageCode) {
    return get('http://localhost:9090/api/translations/en');
}
```
## Relevant log files
 [2019-05-31T12:03:58.040534 #92720]  INFO -- : Registered expected interaction GET /api/translations/en
D, [2019-05-31T12:03:58.040771 #92720] DEBUG -- : {
  "description": "a request to translations service",
  "providerState": "i have a list of translations",
  "request": {
    "method": "GET",
    "path": "/api/translations/en"
  },
  "response": {
    "status": 200,
    "headers": {
    },
    "body": {
      "login.fb": {
        "json_class": "Pact::SomethingLike",
        "contents": "FB"
      },
      "login.google": {
        "json_class": "Pact::SomethingLike",
        "contents": "Login with Google"
      },
      "desc": {
        "json_class": "Pact::SomethingLike",
        "contents": "Description"
      }
    }
  }
}
W, [2019-05-31T12:03:58.059136 #92720]  WARN -- : Verifying - actual interactions do not match expected interactions. 
Missing requests:
	GET /api/translations/en

W, [2019-05-31T12:03:58.059182 #92720]  WARN -- : Missing requests:
	GET /api/translations/en

I, [2019-05-31T12:03:58.051224 #91009]  INFO -- : Received request GET /api/translations/en
D, [2019-05-31T12:03:58.051544 #91009] DEBUG -- : {
  "path": "/api/translations/en",
  "query": "",
  "method": "get",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "User-Agent": "axios/0.18.0",
    "Host": "localhost:9090",
    "Connection": "close",
    "Version": "HTTP/1.1"
  }
}
E, [2019-05-31T12:03:58.051656 #91009] ERROR -- : No matching interaction found for GET /api/translations/en
E, [2019-05-31T12:03:58.051684 #91009] ERROR -- : Interaction diffs for that route:

**Comment by mefellows** [comment]
Can you please provide a reproducable build that demonstrates this issue? There is an e2e example in the test folder of the repository - if you can make it behave the way you describe I'll mark this as a bug.

Looking at the logs, for whatever reason, your `verify()` call is happening before the actual GET request is being made. I can't quite see from the  screenshot (it LGTM) but I'm guessing there is something incorrect about the sequencing of the test itself.

**Comment by L0wry** [comment]
sorted it!

Been some very odd changes from some developers changing api routes
thanks for your help!
