### ISSUE TITLE
E2E Vagrantfile setup fails on `npm run compile`

### ISSUE THREAD

**Issue by davsucks** [pact-foundation/pact-js#315]
## Software versions

* **OS**: Mac OSX 10.13.6
* **Vagrant Version**: 2.2.4
* **Virtualbox**: 6.0.8 r130520

## Expected behaviour

I can run through the steps in the e2e readme:

    vagrant up
    vagrant ssh
    cd /vagrant
    npm i
    npm run compile
    cd examples/e2e
    npm i
    npm run test:consumer
    npm run test:provider

## Actual behaviour

`npm run compile` fails with this output:

    vagrant@jessie:/vagrant$ npm run compile
    
    > @pact-foundation/pact@8.2.6 compile /vagrant
    > rimraf dist && tsc
    
    module.js:478
        throw err;
        ^
    
    Error: Cannot find module './'
        at Function.Module._resolveFilename (module.js:476:15)
        at Function.Module._load (module.js:424:25)
        at Module.require (module.js:504:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/vagrant/node_modules/.bin/rimraf:3:14)
        at Module._compile (module.js:577:32)
        at Object.Module._extensions..js (module.js:586:10)
        at Module.load (module.js:494:32)
        at tryModuleLoad (module.js:453:12)
        at Function.Module._load (module.js:445:3)
    
    npm ERR! Linux 3.16.0-9-amd64
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
    npm ERR! node v6.17.1
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE
    npm ERR! @pact-foundation/pact@8.2.6 compile: `rimraf dist && tsc`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @pact-foundation/pact@8.2.6 compile script 'rimraf dist && tsc'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the @pact-foundation/pact package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     rimraf dist && tsc
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs @pact-foundation/pact
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls @pact-foundation/pact
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /vagrant/npm-debug.log
    vagrant@jessie:/vagrant$ node -v
    v6.17.1
    vagrant@jessie:/vagrant$ npm -v
    3.10.10

## Steps to reproduce

* Clone Repo
* Install Vagrant 2.2.4
* Install Virtualbox 6.0.8 r130520
* `vagrant up`
* `vagrant ssh`
* `cd /vagrant`
* `npm i`
* `npm run compile`

**Comment by mefellows** [comment]
Thanks, to be fair it's been a while since I've run this and it's not tested as part of our builds - so I'm not surprised it's stopped working. I'm tempted to get rid of it, but that fact that you used it is interesting - can you help me justify why I shouldn't just remove it? :)

**Comment by mefellows** [comment]
Just noting that #318 might actually simplify this.
