### ISSUE TITLE
Synchronisation between multiple test cases

### ISSUE THREAD

**Issue by puzan** [pact-foundation/pact-js#33]
Hello! I have faced with synchronisation issue between test cases.

pact-js: 2.2.1
jest: 19.0.2

Gist with examples: https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0

Based on test in examples/jest I have added just other test case with empty response (see [bad.spec.js](https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0#file-bad-spec-js-L60)). Sometimes tests are passed, but sometime they are failed with following [log](https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0#file-failed-jest-log). After short investigation I have found that `removeInteractions` function inside `provider.verify` can be called after start of the next test case. We can see it in [mock server logs](https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0#file-failed-mockserver-integration-log-L50-L71): register interaction for "empty" test case before clear interactions of the first test case.

I rewrote verification part with [following code](https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0#file-passed-spec-js-L57-L59) to wait interactions clear between test cases:

```js
        // verify with Pact, and reset expectations
        it('successfully verifies', done => provider.verify()
           .then(provider.removeInteractions)
           .then(done))
```

With this code all tests are passed always. But in this case there is [double interactions clear](https://gist.github.com/puzan/2d7873b89a8227477fcb744e7ef36bb0#file-passed-mockserver-integration-log-L50-L51).

Is there any other way to avoid issue with test synchronisation? Do you see the same issue?

What do you think about rewriting `verify` function with following way (like it was before 381bf9d938):

```js
    verify: () => {
      return mockService.verify()
        .then(mockService.removeInteractions)     // return promise in then
        .catch(e => {
          // Properly format the error
          console.error('')
          console.error(clc.red('Pact verification failed!'))
          console.error(clc.red(e))

          throw new Error('Pact verification failed - expected interactions did not match actual.')
        })
    },
```

As far as I understand (I'm mostly backend developer) other "thens" should wait execution of `mockService.removeInteractions` in this case.

**Comment by mefellows** [comment]
Hi @puzan, thanks for this. It seems that commit may have introduced a regression (as you say, it executes the function in the promise chain but doesn't wait for it to return).

This _could_ be the cause of your problems, I'll look into this.

As for the "double interactions clear" - that's nothing to be worried about, so if that's enough to keep you moving I wouldn't be concerned (although I suspect it's only working because it's slowing down the execution of promises and therefore the race condition is much less likely to occur).

**Comment by dgreene1** [comment]
I think our team might be experiencing this issue as well. Sorry that I can't provide a jsFiddle, but it looks a lot like the example above ([https://github.com/pact-foundation/pact-js/issues/33#issue-217082490](https://github.com/pact-foundation/pact-js/issues/33#issue-217082490))
