### ISSUE TITLE
Docs incorrectly claim that pactBrokerToken is a VerifierOption

### ISSUE THREAD

**Issue by JVMartin** [pact-foundation/pact-js#334]
The docs incorrectly claim that `pactBrokerToken` is a VerifierOption:
https://github.com/pact-foundation/pact-js/blame/efc91147915e1d48c0822ccfc32fdc43061cec59/README.md#L287

No such option appears in the code:
https://github.com/pact-foundation/pact-js/blob/efc91147915e1d48c0822ccfc32fdc43061cec59/src/dsl/verifier.ts#L29-L52

This appears to be a code issue rather than a doc issue, because the option should exist.

I would work on a PR, but I'm afraid I don't have time at the moment. :(

**Comment by JVMartin** [comment]
Our team is using PactFlow, and we have no way of verifying pacts... we cannot user username / password, as PactFlow only supports using tokens.

Seems like PactFlow was released prematurely. :/

**Comment by JVMartin** [comment]
Wait... why are we duplicating this `VerifierOptions` interface that already exists in `pact-node`?
https://github.com/pact-foundation/pact-node/blob/b1355bde3f24588bcae8fa199a4561f114d9132b/src/verifier.ts#L173-L191

**Comment by mefellows** [comment]
Thanks and apologies, this indeed does appear to be an issue. See the comment in https://github.com/pact-foundation/pact-js/blob/efc91147915e1d48c0822ccfc32fdc43061cec59/src/dsl/verifier.ts#L26 for why we have tobdupe. It's a TS language restriction.

I'll get a release out to address this shortly.

**Comment by JVMartin** [comment]
Awesome, no worries, thanks much! :smile:

**Comment by mefellows** [comment]
You're welcome, thanks for reporting. v`9.0.1` went out this morning with the new flag. I've tested I can verify against a Pactflow test account this morning - do let me know if you have any issues.
