### ISSUE TITLE
consumerVersionTag type doesn't match pact-node

### ISSUE THREAD

**Issue by kuangp** [pact-foundation/pact-js#341]
The type definition lists `consumerVersionTag` as a `string` type in pactjs:
https://github.com/pact-foundation/pact-js/blob/master/src/dsl/verifier.ts#L41

however in pact-node it is a `string | string[]`: 
https://github.com/pact-foundation/pact-node/blob/master/src/verifier.ts#L211

I believe the pact-node definition is the correct type since this was meant to replace the depcrecated `tags` option?

**Comment by TimothyJones** [comment]
Good catch, thanks for reporting.

I'm working on a change for pact-node that will remove the need for pact-js to duplicate the types, hopefully fixing this class of issues forever.

In the meantime, I'll correct the definition in pact-js.

**Comment by TimothyJones** [comment]
Released 9.1.0, which includes this fix.
