### ISSUE TITLE
Unhandled promise rejection - unable to connect to .../interactions

### ISSUE THREAD

**Issue by jaccagent** [pact-foundation/pact-js#343]
Hi team,

I am new to PACT so I may be missing something simple. We have an Angular app that I have just installed pact for through npm.

I have a basic test which looks like this...

`import { TestBed } from '@angular/core/testing';
import { HttpClientModule } from '@angular/common/http';
import { PactWeb, Matchers } from '@pact-foundation/pact/pact-web';
import { ApplicationsApiService } from 'src/app/applications/services/applications-api.service';
import { CreateApplicationModel } from 'src/app/applications/models/create-application-model';
import { ApiResources } from 'src/app/_shared/models/api-resources';
const path = require('path');

describe('createApplication', () => {
  // tslint:disable-next-line: no-var-keyword
  var provider;

  beforeAll(done => {
    provider = new PactWeb({
      consumer: 'ui',
      provider: 'userservice',
      port: 3000,
      host: '127.0.0.1',
      log: path.resolve(process.cwd(), 'logs', 'pact.log'),
      dir: path.resolve(process.cwd(), 'pacts'),
      spec: 2
    });

    // required for slower CI environments
    setTimeout(done, 2000);

    // Required if run with `singleRun: false`
    provider.removeInteractions();
  });

  afterAll(done => {
    provider.finalize().then(done, done.fail);
  });

  describe('getApplicationRequest', () => {
    const cpn = '1234';

    const expectedApplication: CreateApplicationModel = {...};

    beforeAll(done => {
      provider
        .addInteraction({
          state: 'server provides an application',
          uponReceiving: 'a request to view an application',
          withRequest: {
            method: 'GET',
            path: ApiResources.createApplication(cpn)
          },
          willRespondWith: {
            status: 200,
            body: Matchers.somethingLike(expectedApplication)
          }
        })
        .then(done, error => done.fail(error));
    });

    it('should retrieve an application', done => {
      const apiService = TestBed.get(ApplicationsApiService);

      apiService.getApplicationRequest(cpn).subscribe(
        response => {
          expect(response).toEqual(expectedApplication);
          done();
        },
        error => {
          done.fail(error);
        }
      );
    });
  });
});`

Here is my karma.conf.js file...

`module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage/vpa-management'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['ChromeHeadless'],
    singleRun: false,
    restartOnFileChange: true,
    pact: [
      {
        cors: true,
        port: 3000,
        consumer: 'ui',
        provider: 'api',
        dir: 'pacts',
        spec: 2
      }
    ],
    proxies: {
      '/api/': '/http://127.0.0.1:3000/api/'
    }
  });
};`

After setting these up I run npm test 

` 12% building 20/21 modules 1 active ...loader.js??ref--15-3!C:\Dev\Git\vpa-management\src\styles.scss12 08 2019 16:50:58.968:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
12 08 2019 16:50:58.973:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
 12% building 22/23 modules 1 active ...loader.js??ref--15-3!C:\Dev\Git\vpa-management\src\styles.scss12 08 2019 16:50:59.109:INFO [launcher]: Starting browser ChromeHeadless
12 08 2019 16:51:06.695:INFO [HeadlessChrome 76.0.3809 (Windows 10.0.0)]: Connected on socket bPz7dR4aj4DSuUMsAAAA with id 21247606
WARN: 'Passing in consumer/provider to PactWeb is deprecated,
        and will be removed in the next major version'
HeadlessChrome 76.0.3809 (Windows 10.0.0): Executed 4 of 7 SUCCESS (0 secs / 0.055 secs)
WARN: 'Passing in consumer/provider to PactWeb is deprecated,
INFO: 'Setting up Pact using mock service on port: "3000"'
HeadlessChrome 76.0.3809 (Windows 10.0.0): Executed 4 of 7 SUCCESS (0 secs / 0.055 secs)
ERROR: 'Unhandled Promise rejection:', 'Unable to connect to "http://127.0.0.1:3000/interactions"', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', PopsicleError{cause: undefined, code: 'EUNAVAILABLE', popsicle: Request{Url: Url{protocol: ..., slashes: ..., auth: ..., host: ..., port: ..., hostname: ..., hash: ..., search: ..., query: ..., pathname: ..., path: ..., href: ...}, rawHeaders: [..., ..., ..., ..., ..., ...], middleware: [..., ...], opened: true, aborted: false, uploaded: 1, downloaded: 0, timeout: 10000, method: 'DELETE', body: null, events: Object{abort: ...}, transport: Object{use: ..., abort: ..., open: ...}, _promise: ZoneAwarePromise{__zone_symbol__state: ..., __zone_symbol__value: ...}, _raw: XMLHttpRequest{__zone_symbol__ON_PROPERTYload: ..., __zone_symbol__loadfalse: ..., __zone_symbol__ON_PROPERTYabort: ..., __zone_symbol__abortfalse: ..., __zone_symbol__ON_PROPERTYerror: ..., __zone_symbol__errorfalse: ..., __zone_symbol__ON_PROPERTYprogress: ..., __zone_symbol__progressfalse: ..., __zone_symbol__xhrSync: ..., __zone_symbol__xhrURL: ..., __zone_symbol__xhrScheduled: ..., __zone_symbol__xhrErrorBeforeScheduled: ..., __zone_symbol__xhrListener: ..., __zone_symbol__xhrTask: ...}}}, 'PopsicleError: Unable to connect to "http://127.0.0.1:3000/interactions"
    at Request.push../node_modules/popsicle/dist/request.js.Request.error (http://localhost:9876/_karma_webpack_/node_modules/popsicle/dist/request.js:41:1)
    at XMLHttpRequest.xhr.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:9876/_karma_webpack_/node_modules/popsicle/dist/browser.js:38:1)
    at XMLHttpRequest.wrapFn (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:1191:1)
    at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:391:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:339:1)
    at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:390:1)
    at Zone.runTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:168:1)
    at ZoneTask.invokeTask [as invoke] (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:465:1)
    at invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:1603:1)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:1629:1)'
HeadlessChrome 76.0.3809 (Windows 10.0.0): Executed 4 of 7 SUCCESS (0 secs / 0.055 secs)
ERROR: 'Unhandled Promise rejection:', 'Unable to connect to "http://127.0.0.1:3000/interactions"', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', PopsicleError{cause: undefined, code: 'EUNAVAILABLE', popsicle: Request{Url: Url{protocol: ..., slashes: ..., auth: ..., host: ..., port: ..., hostname: ..., hash: ..., search: ..., query: ..., pathname: ..., path: ..., href: ...}, rawHeaders: [..., ..., ..., ..., ..., ...], middleware: [..., ...], opened: true, aborted: false, uploaded: 1, downloaded: 0, timeout: 10000, method: 'DELETE', body: null, events: Object{abort: ...}, transport: Object{use: ..., abort: ..., open: ...}, _promise: ZoneAwarePromise{__zone_symbol__state: ..., __zone_symbol__value: ...}, _raw: XMLHttpRequest{__zone_symbol__ON_PROPERTYload: ..., __zone_symbol__loadfalse: ..., __zone_symbol__ON_PROPERTYabort: ..., __zone_symbol__abortfalse: ..., __zone_symbol__ON_PROPERTYerror: ..., __zone_symbol__errorfalse: ..., __zone_symbol__ON_PROPERTYprogress: ..., __zone_symbol__progressfalse: ..., __zone_symbol__xhrSync: ..., __zone_symbol__xhrURL: ..., __zone_symbol__xhrScheduled: ..., __zone_symbol__xhrErrorBeforeScheduled: ..., __zone_symbol__xhrListener: ..., __zone_symbol__xhrTask: ...}}}, 'PopsicleError: Unable to connect to "http://127.0.0.1:3000/interactions"`

Unfortunately I run into this error upon attempting to startup the tests.

**Comment by mefellows** [comment]
Sorry, it's very hard  to see what's going on with the formatting - could you please fix it up and/or provide an example we can run to demonstrate the issue?

The error suggests that it cannot talk to the remote URL (in this case, the mock service running on port 3000 on your local machine). It's possible that  you need to wait a little longer (longer `setTimeout` or create your own little wait handler before executing your  Karma tests - the server might still be starting up so it can't communicate just yet.

**Comment by mefellows** [comment]
Did you sort it out @jaccagent ?
