### ISSUE TITLE
Documentation example mispell?

### ISSUE THREAD

**Issue by basickarl** [pact-foundation/pact-js#362]
https://github.com/pact-foundation/pact-js#provider-producer

I think this is a misspell in the documentation down by the example. It states `new MessageProviderPact` which I think is incorrect. Is it supposed to be `new Pact` or `new MessageProvider`. Or perhaps `MessageProvider` is supposed to be `MessageProviderPact` at the import statement. I'll do a pull request to fix it, just tell me what it is supposed to be.

**Comment by TimothyJones** [comment]
Good catch. I think it's supposed to be `MessageProviderPact` at the import, but it might be best to confirm this by running the example if you have time.

**Comment by basickarl** [comment]
@TimothyJones Don't fear, the flying unicorn is on it.

**Comment by basickarl** [comment]
Coming back to this `new MessageProviderPact` is now working. Don't know if it was an update or my code, but the documentation is correct now.
