### ISSUE TITLE
willRespondWith headers are filtered

### ISSUE THREAD

**Issue by inkhsutesou** [pact-foundation/pact-js#368]
Copy of: https://github.com/pact-foundation/pact-node/issues/185#issue-501182475
Posting here incase this is a pact-js issue

## Software versions

-   **MAC OS**
-   **8.1.2/74293**
-   **v10.12.0**

## Expected behaviour
```
willRespondWith: {
  status: 503,
  headers: {
    'Retry-After': '1000',
    'Content-Type': 'application/json'
  }
}
```
should have an `error.response.headers` with ..

```
{
    'Retry-After': '1000',
    'Content-Type': 'application/json'
}
```

## Actual behaviour
Returns with:
```
{
    'Content-Type': 'application/json'
}
```

Can anyone tell me why the headers would be filtering ?  I have tried this across several teams at my company and they all run into this same issue.  Checking to see if this is an issue with pact-node.  Thank you.

**Comment by mefellows** [comment]
I have been able to demonstrate this is not the case.

See this branch (`repro/issue-368`) and specifically this test assertion: https://github.com/pact-foundation/pact-js/blob/repro/issue-368/examples/mocha/test/get-dogs.spec.js#L70.

Closing, unless you can provide a reproducable example.

**Comment by inkhsutesou** [comment]
Thank you for your test.  Does it produce the same when the status is 503 and triggers an error instead of using the 200 response ?

**Comment by mefellows** [comment]
I've just updated the example to return a `503`. I'm using axios in the example, which by default will reject the promise if a response code > `400` is returned. I'm catching the exception, extracting the response and sending it back. You can see that the header comes along for the ride.

FWIW you can also use the pact stub server that is bundled with Pact (`./node_modules/.bin/pact-stub-service <path to pact file>) to test outside of your JS environment. Just modify your pact file as required, run the server and then you can cURL it or whatever.

**Comment by inkhsutesou** [comment]
Thank you, I will try that : >
