### ISSUE TITLE
No indication of port being in use during `provider.setup()` call?

### ISSUE THREAD

**Issue by screamish** [pact-foundation/pact-js#37]
I just spent a good while being a doofus getting started with pact-js in a new project (been a PACT user for a fair while) all because the port I chose for my provider (8081) was in use. Yes, my silly choice of port (if only I'd thought to run an `lsof` hours ago and save myself much wasted time), but I'm just wondering why this didn't result in error messages back from `provider.setup()` or even anything in the debug level logs to console?

**Comment by mefellows** [comment]
Thanks @screamish - seems like a nice UX addition!

**Comment by mefellows** [comment]
Latest build released to https://www.npmjs.com/package/pact (`v2.3.2`).

For future me, I wasn't able to repro the Karma issue in the builds until I ran `npm run dist`. This was the cause of the multiple `git push -f`. 

Thanks @screamish  :)
