### ISSUE TITLE
Can't install pact in node v12 ?

### ISSUE THREAD

**Issue by eauc** [pact-foundation/pact-js#371]
Hello, looks like I can't install pact in node v12 this morning... did I miss something ?

## Software versions

* **OS**: Linux Debian 9
* **Node Version**: node v12.9.1 (npm v6.10.2)

## Actual behaviour

```
npm i -S @pact-foundation/pact@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm ERR! 404 
npm ERR! 404  'https-proxy-agent-snyk-fork@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'proxy-agent'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## Steps to reproduce

```
mkdir test-p
cd test-p
npm init -y
npm i -S @pact-foundation/pact@latest
```
[2019-10-04T08_04_04_576Z-debug.log](https://github.com/pact-foundation/pact-js/files/3689569/2019-10-04T08_04_04_576Z-debug.log)

**Comment by mefellows** [comment]
Thanks, just reproduced it myself. Weird, that dependency isn't listed, but the dependency without the `snyk-fork` suffix is, funnily enough, a Snyk dependency. 

Google seems unhelpful here.

**Comment by PeterMK85** [comment]
faced a similar issue:

```
yarn add @pact-foundation/pact@latest -D
yarn add v1.17.3
[1/4] Resolving packages...
error "proxy-agent-3.1.0.tgz": Tarball is not in network and can not be located in cache (["/home/petermk85/dev/web/billing-frontend/proxy-agent-3.1.0.tgz","/home/petermk85/.cache/yarn/v4/.tmp/1cb65d53db120924735197f89834781e/.yarn-tarball.tgz"])
```
Node: 12.7.0

**Comment by mefellows** [comment]
So, it looks to be working today. I'm wondering if Snyk has released something. I wasn't getting this in my `node_modules` search the other day. I think Snyk has a vendored dependency somewhere (it's not visible on npm):

<img width="1438" alt="screenshot" src="https://user-images.githubusercontent.com/53900/66314025-1bdacd80-e95f-11e9-96d5-1ec9407777fd.png">

**Comment by abotalov** [comment]
Yeah, it was an issue with snyk - https://github.com/snyk/snyk/issues/796
Pact install works for me now.

**Comment by eauc** [comment]
Ok, so it was just my karma, first time I'm trying pact after thinking about it for one year :laughing: 

Thank you for your time anyway !

**Comment by mefellows** [comment]
Well, better late than never - thanks for trying us out and don't be afraid to join us at slack.pact.io
