### ISSUE TITLE
Provider state parameters not implemented

### ISSUE THREAD

**Issue by kneczaj** [pact-foundation/pact-js#372]
## Software versions

* **OS**: Windows 10
* **Consumer Pact library**:  @pact-foundation/pact@9.1.1
* **Provider Pact library**: does not matter
* **Node Version**: v10.15.3

## Expected behaviour

The state parameters can be passed, like at pact 3 specification
https://github.com/pact-foundation/pact-specification/tree/version-3#allow-multiple-provider-states-with-parameters

## Actual behaviour

A provider state can be defined by string only.

## Steps to reproduce

See the interface used to define an interaction that it can only receive a string for provider state
https://github.com/pact-foundation/pact-js/blob/3d66117c5b3ba0f2f15c9b29f5651c4eab1217cb/src/dsl/interaction.ts#L28

## Relevant log files

none

I am in a project which used to be consisted of Java services only which have defined many providers with parameters. With pact-js I cannot reuse these providers.

**Comment by mefellows** [comment]
Thanks. We know this is lacking as it is a v3 feature. I'm going to create a separate issue later tonight to track the v3 implementation, but work is already underway (see the v3 branch).

**Comment by kneczaj** [comment]
@mefellows thanks a lot!

**Comment by straurob** [comment]
Is there any way to work around this with the v2 specification?

Example:
The consumer test registers a new user using her email address `foo@bar.com`. The provider state setup function must execute a query to make sure that the email address does not exist yet.

**Comment by bethesque** [comment]
The better way to handle that solution is that the datasources should all be cleared at the start of the provider state set up call. Then you would know that it does not exist.

**Comment by mefellows** [comment]
As Beth said. But also, you could have two separate tests and states

e.g.

* `"... when user foo@bar.com exists"`
* `"... when user foo@bar.com does not exist"`

You don't need a state parameter to do this.

**Comment by garry-jeromson** [comment]
Are there any plans to make the library compatible with v3.0 state parameters? When you only have one variable, adding two tests is fine, but with several variables you end up needing N-factorial state resolvers on the provider side, which is really a pain.

For example, we have a multi-tenant application, and using [pactman](https://pypi.org/project/pactman/) we can structure our Python consumer tests to have states like:

```py
...
"providerStates": [
        {
          "name": "a tenant exists with the given tenant ID",
          "params": {
            "tenant_id": 1
          }
        },
        {
          "name": "a doctor with the given ID exists",
          "params": {
            "doctor_id": 123,
            "tenant_id": 1
          }
        }
      ],
...
```

We can't yet do this for our JavaScript/TypeScript clients without creating clunky-as-hell states like _Given that a doctor with ID 123 exists on tenant with ID 1 and his favourite colour is turqoise_, etc. This effectively means writing a new state resolver on the provider for every single test.

**Comment by garry-jeromson** [comment]
OK, just stumbled on this: https://github.com/pact-foundation/pact-js#pact-js-v3 - looks promising.

**Comment by mefellows** [comment]
Yes, that should do the trick for you Garry!

Please also note the new package import too - we'd love your feedback on
this too.

**Comment by garry-jeromson** [comment]
First impression is: it's gonna be a tricky migration, at least for our setup (consumer tests only, Jest + TypeScript). The interface for the `PactV3` class is very different to the `Pact` class (from [here](https://github.com/pact-foundation/pact-js/blob/dd4560bbb2ed1c64a1fd3263a16bd42c5b53dbcd/src/httpPact.ts#L22)) so it's not gonna be as simple as just tweaking the state parameters, and will require a bit of a rejig of our whole setup. More digging required. 🧑‍💻

**Comment by mefellows** [comment]
Thanks @garry-jeromson. We're looking at bringing that more inline with the current type definitions, but there is going to be a lag there.

In the meantime, I believe #407 might actually work - it's just not tested and the author has gone stale. It could also potentially be added to the existing interface and _might_ work (again, needs testing, but the underlying engine does actually support multiple states for message pact, so it's possible the http interface already supports it, but it's not exposed to the DSL itself).

cc: @TimothyJones

**Comment by mefellows** [comment]
10.x.x now supports this.

**Comment by adamwitko** [comment]
@mefellows on reading the V3 spec, I just wanted to check, is provider state parameters only supported for message based pact testing and not the standard verifications?

**Comment by mefellows** [comment]
It should be supported for all interaction types.

**Comment by adamwitko** [comment]
> It should be supported for all interaction types.

I checked the merged PRs above and state params have been added for the message provider and not others. The spec also seems to focus on message pacts when talking about state params so I'm a little confused :D 

I couldn't spot any state param options for 10.x.x.

**Comment by adamwitko** [comment]
Ok thanks @mefellows. I'll go and figure out if I'm a fool and I somehow missed it 👀

**Comment by mefellows** [comment]
haha no worries!
