### ISSUE TITLE
Dependency on outdated graphql package

### ISSUE THREAD

**Issue by ertrzyiks** [pact-foundation/pact-js#374]
This project depends on graphql 0.13.2 which is outdated. The graphql-tag allows 14.0.0, so it should be fine to update.

## Expected behaviour

package.json dependency on
```
 "graphql": "^14.0.0",
```

## Actual behaviour

package.json dependency on
```
 "graphql": "^0.13.2",
```

**Comment by TimothyJones** [comment]
Fixed by #375
