### ISSUE TITLE
A matcher for string or `null`

### ISSUE THREAD

**Issue by zettadam** [pact-foundation/pact-js#393]
The body of a service I want to cover with Pact tests contains an array of objects containing properties that could be a either `string` or `null`. Pact doesn't seem to support this case, but I think it is fairly common for JSON payloads to return `null` in cases where there is no data for a specific field.

How would Pact allow me to express this with a matcher? `term` with regex matcher can't cover this case. `like` accepts a single argument. I've seen a couple of issues related to this but no conclusive answer or documentation.

- [#323] **Feature request – create matchers for all JS data types**
- [#51] **Matcher of a type or null**

NOTE: I'm attaching a screenshot to (perhaps) illustrate this better.

<img width="1440" alt="pact-js_matcher-string-or-null" src="https://user-images.githubusercontent.com/516382/68437203-e6a3e400-0185-11ea-9638-589b20adfe68.png">

**Comment by mefellows** [comment]
Have you read https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes?

**Comment by TimothyJones** [comment]
To match null, just explicitly put `null` in the request.

Usually, it's best to have two tests for optional cases - one where the string is present, and one where the field is null. [This stackoverflow question](https://stackoverflow.com/a/58444156/790070) has some discussion that you might find useful.

**Comment by mefellows** [comment]
It's not something we're currently willing to implement due the the article above  unless I've missed something, we'll close this. Thanks for the detailed report, though.
