### ISSUE TITLE
Support tagging provider versions when publishing verification results

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#394]
The option to the underlying pact-provider-verifier command is `--provider-version-tag TAG` and this can be repeated multiple times. See https://github.com/pact-foundation/pact-provider-verifier#usage

**Comment by MrRhodes** [comment]
Wow, quick turn around.... thank you... I'm impressed!

**Comment by mefellows** [comment]
Thanks! Give it a few minutes though, the change has been committed but is in the process of a release (`v9.3.0"`).

**Comment by MrRhodes** [comment]
I've just been trying this and I'm getting this error:

```
    Error reading file from --provider-version-tag

    No such file or directory @ rb_sysopen - --provider-version-tag 
```

.. im not sure if this is related to this new feature?

**Comment by mefellows** [comment]
Hmm, so it looks like `--provider-app-version` isn't available in the current binary supplied to Pact Node. Let me find out why...

<img width="1440" alt="Screen Shot 2019-11-09 at 9 15 32 am" src="https://user-images.githubusercontent.com/53900/68514321-828e3680-02d1-11ea-9caa-ae68dd3d6651.png">

**Comment by mefellows** [comment]
OK so it looks like the [standalone](https://github.com/pact-foundation/pact-ruby-standalone/) package needs updating as it doesn't contain this flag. I'll update that, and then update pact-node to include that in the latest binary. I have a few things on this morning, but will sort it out when I'm back a little later today.

**Comment by MrRhodes** [comment]
> Hmm, so it looks like `--provider-app-version` isn't available in the current binary supplied to Pact Node.

I assume you mean `--provider-version-tag` ?

**Comment by mefellows** [comment]
Yes that, I originally thought it was a documentation error and copied the
wrong tag. I didn't update the comment after it seems

**Comment by mefellows** [comment]
Just an FYI, this release is held up a little as we investigate a minor difference in beaviour in the latest verifier. See https://github.com/pact-foundation/pact-provider-verifier/issues/42 for detail.

**Comment by mefellows** [comment]
Ok take 2, the latest release should have this fix. Apologies for the delay.
