### ISSUE TITLE
Remove the redundant property 'providerBaseUrl' in the publish.js file

### ISSUE THREAD

**Issue by LayMui-Toh** [pact-foundation/pact-js#400]
## Software versions

NA

## Expected behaviour

Please remove the property 
  providerBaseUrl: "http://localhost:8082",
from the publish.js in the jest example
to avoid confusion to reader

## Actual behaviour

NA

## Steps to reproduce

NA

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by TimothyJones** [comment]
Thanks for the report! Fixed in b4780ef
