### ISSUE TITLE
Dealing with path and headers are different because of interceptor running in a gateway

### ISSUE THREAD

**Issue by yonarad** [pact-foundation/pact-js#401]
Hi,

I trying to use Pact to verify the rest contract between UI and back-end.
the back-end located behind gateway that re-route the request to the correct service according to the prefix and add custom headers.

for example: from the UI I use path: /prefix/v1/policy
the prefix is trimmed in the gateway, and the actual path in the provider is: /v1/policy

So, the contract can't be the same.

If I change the path on "addInteraction" in the consumer to be compatible with the producer, I get error in consumer side: 
actual interactions do not match expected interactions. 
Missing requests:
	GET /v1/policies
Unexpected requests:
	GET /prefix/v1/policies

If I creating the contract according UI path(/prefix/v1/policies), I failed on the Provider:
"status": 404,
+  "error": "Not Found",
+  "message": "No message available",
+  "path": "/prefix/v1/policies"

Do you have idea for me how to work around this problem?

Thanks!

**Comment by TimothyJones** [comment]
I would view this either as a contract between:

* The UI, and the (gateway + back-end)

or as two contracts:

* The UI, and the Gateway
* The Gateway and the back-end

**Comment by TimothyJones** [comment]
Or, if the difference is just in the path, in pact test mode, can you stand up your API with a prefix?

**Comment by yonarad** [comment]
Thanks about the ideas.
Finally, I injected special parameter via angular environment file.
This parameter configure the API as the service expected (with adjusted path and the expected header) after the gateway manipulation only when I created the consumer contract.

Thanks

**Comment by mefellows** [comment]
Ah, I didn't hit send on my suggestions. But FWIW this is exactly what I would have done 👌 .

It's not worth writing a contract to the gateway if it's just pass through (see https://docs.pact.io/faq#why-pact-may-not-be-the-best-tool-for-testing-pass-through-apis).
