### ISSUE TITLE
Angular httpClient requests that include "withCredentials: true" cannot be used with cors: true

### ISSUE THREAD

**Issue by vandemark** [pact-foundation/pact-js#409]
* **OS**: 
Windows 10
* **Consumer Pact library**: 
@pact-foundation/pact: ^9.6.0
@pact-foundation/pact-node: ^10.2.2
* **Node Version**: 
10.14.0

## Description

I have a PACT test set up to call an angular httpClient post request that has { withCredentials: true }. This requires the server to respond with a header 'Access-Control-Allow-Credentials': 'true'. Setting cors:true does not add this header so I get the exception below, but if I set cors:false and set up the headers to be returned manually I then have to verify/create them on our provider side test, which is not ideal, because the provider were verifying against is not technically responsible for setting those cors headers.

## Expected behavior

Pact consumer test passes 

## Actual behavior

"Error: Credentials forbidden" is being thrown on httpRequest to the mock server because setting cors:true does not add an "access-control-allow-credentials" header on the mock server response   
Code in jest causing test to fail:                                                                                                                                   
![image](https://user-images.githubusercontent.com/19509431/74470603-de3a0400-4e6c-11ea-96c6-d4488a24155e.png)
Running the pact:
![image](https://user-images.githubusercontent.com/19509431/74473168-20fddb00-4e71-11ea-8812-8d82399f11fc.png)

I am using jest.
Could the cors:true setting (or a new setting) make the mock server pass back a 'Access-Control-Allow-Credentials': 'true' header? Or, (I know its not part of pact.js and is a separate request) is there a way I can change the jsdom settings to not throw this exception?  Thanks.

**Comment by bethesque** [comment]
Can you join the conversation in the issue referenced ^^ @vandemark

**Comment by TimothyJones** [comment]
Thanks to @bethesque , this is fixed in `pact-node` v10.6.0, which will be released in the next few minutes.
