### ISSUE TITLE
how do i use pact with typescript? 

### ISSUE THREAD

**Issue by Gavin-TW** [pact-foundation/pact-js#410]
## Software versions

* **OS**: e.g. Mac OSX 10.15.3
* **Node Version**: `v13.6.0`

i clone the pact-js in local, and run npm install ,then cd example/typescript ,no readme.md i can see,so i run npm install  in this dir,and npm t ,then ,blocked me ,like this , so , how do i use pact with ts...?

![image](https://user-images.githubusercontent.com/60416455/74640063-f3cf6680-51a9-11ea-9610-cc2df25aad64.png)

**Comment by mefellows** [comment]
This is what we do for our builds https://github.com/pact-foundation/pact-js/blob/master/package.json#L28

So it should work. Perhaps there is a local issues, try following the debug instructions at  https://github.com/pact-foundation/pact-js/#debugging and see what you can find.

**Comment by Gavin-TW** [comment]
thanks for commente, i rm -rf the pact-js and clone again,then cd example/typescript  run 'npm it', it work,appreciate it ,maybe the reason is network、、、
