### ISSUE TITLE
NPM Audit failure on third party dependency

### ISSUE THREAD

**Issue by Sami-5** [pact-foundation/pact-js#411]
## Software versions

* **OS**: Mac OS Catalina 10.15.3
* **Consumer Pact library**: Pact JS v9.7.0
* **Node Version**: v12.13.0

## Expected behaviour

To run test suite without triggering npm audit failure

## Actual behaviour

Triggering npm audit failure

## Steps to reproduce

Running my test suite is failing because of an npm audit issue on a dependency of pact. Please see below screenshot:

![Screen Shot 2020-02-28 at 9 46 52 am](https://user-images.githubusercontent.com/32408319/75494033-67297180-5a0f-11ea-9fc4-182e566ad315.png)

**Comment by mohammedalnuaimi** [comment]
getting the same issue here...  @mefellows could you help?

**Comment by mefellows** [comment]
Work is underway. See https://github.com/pact-foundation/pact-node/pull/209
