### ISSUE TITLE
Please expose the --verbose flag for the pact ruby standalone CLI

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#421]
This is available for any command that connects to the broker (pact publish, verify etc). If you search for `--verbose` in https://github.com/pact-foundation/pact-ruby-standalone/releases you'll see the docs.

**Comment by TimothyJones** [comment]
This now is fixed in `pact-node` v10.7.0, currently releasing. I'll close this issue when it's released and the version in pact-js is bumped.

**Comment by TimothyJones** [comment]
Fixed!

**Comment by bethesque** [comment]
Thanks. That'll help debugging some "it doesn't work, waaah!" issues.
