### ISSUE TITLE
pact standalone binary download - self signed cert

### ISSUE THREAD

**Issue by oxlade39** [pact-foundation/pact-js#427]
## Software versions

* **OS**: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

* **Consumer Pact library**: e.g. Pact JS v2.6.0
pactjs 1.82.1
* **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
npm 6.13.4
* **Node Version**: `node --version`
v12.16.1

## Expected behaviour

Downloads standalone binary from custom location honouring the trusted certifactes that are installed in the target OS.

## Actual behaviour
```
Error: Downloading Pact Standalone Binary v1.82.1 for platform linux from https://[redacted]/pact/pact-1.82.1-linux-x86_64.tar.gz
Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error downloading binary from https://[redacted]/pact/pact-1.82.1-linux-x86_64.tar.gz: Error: Error while installing binary: Error: self signed certificate in certificate chain
    at throwError (/home/[redacted]/node_modules/@pact-foundation/pact-node/standalone/install.js:29:11)
    at /home/[redacted]/node_modules/@pact-foundation/pact-node/standalone/install.js:307:16
```

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

install all ssl certs, intermediates and roots on the given target http URL chain into ubuntu trusted certs.

```json
"config": {
    "pact_do_not_track": true,
    "pact_binary_location": "https://[redacted]/pact/"
  }
```

`npm i -S @pact-foundation/pact@latest`

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Thanks for the report.

I think you should be able to fix this by setting a `cafile` in your [npmrc](https://docs.npmjs.com/configuring-npm/npmrc.html) (see https://github.com/pact-foundation/pact-node/blob/master/standalone/install.ts#L157-L164).

Have you tried this? I'll add a note in the docs because it's not obvious.

**Comment by oxlade39** [comment]
Thanks for the reply.

I already have the setting:

```
cat ~/.npmrc 
registry=https://[redacted]/artifactory/api/npm/npm-release
cafile=/etc/ssl/certs/ca-certificates.crt
strict-ssl=true
no_proxy=localhost,127.0.0.1,.[redacted].io,.[redacted].com,.[redacted].net,.[redacted].net
package-lock=true
save-exact=false
proxy=null
https-proxy=null
```

this points to the ubuntu certs. I'm fairly sure the cert is setup in there because when I do a curl to download the file manually, it works fine. If it didn't curl would reject as untrusted.

**Comment by oxlade39** [comment]
@mefellows I've just realised you linked to pact-node, was that intentional? It feels like the postinstall isn't honouring the cafile config.

**Comment by oxlade39** [comment]
I tried playing around locally.
It looks like the line you linked above is wrong. The `cafile` property is used for the location of the pem file. The `request` library expects the content of the file, *not* the file location. 

The below worked for me just hacking around. But obviously won't for the majority of people without the property set.
```javascript
request({
            url: url,
            headers: {
                'User-Agent': 'https://github.com/pact-foundation/pact-node',
            },
            strictSSL: config.read()['strict-ssl'],
            ca: fs.readFileSync(config.read()['cafile']),
        })
```

**Comment by oxlade39** [comment]
Create MR in pact-node
https://github.com/pact-foundation/pact-node/pull/222

**Comment by mefellows** [comment]
Release `10.8.1` going out for Pact Node. It's a patch level release, so next Pact JS install will bring it in (you can obviously npm upgrade your local dependencies as soon as its out).

Thanks for the patch 🙏
