### ISSUE TITLE
Deployment to NPM is under Tarcio's account and not Pact Foundation's

### ISSUE THREAD

**Issue by mboudreau** [pact-foundation/pact-js#43]
Further adding to the confusion of how to find all things Pact, this one is not deployed under the foundation's account and isn't using our naming convention. 

https://www.npmjs.com/package/pact

It should be renamed to @pact-foundation/pact-js and deployed under our account.  This can be done easily enough through API keys on the npm site.

**Comment by mefellows** [comment]
Yeah, the API key has been on the back burner a while. Should be easy.

I'm not entirely convinced about using the "@pact-foundation" prefix, but I can see the value.

I'd like to get some more opinions on this to make certain I'm in the minority.

**Comment by mboudreau** [comment]
Well, npm just released a new organizations feature which we could
amalgamate everything under that account, but we are going to have some
issues with the names colliding with past projects.  Frankly, I don't see
what the deal is with the prefix.  You do it once and you never have to do
it again really.  At the very least, it gives some confidence that the
developer has the right package.
