### ISSUE TITLE
Chore: link @pact-foundation/pact in Appveyor builds

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#441]
Builds that change an interface or have backwards-incompatible changes in them will fail an Appveyor build because they pull in pact from NPM rather than the in-build changes.

See https://ci.appveyor.com/project/pact-foundation/pact-js/builds/32277939 for an example.

We should `npm link @pact-foundation/pact` as we do in `build.sh` on Linux, so that the examples are always tested against the change.

**Comment by mefellows** [comment]
Update: Branch is up and working, except there is an issue with message pact on AppVeyor builds that needs further review.

**Comment by YOU54F** [comment]
no longer using appveyor
