### ISSUE TITLE
Ability to set JSON serialization settings

### ISSUE THREAD

**Issue by benquinteros** [pact-foundation/pact-js#447]
Could we possibly be able to tweak the serialization settings so that a body can match based on the preferred serialization settings of the app, rather than PACT's preferred settings? 

This is implemented in pact-net 

https://github.com/pact-foundation/pact-net/commit/6b07a7c581f17d9395db50e0bf09804cdfc27458

**Comment by mefellows** [comment]
What do you mean by "serialisation" settings - can you please elaborate on the requirements/need?

**Comment by benquinteros** [comment]
I've a nullable array property for a typescript class which pact omits when serializing. The implementation creates an empty array and includes it in the request. Instead of changing the implementation I'd like to provide options for the pact serializer, I know it has been discussed in https://github.com/pact-foundation/pact-js/issues/51 but would like an impl similiar to what has been done in pact-net.

**Comment by mefellows** [comment]
I may be daft, so could you maybe show me exactly what's not working as expected:

```js
      provider.addInteraction({
        uponReceiving: "a request to create a new mate",
        withRequest: {
          method: "POST",
          path: "/animals",
          body: {
            foo: [] // <- your nullable serialises an empty array
          },
          headers: {
            "Content-Type": "application/json; charset=utf-8",
          },
        },
        willRespondWith: {
          status: 200,
          headers: {
            "Content-Type": "application/json; charset=utf-8",
          },
          body: like(suitor),
        },
      })
```

This will create a pact file that looks like this

```
...
  "interactions": [
    {
      "description": "a request to create a new mate",
      "request": {
        "method": "POST",
        "path": "/animals",
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "foo": [ // <- pact  will record this empty array

          ]
        }
      },
      "response": {
        "status": 200,
        "headers": {
...
```

**Comment by benquinteros** [comment]
That works as expected, my misunderstanding.

**Comment by mefellows** [comment]
Ha, ok no worries. If there is an issue, feel free to re-open!
