### ISSUE TITLE
RFC1123 Datetime matcher format

### ISSUE THREAD

**Issue by tomasbasham** [pact-foundation/pact-js#451]
From the look of the regex I believe this is actually a RFC1123 datetime format and not RFC3339.

https://github.com/pact-foundation/pact-js/blob/8ed3efe36288e505194555552b0d91c1c9647ec7/src/dsl/matchers.ts#L22

**Comment by TimothyJones** [comment]
From a cursory glance it appears you are correct.

Before I go unpacking the regex, do you happen to know that it is wholly RFC1123 compliant, or were you just reporting that it looks like it probably is RFC1123?

Either way, thanks for the report! Much appreciated.

**Comment by tomasbasham** [comment]
I'm afraid I'm not too familiar with the standard. I just noticed it most definitely was not RFC3339 as this is used a lot in Go.

**Comment by TimothyJones** [comment]
Thanks for the report! This is fixed in v10.0.0-beta.47, and will be in the next major release.
