### ISSUE TITLE
Matchers.extractPayload ignores properties that aren't matchers

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#454]
## Software versions

- **Consumer Pact library**: e.g. Pact JS v9.10.0

We have a helper called `extractPayload`, used for creating test objects from pact matchers:

```
    describe('when there are only matchers', () => {
      const rawPlayer = { name: 'tim' };
      const matchedPlayer = { name: Matchers.like('tim') };

      it('Returns the raw object', () => {
        expect(Matchers.extractPayload(matchedPlayer)).toEqual(rawPlayer);
      });
    });
```

However, when there are fields that aren't matchers, they are omitted from the extracted payload:

```
    // These tests fail
    const rawPlayer = { name: 'tim', code: 'THIS_GUY' };
    const matchedPlayer = { name: Matchers.like('tim'), code: 'THIS_GUY' };

    describe('when there are no matchers at all', () => {
      it('Returns the same object', () => {
        expect(Matchers.extractPayload(rawPlayer)).toEqual(rawPlayer);
      });
    });

    describe('when there some fields without matchers', () => {
      it('Returns the raw object', () => {
        expect(Matchers.extractPayload(matchedPlayer)).toEqual(player);
      });
    });
```

## Expected behaviour

Fields that are explicit should be returned without modification (ie, the tests above should pass)

## Actual behaviour

Fields with no matchers are deleted in the returned object (ie, the tests above do not pass)

## Steps to reproduce

Run the tests above

**Comment by TimothyJones** [comment]
It's possible I've misunderstood the purpose of `extractPayload`, and if that is the case, then this is instead a feature request for a function that passes these tests :)

**Comment by mefellows** [comment]
Thanks Tim, no the behaviour you describe was what it was intended (and if changing it breaks other functionality we will just have to deal with that as it comes up). I can't recall the exact usage in the code base, it wasn't designed necessarily for use outside of the DSL but left as public as a utility - which has turned out to be useful to some.
