### ISSUE TITLE
req.headers["authorization"] is case sensitive in requestFilter

### ISSUE THREAD

**Issue by aurnoi1** [pact-foundation/pact-js#465]
## Software versions

- **OS**: Windows 10 - 2004
- **Consumer Pact library**:" @pact-foundation/pact": "9.11.0"
- **Provider Pact library**: "@pact-foundation/pact": "9.11.0"
- **Node Version**: v12.16.1

Confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have created a reproducable git repository to illuminate the problem
- [X ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code

## Expected behaviour

this [documentation example](https://github.com/pact-foundation/pact-js#modify-requests-prior-to-verification-request-filters) should allows to overwrite the Authorization token:
```js
requestFilter: (req, res, next) => {
    req.headers["Authorization"] = `Bearer: ${token}`
    next()
```
## Actual behaviour

The token is not overwriten.

## FYI
The actual contract contains these information:
```json
  "interactions": [
    {
      "description": "a request to get the list of accounts",
      "providerState": "A list of accounts exists",
      "request": {
        "method": "GET",
        "path": "/accounts",
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Authorization": "Bearer df4e73c6-8bbb-11ea-bc55-0242ac130003"
        }
      },
```

## Workaround
Using lowercase "authrorization" as documented in this[ other example](https://github.com/pact-foundation/pact-js/blob/ab7e3a4f1d68792e54004380054c41b81f071686/examples/e2e/test/provider.spec.js#L23), does allow to overwrite the token.

**Comment by mefellows** [comment]
I think this is just because express lowercases headers. Most HTTP frameworks will canonicalise the headers (sometimes lowercasing-the-header and sometimes Upper-Camel-Casing-The-Header). 

Closing as the solution is mentioned.
