### ISSUE TITLE
Fix docs for migration

### ISSUE THREAD

**Issue by elliottmurray** [pact-foundation/pact-js#488]
## Issue Classification

- [ ] Feature request

## Feature Request
From yarn build. 3 github paths fail in docosaurus, slack url needs to be absolute.

- Page path = /implementation_guides/javascript/readme:
   -> link to examples/v3/e2e (resolved as: /implementation_guides/javascript/examples/v3/e2e)
   -> link to examples/v3/todo-consumer (resolved as: /implementation_guides/javascript/examples/v3/todo-consumer)
   -> link to examples/v3/todo-consumer/test/consumer.spec.js (resolved as: /implementation_guides/javascript/examples/v3/todo-consumer/test/consumer.spec.js)
   -> link to slack.pact.io (resolved as: /implementation_guides/javascript/slack.pact.io)

**Comment by ibotdotout** [comment]
Could you explain more How I can reproduce this ?

**Comment by mefellows** [comment]
Closing this as we have docs in docs.pact.io and we have a set of new docs to publish shortly.
