### ISSUE TITLE
Tests timeout before pact daemon starts

### ISSUE THREAD

**Issue by azzamallow** [pact-foundation/pact-js#49]
I've started experiencing an issue where my mocha tests time out before the pact daemon starts.
```
[2017-05-12T00:19:06.959Z]  INFO: pact-node@4.9.1/36673 on Machine: Creating Pact with PID: 36674
    1) "before all" hook


Pact verification failed!
Error: connect ECONNREFUSED 127.0.0.1:6666
(node:36673) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Pact verification failed - expected interactions did not match actual.
(node:36673) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36673) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 127.0.0.1:6666

  0 passing (2s)
  1 failing

  1) Contracts Pact "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

The default two second timeout is too short, I've resolved this by increasing the timeout on mocha to make the tests pass.
```
mocha consumer.js --timeout 10000
```

The weirdness is:

1. This has just started happening, nothing changed in terms of dependency versions
2. It was not clear to me what the problem was but reading the output from mocha, I had to probe around to figure this out.

**Comment by mefellows** [comment]
hmm am I right in guessing that you are connecting a pact front end to the pact go daemon?

**Comment by azzamallow** [comment]
not sure what you mean by pact front end, I am using the pact-js tool via mocha, and I believe pact-js is starting the daemon for me. I am not starting up a daemon myself.

**Comment by mefellows** [comment]
The reason I asked is I noticed that it's trying to connect to port `6666` which is the default Daemon port for `pact-go`, so if the Go daemon is running and your pact JS tests were pointed at it, this would definitely not work. But you _did_ say that increasing the timeout fixed it, so it's probably just coincidental.

I agree, a better error would be nice here (we do have a note on this in the [troubleshooting](https://github.com/pact-foundation/pact-js#timeout) section, but we shouldn't rely on that).

I'll leave this open as a request to fix.

In terms of slowness, it could be recently changes in the underlying Ruby process, which might be the "final straw that broke the camel's back" sort of thing.

**Comment by azzamallow** [comment]
Ok I see. I am using pact-go for other things but it is unrelated to this problem. This is the setup in mocha as an FYI (note I've chosen port 6666 by chance):

```
const provider = pact({
    consumer: 'TestApp',
    provider: 'Contracts',
    port: 6666,
    log: path.resolve(process.cwd(), 'logs', 'pact.log'),
    dir: path.resolve(process.cwd(), 'pacts'),
    logLevel: 'INFO',
    spec: 2
  });
```

**Comment by mefellows** [comment]
Thanks. I don't see anything wrong with that setup. I've marked this for enhancement, I take it you're able to progress now?

**Comment by azzamallow** [comment]
Yes I can.

**Comment by lemon123456** [comment]
I am experiencing a similar error: 


Pact
[2018-01-02T04:02:22.269Z]  INFO: pact-node@6.7.0/61436 on xxj.local: Created './platforms/darwin/bin/pact-mock-service service --host '127.0.0.1' --port '2202' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'' process with PID: 61437
[2018-01-02T04:02:22.302Z]  WARN: pact-node@6.7.0/61436 on xxj.local: Pact exited with code 1.
[2018-01-02T04:02:22.302Z]  INFO: pact-node@6.7.0/61436 on xxj.local: Removing Pact with PID: 61437
    1) "before all" hook
(node:61436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:2202
(node:61436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Pact verification failed!
Error: connect ECONNREFUSED 127.0.0.1:2202
(node:61436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Pact verification failed - expected interactions did not match actual.
(node:61436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Pact startup failed; tried calling service 10 times with no result.
    2) "after all" hook


  0 passing (30s)
  2 failing

  1) Pact
       "before all" hook:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) Pact
       "after all" hook:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by lemon123456** [comment]
@mefellows The following is my file:

```
   const provider = pact({
        consumer: 'TodoApp',
        provider: 'TodoService',
        port: MOCK_SERVER_PORT,
        log: path.resolve(process.cwd(), 'logs', 'pact.log'),
        dir: path.resolve(process.cwd(), 'pacts'),
        logLevel: 'INFO',
        spec: 2
    });

    const EXPECTED_BODY = [{
        id: 1,
        name: 'Project 1',
        due: '2016-02-11T09:46:56.023Z',
        tasks: [
            {id: 1, name: 'Do the laundry', 'done': true},
            {id: 2, name: 'Do the dishes', 'done': false},
            {id: 3, name: 'Do the backyard', 'done': false},
            {id: 4, name: 'Do nothing', 'done': false}
        ]
    }];

    before((done) => {
        provider.setup().then(done);
    });

    after((done) => {
        provider.finalize();
        provider.verify().then(done);
    });
```

**Comment by mboudreau** [comment]
Which version of node are you on? It looks like node is throwing the error
because you're not handling a promise rejection?

**Comment by lemon123456** [comment]
I'm using node v8.5.0

**Comment by mefellows** [comment]
I don't think that's the problem:

```
[2018-01-02T04:02:22.269Z]  INFO: pact-node@6.7.0/61436 on xxj.local: Created './platforms/darwin/bin/pact-mock-service service --host '127.0.0.1' --port '2202' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'' process with PID: 61437
[2018-01-02T04:02:22.302Z]  WARN: pact-node@6.7.0/61436 on xxj.local: Pact exited with code 1.
[2018-01-02T04:02:22.302Z]  INFO: pact-node@6.7.0/61436 on xxj.local: Removing Pact with PID: 61437
```

Notice how the process immediately exits with status code 1.

I'm wondering if it's actually the spaces or something?

@lemon123456 can you please run the following on your machine and share the output?

```
./node_modules/@pact-foundation/pact-standalone/platforms/darwin/bin/pact-mock-service service --host '127.0.0.1' --port '2202' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'
```

Also, can you please provide the extra details as per the [issue template](https://github.com/pact-foundation/pact-js/blob/master/.github/issue_template.md#relevant-log-files)?

**Comment by lemon123456** [comment]
Sure. This is the output:

```
➜  pact-exercise ./node_modules/@pact-foundation/pact-standalone/platforms/darwin/bin/pact-mock-service service --host '127.0.0.1' --port '2202' --log '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/logs/pact.log' --pact_dir '/Users/twer/Documents/AutoTest/Contract test/pact-exercise/pacts' --pact_specification_version '2' --pact-file-write-mode 'overwrite'

/Users/twer/Documents/AutoTest/Contract test/pact-exercise/node_modules/@pact-foundation/pact-standalone/platforms/darwin/lib/ruby/bin/ruby: line 14: test/pact-exercise/node_modules/@pact-foundation/pact-standalone/platforms/darwin/lib/ruby/lib/ruby/gems/2.2.0: No such file or directory
```

**Comment by mefellows** [comment]
@crystalyxiaoxianer the resolution is increasing your test timeout duration. 

In the case of running a mocha suite, it looks something like this `mocha consumer.js --timeout 10000`.

You should consult the docs for whatever framework you're using.

**Comment by crystalyxiaoxianer** [comment]
@mefellows  my problem had solved that  i changed port.  Before that, i  had changed port several times but not work.  thank you anyway.   but i have a new problem  that all tests passed but not write pact files.

**Comment by crystalyxiaoxianer** [comment]
@mefellows ok,i will.
