### ISSUE TITLE
supported WebDAV HTTP methods

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#494]
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request

WebDAV methods like `MKCOL` (https://en.wikipedia.org/wiki/WebDAV#Implementation) are not supported, trying to use them results in an error `Failed: You must provide a valid HTTP method: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS.`

**Comment by mefellows** [comment]
` v9.12.0` on the way - thanks for this PR!

I've verified this works for a consumer test in JS and it should also work for a provider. What language are you using for the provider?

**Comment by individual-it** [comment]
@mefellows we haven't implemented the provider tests yet. Not sure if that is the correct workflow but we fist focus on the consumer tests. The main goal is to convert the currenty existing tests. The current tests using a real server and over time we found it hard to maintain and run in CI, specially because there are now different provider versions and the consumer has to run with both.
So the plan is to convert first all consumer tests to use pact and then look into the provider tests. I guess it will be ether JS or Go. Not sure what is wiser, the provider itself is written in Go, but all the consumer tests are done in JS

**Comment by mefellows** [comment]
You're doing it right and awesome to see you folks using Pact.

As you know, I also maintain the Golang port so I will jump on any issues you see straight away. Sorry I haven't gotten to your other PR just yet, it's on the list.

Depending on your complexity, you may be able to use the CLI verifier: https://docs.pact.io/implementation_guides/cli#provider-verifier
