### ISSUE TITLE
specify an interaction that matches when a field does NOT exist

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#511]
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request
I would need a way to create an interaction that only matches when a header DOES NOT exist?
in my case I want to have 3  interactions:
 1. auth header set and correct
 2. auth header set and incorrect
 3. auth header not present

If I don't mention the auth header for the third interaction I get multiple interactions that match a requests with correct and wrong password.

What would be handy is something like:
```
      provider.addInteraction({
        uponReceiving: 'list password folder sending NO password',
        withRequest: {
          method: 'PROPFIND',
          path: '/remote.php/dav/public-files/
          headers: {
            authorization:  Pact.Matchers.shouldNotExist
          }
        },
        willRespondWith: {
          status: 401
    })
```

I tried using `nullValue` matcher, but that seems not to work

**Comment by mefellows** [comment]
Thanks @individual-it. Can you please share your test setup? You should have 3 separate tests for the above and definitely be able to test the scenario you're describing without a new matcher.

**Comment by individual-it** [comment]
@mefellows here is the test, it uses `'jasmine-data-provider'` to run the same test with different values.

```
  describe('when listing a shared folder', function () {
    using({
      'without password': {
        shareParams: {},
        passwordWhenListing: null,
        shallGrantAccess: true
      },
      'with password': {
        shareParams: {
          password: 'password'
        },
        passwordWhenListing: 'password',
        shallGrantAccess: true
      },
      'with password but invalid when accessing': {
        shareParams: {
          password: 'password'
        },
        passwordWhenListing: 'invalid',
        shallGrantAccess: false
      }
      // the following test cannot not be used currently because there is no way
      // to have an interaction that only matches when a header (in this case authorization) is NOT set
      // see https://github.com/pact-foundation/pact-js/issues/511

      // 'with password but no password when accessing': {
      //   shareParams: {
      //     password: 'password'
      //   },
      //   passwordWhenListing: null,
      //   shallGrantAccess: false
      // }
    }, function (data, description) {
      describe(description, function () {
        // TESTING CONFIGS
        const testContent = 'testContent'

        // CREATED SHARES
        let testFolderShare = null

        beforeEach(function (done) {
          oc.shares.shareFileWithLink(config.testFolder, data.shareParams).then(share => {
            expect(typeof (share)).toBe('object')
            testFolderShare = share
            done()
          }).catch(error => {
            fail(error)
            done()
          })
        })

        fit('should list the folder contents', function (done) {
          oc.publicFiles.list(testFolderShare.getToken(), data.passwordWhenListing).then(files => {
            if (data.shallGrantAccess) {
              // test length
              expect(files.length).toBe(4)
              // test root folder
              expect(files[0].getName()).toBe(testFolderShare.getToken())
              expect(files[0].getPath()).toBe('/')
              expect(files[0].getProperty(oc.publicFiles.PUBLIC_LINK_ITEM_TYPE)).toBe('folder')
              expect(files[0].getProperty(oc.publicFiles.PUBLIC_LINK_SHARE_OWNER)).toBe(config.username)
              expect(files[0].getProperty(oc.publicFiles.PUBLIC_LINK_PERMISSION)).toBe('1')

              // test folder elements
              expect(files[1].getName()).toBe(config.testFiles[0])
              expect(files[1].getPath()).toBe('/' + testFolderShare.getToken() + '/')

              expect(files[2].getName()).toBe(config.testFiles[1])
              expect(files[2].getPath()).toBe('/' + testFolderShare.getToken() + '/')

              expect(files[3].getName()).toBe(config.testFiles[2])
              expect(files[3].getPath()).toBe('/' + testFolderShare.getToken() + '/')
            } else {
              fail(files)
            }
            done()
          }).catch(error => {
            if (data.shallGrantAccess) {
              fail(error)
            } else {
              expect(error.statusCode).toBe(401)
            }
            done()
          })
        })
```

Are you saying that I should have an interaction created in the specific test, that is only valid for that specific test?

In the beginning of my current task (converting existing tests to pact.io) I tried to have interactions that are just for that specific test, but could not accomplish that because there seems no way to make `provider = new Pact.PactWeb()` super-global to be accessible between all test files

**Comment by mefellows** [comment]
Thanks!

> In the beginning of my current task (converting existing tests to pact.io) I tried to have interactions that are just for that specific test, but could not accomplish that because there seems no way to make provider = new Pact.PactWeb() super-global to be accessible between all test files

`karma-pact` can do that (https://github.com/pact-foundation/karma-pact/), whilst allowing you the ability to define the interactions from within your jasmine tests. Here is an example you can follow: https://github.com/pact-foundation/pact-js/blob/master/examples/karma/jasmine/client-spec.js

In case you missed it, see also your options [using Pact in non-Node environments](https://github.com/pact-foundation/pact-js#using-pact-in-non-node-environments)

The issue is that because you load 3 overlapping interactions at once, the mock service gets confused about what you want.

Let us know if the above doesn't unblock you.

**Comment by individual-it** [comment]
for anyone who comes here later:
my miss-concept was to put all interactions in a central location, I've done so because in karma.js there is no way to make a variable `provider = new Pact.PactWeb()` global and accessible from all test files. But that seems not to be necessary.
Every test-file can create its own `provider = new Pact.PactWeb()`
to reduce duplication of interactions that are needed in all tests (in our case `OPTIONS` CORS-preflight) we put them in a separate helper file, that helper function does receive the `provider` object and returns promises of all needed interactions

to not move all interactions in the first step of the refactoring, I just dumped all existing interactions into the helper (see https://github.com/owncloud/owncloud-sdk/pull/583). Next step will be to move the interactions to the correct tests (or create extra helpers if interactions are needed in multiple, but not all test files)

**Comment by mefellows** [comment]
@individual-it thanks for following this up!

Also note that there is a `cors` option on the Pact constructor which you can set to `true` to enable CORS on the mock server (I wasn't sure if that was what you needed, but felt it worth mentioning if it will simplify your seutp).

**Comment by individual-it** [comment]
@mefellows thanks, I tried that at the very beginning but did not help in the case of our app :-(
