### ISSUE TITLE
Cannot find module '../native'  (when using V3 spec beta release)

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#514]
Copied from another issue about V3:

-----

I'm having [similar issue](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1600426474003300) with 10.x as well. But we are not using `jest-pact` and the error is
```
    Cannot find module '../native' from 'node_modules/@pact-foundation/pact/v3/index.js'
```

_Originally posted by @aelmekeev in https://github.com/pact-foundation/pact-js/issues/483#issuecomment-696154255_

**Comment by TimothyJones** [comment]
@mefellows @uglyog : I encountered this too, and fixed it by modifying the import to `../native/index.node`. I don't have the context for the V3 branch though - would that be an appropriate fix?

**Comment by mefellows** [comment]
It may do. My recollection of the issue is that if pact is installed at a different level (e.g. within another dependency or lerna hierarchy) the relative path isn't resolved correctly. 

We'll need to reliably reproduce it to fix first.

**Comment by TimothyJones** [comment]
I think the problem is more to do with node module resolution - index.node isn’t always picked up as a candidate for index.

My suspicion is that this might only be a problem for typescript users, because the documentation says that index includes work “the same as node”, but only mention index.js, not index.node

**Comment by uglyog** [comment]
I've updated the imports, but I haven't been able to replicate this issue. It was worked ok for my test projects.

**Comment by uglyog** [comment]
Ah! `from 'node_modules/@pact-foundation/pact/v3/index.js'`
should have been `from 'node_modules/@pact-foundation/pact/v3/pact.js'`

due to the `types` and `main` entry in `package.json`. This has now been changed to `index` instead of `pact`

**Comment by aelmekeev** [comment]
> My recollection of the issue is that if pact is installed at a different level (e.g. within another dependency or lerna hierarchy) the relative path isn't resolved correctly.

This is probably the case cause we are using yarn workspaceses and `@pact-foundation` is in root level `node_modules` and not "workspace" level `node_modules`.

**Comment by TimothyJones** [comment]
@aelmekeev Does v10.0.0-beta.17 work for you?

**Comment by aelmekeev** [comment]
@TimothyJones it does work 🎉

**Comment by TimothyJones** [comment]
Great! It works for jest-pact's beta V3 build too, so I think we can close this.
