### ISSUE TITLE
Support webdav REPORT method

### ISSUE THREAD

**Issue by HariBhandari07** [pact-foundation/pact-js#518]
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request
WebDav method `REPORT` is still not supported and trying to use `REPORT` results in an error like `Failed: You must provide a valid HTTP method: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS.`

**Comment by TimothyJones** [comment]
`9.13.0` is building now with this fix in it.

It will be available in all your favourite npm repositories in about 10-15 minutes.
