### ISSUE TITLE
Allow term matcher to generate integers

### ISSUE THREAD

**Issue by callumbooth** [pact-foundation/pact-js#521]
## Issue Classification

- [ ] Feature request
- [x] Bug report

## Bug Report

Might be related to #435 but currently it's not possible to use the term matcher with integers. 

### Software versions

_NOTE: only applicable for bug reports_

- **OS**: e.g. Mac OSX 10.11.5
- **Consumer Pact library**: e.g. Pact JS v2.6.0
- **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
- **Node Version**: `node --version`

### Issue Checklist

Confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have created a reproducable git repository (see below) to illuminate the problem
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code

### Expected behaviour

I should be able to use `term()` to generate integer values. Passing `term({generate: '0', matcher: '0|1'})` is not suitable because the contract json file it generates will check against a string type rather than the integer type.

### Actual behaviour

When passing `term({generate: 0, matcher: '0|1'})` you get the message `Error ocurred in mock service: RuntimeError - Value to generate \\\"0\\\" does not match regular expression...`.

**Comment by mefellows** [comment]
Thanks, should the title be "Allow term matcher to generate **integers**" (on "non strings"?)

Yes, at the current time, you cannot generate non-string values for a regex.

Our next major release of Pact (https://github.com/pact-foundation/pact-js#pact-js-v3) would let you do this if you wanted to try it?

**Comment by callumbooth** [comment]
yes, the title should be integers. I'll take a look at v3 and get back to you.

**Comment by mefellows** [comment]
10.x.x supports this.
