### ISSUE TITLE
Jest tests are passing, but pact files are not being generated

### ISSUE THREAD

**Issue by ralves20** [pact-foundation/pact-js#522]
Hello,

I'm creating consumer tests in a node-js application and I'm using jest for pact tests.
I was able to create the tests properly and they are passing, however, they are not generating the contract on the proper folder (dist/pacts)...
but the pact.log file is generated

Do you guys have any ideia on what am I missing on the code and why the pact file is not generated?

```
    const pact = new Pact({
        consumer: "user-data-ui2",
        provider: "user-data-provider",
        port: MOCK_SERVER_PORT,
        log: path.resolve(process.cwd(), "dist/logs", "pact.log"),
        dir: path.resolve(process.cwd(), "dist/pacts"),
        spec: 2,
        logLevel: 'WARN',
        cors: true
    });
```

```
 it("can load user data", () => {
            const url = `http://localhost:${MOCK_SERVER_PORT}/user`;
            const promise = fetchUserData(url);

            return promise.then(response => {
                expect(response.status).toBe(200);
                expect(response.headers['content-type']).toBe("application/json;charset=UTF-8");
                expect(response.data).toMatchObject({
                    firstName: "aValidFirstName",
                    lastName: "aValidLastName",
                    age: 100
                });
            })
        });
    });

    afterAll(() => {
        // pact.writePact();
        pact.finalize();
        publishContract();

    });


```

Thanks!

**Comment by mefellows** [comment]
There are a few issues:

1. you're not calling the `pact.verify()` method, which is the method that confirms the interaction was correctly performed (see point `5` https://github.com/pact-foundation/pact-js#example)
2. in your `afterAll` block, both of those calls are promises but you aren't handling them. It's possible your code will try and publish before the pact file itself has been created.
