### ISSUE TITLE
Add simple changelog (?)

### ISSUE THREAD

**Issue by ivan-kolmychek** [pact-foundation/pact-js#53]
It would be really nice to have a changelog, maybe at least for major releases.

It feels scary to just update it from `1.0.x` to `2.5.x` without any idea of what breaking changes were introduced. :)

Commit history helps, but I'm pretty sure that some `history.md` even with short "hey, we've bumped version to 2.x cause of X, Y and Z breaking changes" is better than reading through [28 commits between `1.0.0`  and `2.0.0`](https://github.com/pact-foundation/pact-js/compare/v1.0.0...v2.0.0) tags trying to find those potentially breaking changes.

**Comment by mefellows** [comment]
Yep, agree. I'll update contributing.md and create a changelog - thanks!

**Comment by mefellows** [comment]
This is done - we'll update on each release.
