### ISSUE TITLE
V3 MatchersV3 cannot be used in json structures

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#548]
## Issue Classification

- [ ] Feature request
- [x] Bug report

## Bug Report
trying to use a matcher in a part of the interaction that is provided by a JSON structure. e.g. headers throws an `internal error in Neon modul`

### Software versions

_NOTE: only applicable for bug reports_

- **OS**: Ubuntu 20.10
- **Consumer Pact library**: Pact JS v10.0.0-beta.22
- **Provider Pact library**: Pact JS v10.0.0-beta.22
- **Node Version**: v12.20.0

### Issue Checklist

Confirm the following:

- [x] I have upgraded to the latest
- [ ] I have created a reproducable git repository (see below) to illuminate the problem
- [ ] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code

### Expected behaviour

nice error if its not sported or us the matcher

### Actual behaviour

```
    internal error in Neon module: called `Result::unwrap()` on an `Err` value: DowncastError

      265 | 
      266 |   await provider.uponReceiving('a capabilities GET request with invalid authentication')
    > 267 |     .withRequest({
          |      ^
      268 |       method:  'GET',
      269 |       path:  '/ocs/v1.php/cloud/capabilities',
      270 |       query: {'format': 'json'},

      at PactV3.withRequest (node_modules/@pact-foundation/src/v3/pact.ts:137:15)
      at _callee2$ (tests/pactHelper.js:267:6)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (tests/pactHelper.js:13:103)
      at _next (tests/pactHelper.js:15:194)
```

### Steps to reproduce
create a interaction with a matcher in `headers.Authorization`
e.g.
```
provider.uponReceiving('a capabilities GET request with invalid authentication')
    .withRequest({
      method:  'GET',
      path:  '/ocs/v1.php/cloud/capabilities',
      query: {'format': 'json'},
      headers: {
        'Authorization': MatchersV3.string('Basic 1234')
      }
    })
...
```

in the v3 example exactly that issue happens: https://github.com/pact-foundation/pact-js/tree/feat/v3.0.0/examples/v3/todo-consumer

```
  1) Pact V3
       when there are a list of projects
         with XML requests
           "before all" hook for "generates a list of TODOs for the main screen":
     Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: DowncastError
      at PactV3.withRequest (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/node_modules/@pact-foundation/src/v3/pact.ts:137:15)
      at Context.<anonymous> (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/test/consumer.spec.js:94:12)
      at callFn (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/node_modules/mocha/lib/runnable.js:387:21)
      at Hook.Runnable.run (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/node_modules/mocha/lib/runnable.js:379:7)
      at next (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/node_modules/mocha/lib/runner.js:384:10)
      at Immediate._onImmediate (/home/artur/www/pact/pact-js/examples/v3/todo-consumer/node_modules/mocha/lib/runner.js:425:5)
      at processImmediate (internal/timers.js:461:21)

**Comment by TimothyJones** [comment]
Thanks for the report! Can you tell me what the use case for a matcher in the header is? Usually matchers are for widening what is accepted during verification (as in, for specifying the provider response data).

**Comment by individual-it** [comment]
@TimothyJones in the pact v3 example its to match various content types https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/examples/v3/todo-consumer/test/consumer.spec.js#L98
I came across is because I tried to match anything except a valid basic-auth. I can work around it by setting a defined wrong password.

If its not supported and not a bug, then IMO a better error message should be shown.

**Comment by mefellows** [comment]
This feature should be supported IMO. I can see the arguments for not supporting it (a variation on Postel's Law and wanting to ensure we serialise what the actual consumer sends).

But, it is prevalent across all languages and versions and can be useful in situations to avoid more mocking (authorization being the main use case I use it for). Unless we're looking to drop that functionality in the rest of Pact, it seems strange we wouldn't also support it here.

**Comment by TimothyJones** [comment]
Hmm. Surely this is an anti-pattern, because otherwise we could end up with situations like:

* Consumer sends "application/foo+xml", which passes the consumer test `regex("application/.*xml(;.*)?", "application/xml")`
* Provider verifies with `application/xml`, which passes
* Actual consumer hitting actual provider with `application/foo+xml` fails

As I understand it, the purpose of matchers is to allow tests not to rely on specific data, not to widen the definition of the contract.

**Comment by TimothyJones** [comment]
The V3 specification allows it, so it is indeed a bug. I think the specification should forbid it. Something to consider for V4.

**Comment by uglyog** [comment]
Closing this as it works with the latest version
