### ISSUE TITLE
providerStatesUrl docs should tell me what needs to be provided by that url

### ISSUE THREAD

**Issue by thetrav** [pact-foundation/pact-js#55]
So... is it just 200 OK?  nope, is it an array of strings? nope, it is trying to enumerate keys, so it's some kind of dictionary.

Can you add or link to something like an example or schema in the readme?

**Comment by mefellows** [comment]
There was a link, but obviously that's not clear enough. I've brought in the material from linked repo (https://github.com/pact-foundation/pact-js#api-with-provider-states) - is this clearer do you think?
