### ISSUE TITLE
flexible matchers doc either incorrect or incomplete

### ISSUE THREAD

**Issue by thetrav** [pact-foundation/pact-js#56]
https://github.com/pact-foundation/pact-js#match-based-on-type

It implies there is a function named like in scope, this is not the case by default.

I'm 95% sure you mean pact.Matchers.somethingLike

**Comment by abubics** [comment]
Totally, I have `const { somethingLike: like } = pact.Matchers` in my tests.

**Comment by mefellows** [comment]
I've updated the README, hopefully this clarifies things.
