### ISSUE TITLE
V3 make VerifierV3 to accept self signed SSL certificates

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#561]
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request
currently its not possible to run `VerifierV3(opts).verifyProvider()` on a provider that uses a self-signed URL
```
Request Failed - Invalid response: error sending request for url (https://localhost:9200/ocs/v1.php/cloud/capabilities?format=json): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
```

It would be very useful if there would be an option like `validateSSL: false` to make it possible to use self-signed URLs, alternatively having the possibility to import a certificate would also work, but more complex to setup e.g. in CI

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-reference/pull/84.

WIP.

**Comment by individual-it** [comment]
this seems to be fixed in beta.25
self signed certificates can be used with `disableSSLVerification: true` in the `VerifierV3Options`
closing?

**Comment by mefellows** [comment]
Yep, thanks - closing!
