### ISSUE TITLE
confusing error message when content should be JSON but wrong content-type is set by provider

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#575]
## Issue Classification

- [ ] Feature request
- [x] Bug report

## Bug Report
When having an interaction that checks the JSON body of the provider and the provider respond with a JSON body but sets the wrong Content-Type in the header the error message is confusing.

Interaction response:
```
...
      .willRespondWith({
        status: 200,
        body: {
          ocs: {
            meta: {
              statuscode: 100
            }
          }
        }
```

### Software versions

- **OS**: Ubuntu 20
- **Consumer Pact library**: Pact JS v10.0.0-beta.25
- **Provider Pact library**: Pact JS v10.0.0-beta.25
- **Node Version**: v12.20.1

### Issue Checklist

Confirm the following:

- [x] I have upgraded to the latest
- [x] I have created a reproducable git repository (see below) to illuminate the problem
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle

### Expected behaviour
ether of:
1. don't check the content-type if its not mentioned in the interaction, only check the body
1. An error message saying that the header is the problem, because the body is actually valid JSON

### Actual behaviour

```
1) Verifying a pact between owncloud-sdk and oc-server - a capabilities GET request with valid authentication returns a response which 
  1.1) has a matching body
          expected 'application/json' body but was 'text/plain;charset=utf-8'
```

In case the interaction is set also to check the header the error message is:
```
1) Verifying a pact between owncloud-sdk and oc-server - a capabilities GET request with valid authentication returns a response which 
    1.1) has a matching body
           expected 'application/json;charset=utf-8' body but was 'text/plain;charset=utf-8'
    1.2) includes header 'Content-Type' with value 'application/json; charset=utf-8'
           Expected header 'Content-Type' to have value 'application/json; charset=utf-8' but was 'text/plain; charset=utf-8'
```
### Steps to reproduce
Interaction defined as:
https://gist.github.com/individual-it/909674801163a994b3701bbbf2e6fe32

provider tests run against github.com/owncloud/core/ work fine, because it returns the correct content-type
github.com/owncloud/ocis/ sets the content type wrong and that leads to the described error message

### Relevant log files
```
PROVIDER_BASE_URL=https://localhost:9200 yarn test-provider
yarn run v1.22.5
$ jest --runInBand providerTest.js

Verifying a pact between owncloud-sdk and oc-server

 RUNS  tests/providerTest.js
  a capabilities GET request with valid authentication
    returns a response which
      has status code 200 (OK)
      has a matching body (FAILED)


Failures:

1) Verifying a pact between owncloud-sdk and oc-server - a capabilities GET request with valid authentication returns a response which 
    1.1) has a matching body
           expected 'application/json' body but was 'text/plain;charset=utf-8'

 FAIL  tests/providerTest.js
  provider testing
    ✕ verifies the provider (224 ms)

  ● provider testing › verifies the provider

    TypeError: Cannot read property 'message' of null

      29 |     }
      30 |     await new VerifierV3(opts).verifyProvider().catch(function (error) {
    > 31 |       chai.assert.fail(error.message)
         |                              ^
      32 |     })
      33 |   }, 60000)
      34 | })

      at tests/providerTest.js:31:30

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.036 s
Ran all test suites matching /providerTest.js/i.
error Command failed with exit code 1.
```

**Comment by TimothyJones** [comment]
@uglyog Looks like this might be in the rust provider. Should we move the issue there?

**Comment by uglyog** [comment]
Not sure if this is an actual error. You need to use the content type header to determine the content type of the body. If the header is different, what would you like displayed for the error? 

When comparing the body, it is getting the header value to determine how to parse the bodies, but the header values are different, so it is not bothering to parse the body. With `text/plain`, it could be any format. If the expected was JSON, and the actual is CSV, how can you compare that?

**Comment by TimothyJones** [comment]
If the check is failing during the header check, shouldn't the error message read "has a matching header (fail)" - even if the header check is implied while looking at the body.

**Comment by uglyog** [comment]
During the header check, if the content type header was expected, the message will be 

```
Expected header 'Content-Type' to have value 'application/json; charset=utf-8' but was 'text/plain; charset=utf-8'
```

In this case, there was not any expected headers, so the headers were not compared. But when getting to compare the bodies, it uses the Content-Type header.

This is the steps that occurred:
1. Compare the status code - OK
2. Compare all expected headers - no headers were expected
3. Compare the bodies
    - get the content type header for the expected body - application/json
    - get the content type header for the actual body - text/plain
    - generate an error because the bodies have different contents

**Comment by TimothyJones** [comment]
Right, we're on the same page there.

However, I think the error message is misleading - because the bodies *don't* have different contents. They only have different content-type headers. Even though this was detected during the body equality check, I think it would be more helpful to tell the user the source of the mismatch (the header), rather than where in Pact the mismatch was detected (the body equality check).

If there's some structural reason that it's difficult to change the `1.1) has a matching body` text in this case, we could make the error message more explicit, like `expected 'application/json' content-type header, but was 'text/plain;charset=utf-8'`

**Comment by uglyog** [comment]
We could change it to: Could not compare the bodies because the content-type headers were different: expected ... received ...

**Comment by TimothyJones** [comment]
Perfect.

**Comment by d-shankar** [comment]
I faced the same issue, the reason was null object was returned by the provider which is of type text-plain and hence the test failed. Debugging the application and finding the reason why the provider returns a null object solved the issue l.

**Comment by d-shankar** [comment]
faced the same issue, the reason was because null value was returned by the provider which is of type text-plain and hence the test failed. Debugging the application and finding the reason why the provider returns a null object solved the issue.

**Comment by d-shankar** [comment]
Faced the same issue, the reason was because null value was returned by the provider which is of type text-plain and hence the test failed. Debugging the application and finding the reason why the provider returns a null object solved the issue

**Comment by d-shankar** [comment]
Faced the same issue, the reason was because null value was returned by the provider as response body which is of type text-plain and hence the test failed with the above mentioned exception message. Debugging the application and finding the reason why the provider returns a null redponse body solved the issue

**Comment by d-shankar** [comment]
Faced the same issue, the reason was because null value was returned by the provider as response body which is of type text-plain and hence the test failed with the above mentioned exception message. Debugging the application and finding the reason why the provider returns a null redponse body solved the issue

**Comment by d-shankar** [comment]
Faced the same issue, the reason was because null value was returned by the provider as response body which is of type text-plain and hence the test failed with the above mentioned exception message. Debugging the application and finding the reason why the provider returns a null response body solved the issue

**Comment by mefellows** [comment]
Awesome, I think we can close this off then.
