### ISSUE TITLE
Pact verification fails when using graphql-request package for actual request

### ISSUE THREAD

**Issue by dkulezich** [pact-foundation/pact-js#592]
### Software versions

- **OS**: MacOS 10.15.7
- **Consumer Pact library**:  @pact-foundation/pact 9.10.0 && 9.14.2

### Issue Checklist

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Description
We switched from Apollo to graphql-request in our project. Since then we use graphqlClient to do the requests to the Pact Mock server. Once we did that our pact tests started failing. We didn't change anything else and the tests were passing before. 

### Expected behaviour

Pact tests pass successfully when using graphql-request package 

### Actual behaviour

Tests are failing

### Steps to reproduce

Replace ApolloClient with GraphQLClient

### Relevant log files

    Rejected to value: [Error: GraphQL Error (Code: 500): {"response":{"message":"No interaction found for POST /","interaction_diffs":[{"description":"stations query","body":{"operationName":{"EXPECTED":"StationsQuery","ACTUAL":"<key not found>"}}}],"status":500,"headers":{}},"request":{"query":"query StationsQuery {\n  stations {\n    id\n    name\n    logo {\n      url\n    }\n    stream {\n      url\n    }\n  }\n}\n","variables":{}}}]

**Comment by mefellows** [comment]
That error suggests that `operationName` should be `StationsQuery` but instead is not coming through at all. 

That implies:

1. You have operation name set in the graphql interaction
2. Your code is not sending that interaction

If the behaviour is correct, then you need to update your expected interaction to not expect your code to send that operation name. Otherwise, you've just found a bug.

**Comment by dkulezich** [comment]
Thank you for your answer, Matt.
I've removed the operation name when setting the graphql interaction and from the query and I still get the same error as described above.
This behaviour is observed only when using graphql-request package, if I execute the same code with apollo client package it runs without errors and the contract is generated.

**Comment by mefellows** [comment]
Could you please attach the log file so we can see what's going on?

**Comment by dkulezich** [comment]
Sure, here are both logs with and without Operation name
[pact-noOperationName.log](https://github.com/pact-foundation/pact-js/files/5910434/pact-noOperationName.log)
[pact.log](https://github.com/pact-foundation/pact-js/files/5910435/pact.log)

**Comment by mefellows** [comment]
Thanks. So the `pact.log` file is the one failing, because as you say, it's expecting `operationName` but is not receiving it. The `pact-noOperationName.log` seems to be a working pact.

Can I assume that `pact-noOperationName.log` is the one where you were still using the apollo client? The user-agent looks the same, so I'm a bit confused.

**Comment by mefellows** [comment]
If you have a minute to chat in slack, i'll see you in #graphql, otherwise, I think I'm going to need to see your code to be able to help diagnose further.

**Comment by dkulezich** [comment]
Thanks, Mat, for your help. As you suggested I have removed the `operationName` from the test (deleted `.withOperation("StationsQuery")`) and added the `headers: {} `property to the the response ( to `.willRespondWith()`) and it did the job! Our tests are passing now and the contracts are successfully generated.

**Comment by TimothyJones** [comment]
Sounds like this got sorted out, so I'll close it. Feel free to reopen if there are any changes required.
