### ISSUE TITLE
[V3] File locking issue when writing to pact file with parallel tests in Jest

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#599]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OSX 10.15.7
- **Consumer Pact library**:  10.0.0-beta.29
- **Provider Pact library**: n/a
- **Node Version**: v12.18.0 (node) / 6.14.4 (npm)

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Pact file is written correctly when tests are run in parallel.

### Actual behaviour

- I have 6 tests and launch them in parallel by jest
- In 50% cases it false with error:
- (line and column numbers are different each launch)
- If I launch jest in one worker – no such an error. Looks like it is a kind of race condition.

Failure notice:

> Failed to write pact to file - Failed to parse Pact JSON - EOF while parsing a string at line 386 column 20

The error seems to be `this.pact.writePactFile(result.mockServer.id, this.opts.dir)  //   src/v3/pact.ts:208:23`, and likely is a file locking issue.

### Steps to reproduce

```
cd examples/v3/e2e
npm i --save-dev jest
cp test/consumer.spec.js test/consumer2.spec.js 
cp test/consumer.spec.js test/consumer3.spec.js 
cp test/consumer.spec.js test/consumer4.spec.js
jest test/*.spec.js
```

**Comment by TimothyJones** [comment]
In on mobile, but the documentation says somewhere that tests need to be run with `—runInBand`. We might need to surface that more clearly.

Of course, if we can fix it, that would be even better.

**Comment by mefellows** [comment]
Yes we do indeed! But that's only for the current package, the v3 package should be allowed to do this

**Comment by mefellows** [comment]
from `mock_server.rs`:

![Screen Shot 2021-02-08 at 10 12 00 am](https://user-images.githubusercontent.com/53900/107162269-16c7db80-69f6-11eb-94cb-fb19316da798.png)

It seems the original author could foresee this issue :)

**Comment by TimothyJones** [comment]
I believe this issue will happen with any framework that parallelises tests- but Jest is the only one I am aware of.

I wanted to get jest-pact to detect whether the tests were running in parallel and warn, but I couldn’t figure out a way to determine it

**Comment by TimothyJones** [comment]
Oh, I didn’t see this was v3

**Comment by TimothyJones** [comment]
A coworker and I once chased a broken feature down to a function that said “todo: implement this method”. So I guess this is better ;)

**Comment by mefellows** [comment]
Ron, I can see you've been making some changes for this. I was also but haven't pushed. I'll leave the upstream lib changes for you, want me to push the updates to the JS side? FYI it was fairly easy to replicate by just duplicating more tests.

**Comment by uglyog** [comment]
Rust libs have been released

**Comment by TimothyJones** [comment]
@mefellows Do you know if this can be closed now?

**Comment by mefellows** [comment]
Yes, I believe it has been fixed - thanks and closing!
