### ISSUE TITLE
fatal issue: Identifier 'makeErrorCause' has already been declared

### ISSUE THREAD

**Issue by pei-wang** [pact-foundation/pact-js#606]
_Thank you for reporting a bug! We appreciate it very much. Issues are a big input into the priorities for Pact-JS development_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OSX 10.15.7
- **Consumer Pact library**:  Pact JS v9.15.0
- **Node Version**:  v14.15.5
- ** TypeScript**: 3.8.3

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

I can run the consumer pact test.

### Actual behaviour

node_modules/make-error-cause/dist/index.js: Identifier 'makeErrorCause' has already been declared (12:4)

      10 |     return makeError(value, _super);
      11 | }
    > 12 | var makeErrorCause;
         |     ^
      13 | (function (makeErrorCause) {
      14 |     var BaseError = (function (_super) {
      15 |         __extends(BaseError, _super);

      at _temp._raise (node_modules/@babel/parser/src/parser/error.js:60:45)
      at _temp.raiseWithData (node_modules/@babel/parser/src/parser/error.js:55:17)
      at _temp.raise (node_modules/@babel/parser/src/parser/error.js:39:17)
      at ScopeHandler.checkRedeclarationInScope (node_modules/@babel/parser/src/util/scope.js:137:12)
      at ScopeHandler.declareName (node_modules/@babel/parser/src/util/scope.js:112:14)
      at _temp.checkLVal (node_modules/@babel/parser/src/parser/lval.js:435:22)
      at _temp.checkLVal (node_modules/@babel/parser/src/plugins/flow.js:2277:22)
      at _temp.parseVarId (node_modules/@babel/parser/src/parser/statement.js:1045:10)
      at _temp.parseVarId (node_modules/@babel/parser/src/plugins/flow.js:2625:13)
      at _temp.parseVar (node_modules/@babel/parser/src/parser/statement.js:1006:12)

### Steps to reproduce
https://stackoverflow.com/questions/61748582/pact-dependency-stopping-tests-being-run
_How can someone else reproduce this bug?_

_For extra bonus points and internet karma, provide a repository, gist or reproducible code snippet so that we can test the problem._

_We recommend forking the project and modifying a relevant example [in the examples folder](https://github.com/pact-foundation/pact-js/blob/master/examples)_

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._

**Comment by mefellows** [comment]
Can you please provide a repro for us? We have multiple JS and TS examples that don't have this problem, so we'd need to see the specific configuration causing the issue.

**Comment by mefellows** [comment]
As a side note, it seems to be a dependency on popsicle from `pact-node`, so an upgrade might just do the trick.

**Comment by mefellows** [comment]
And more follow up - we currently use Popsicle `9.2.0` (not from pact-node). The latest version of popsicle doesn't use that package, so it probably just requires a PR to update that package. 

PR welcome! :)

**Comment by pei-wang** [comment]
Hi @mefellows ,
Thanks for your response. 
I think it's our project config issue. Our project is React Native project.

After I update the transformIgnorePatterns in jest.config.js, it works.

But the weird thing is that it only happened when I init Pact object on the test file.

**Comment by TimothyJones** [comment]
I'm unable to reproduce this. What was the config issue?

**Comment by pei-wang** [comment]
basically my jest config is below:
```
  preset: 'react-native',
  // transformIgnorePatterns: ['node_modules/(?!(react-native|uilib)/)'], ## uncomment this, it's fine.
 //  transformIgnorePatterns: ['node_modules/uilib/']    ## if I uncomment this, it will fail
```
don't know how does this impact pact.

**Comment by lovewithmind** [comment]
> basically my jest config is below:
> 
> ```
>   preset: 'react-native',
>   // transformIgnorePatterns: ['node_modules/(?!(react-native|uilib)/)'], ## uncomment this, it's fine.
>  //  transformIgnorePatterns: ['node_modules/uilib/']    ## if I uncomment this, it will fail
> ```
> 
> don't know how does this impact pact.

This worked for me . Even i do not know how.
