### ISSUE TITLE
[V3] document VerifierV3Options

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#608]
I cannot find documentation for all the `VerifierV3Options`  https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/src/v3/verifier.ts#L9
would be good to have a list similar to https://github.com/pact-foundation/pact-js/tree/feat/v3.0.0#verification-options

I'm happy to work on that

**Comment by TimothyJones** [comment]
@individual-it : Sorry, somehow I missed your offer to work on this. Yes please! This would be super helpful.

I'm focussing on the V3 branch significantly over the next week.

**Comment by individual-it** [comment]
I must confess I also forget all about it :see_no_evil:, can you assign me, so that the task will be on my list?

**Comment by TimothyJones** [comment]
Sure thing!

**Comment by individual-it** [comment]
PR in #630 
but I don't know what the `requestFilter` option is for and `logLevel` seems not to have any effect

**Comment by individual-it** [comment]
fixed by #630
