### ISSUE TITLE
Pact For Soap API

### ISSUE THREAD

**Issue by Sourav201** [pact-foundation/pact-js#61]
Hello Team,

Do we have any pact solution working for SOAP API similar to REST based services.  50% of our microServices are SOAP based.  If no , do we have any future roadmap on this.

Any help would be appreciated.

**Comment by bethesque** [comment]
Pact JS uses the ruby implementation under the hood, and so far, despite many people asking for it over the past 4 years, nobody has actually volunteered to do the development of the XML matching logic. So if you can find someone to do the dev, it's on the roadmap ;)

**Comment by hemantp2001** [comment]
hi, I was trying with the SOAP Web  service and it seems it has a dependency on having the wsdl available on server and pact mock server is unable to mock the wsdl for the same SOAP service. Any idea how to add this capability to mock the wsdl file?

**Comment by mefellows** [comment]
As per Beth's comments, we don't support XML/SOAP services at this point, sorry. We'd happily accept a PR to the Ruby project however, to add this capability.

**Comment by mefellows** [comment]
Closing this, PRs welcome but we won't be adding this feature any time soon.
