### ISSUE TITLE
New beta version is failing

### ISSUE THREAD

**Issue by joramirez85** [pact-foundation/pact-js#617]
Hi,

I'm getting the follow error when I do:
- npm install to install pact-js because I need to use MatchersV3, XmlBuilder from @pact-foundation/pact/v3

Error: 404 status code downloading tarball https://github.com/pact-foundation/pact-js/releases/download/v10.0.0-beta.32/node-v64-darwin-x64-unknown.tar.gz

And node modules packages installation is breaking due this error 

pactjs version: "@pact-foundation/pact@beta": "^10.0.0-beta.32"
node version: v10.16.0
npm version: 6.9.0

**Comment by mefellows** [comment]
Hi @joramirez85 thanks for raising. Indeed, there was an issue with the v3 release process that prepended an extra `v` in the release.

I've updated the release process, and repaired the release - I've verified this by running a local install of the same version, and downloading the referenced file that was 404ing for you.
