### ISSUE TITLE
[V3] allow user to filter by state

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#622]
### Feature description

The current version of Pact JS allows to run verifications for specific interaction description and/or state: https://github.com/pact-foundation/pact-js#re-run-specific-verification-failures 

A similar approach (env var and possibly a flag in the API) in the V3 branch would be helpful.

The underlying Rust library exposes the following [CLI flags](https://docs.pact.io/implementation_guides/rust/pact_verifier_cli/#command-line-interface):

```
    -c, --filter-consumer <filter-consumer>...
            Consumer name to filter the pacts to be verified (can be repeated)

        --filter-description <filter-description>
            Only validate interactions whose descriptions match this filter

        --filter-state <filter-state>
            Only validate interactions whose provider states match this filter
```

**Comment by individual-it** [comment]
@mefellows something like #668 ?

**Comment by mefellows** [comment]
Closing as 10.x.x supports this.
