### ISSUE TITLE
pact-web package.json not updated with new filepath

### ISSUE THREAD

**Issue by eijiew** [pact-foundation/pact-js#625]
ref: https://github.com/pact-foundation/pact-js/blob/master/package.json.web#L7
```
  "types": "./pact-web.d.ts",
```
should it be updated to:
```
  "types": "./src/pact-web.d.ts",
```

not sure about the `"main": "pact-web.js",`, it seems like pact-web.js is still outside of the src folder

**Comment by TimothyJones** [comment]
Good catch! Sorry about this one - looks like we missed this because the pact-web examples aren't in typescript, so it looked like everything was fine.

Releasing 9.15.3 with this fixed - should be up in a few minutes.

**Comment by TimothyJones** [comment]
v9.15.3 is now released. Thanks for the report!
