### ISSUE TITLE
undefined method `strip' for nil:NilClass when verifying provider

### ISSUE THREAD

**Issue by kiennt23** [pact-foundation/pact-js#642]
### Software versions

- **OS**: _e.g. Mac OSX 11.2.3 (20D91)
- **Consumer Pact library**: _e.g. Pact JS v9.15.3
- **Provider Pact library**: _e.g. Pact JS v9.15.3
- **Node Version**: 12.21.0_1

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
Test pass

### Actual behaviour
Test failed with error: 
```
NoMethodError:
       undefined method `strip' for nil:NilClass
```

### Steps to reproduce
The contract file is [here](https://gist.github.com/kiennt23/ddaf25bec529dd0c8e0fea0620a1fdb9)
```
import { Verifier } from '@pact-foundation/pact';
import { LogLevel } from '@pact-foundation/pact-node/src/service';
import * as path from 'path';

const PACT_ROOT = path.join(__dirname, '../../', 'pact/pacts');

describe('Test An API', () => {
  it('validate the expectations', async () => {
    const defaultState: string = null;
    const opts = {
      logLevel: 'debug' as LogLevel,
      providerBaseUrl: 'https://api.sandbox.dana.id',
      pactUrls: [path.join(PACT_ROOT, 'test-consumer_test-provider.json')],
      stateHandlers: {
        [defaultState]: async (): Promise<any> => {
          // This is the "default" state handler, when no state is given
        },
      },
    };
    return await new Verifier(opts).verifyProvider();
  });
});

```

### Relevant log files
https://gist.github.com/kiennt23/45601e0f9979f7569fbd6f9c8b0489af

**Comment by TimothyJones** [comment]
Does this still happen with pact 9.15.4?

**Comment by mefellows** [comment]
Thanks for the helpful report. If upgrading doesn't help, you might want to see also https://github.com/pact-foundation/pact-js/issues/446#issuecomment-636538469

If you could please re-run the tests with the environment variable `BACKTRACE=true` set and share the output/logs, that might help.

**Comment by kiennt23** [comment]
> Does this still happen with pact 9.15.4?

Hi @TimothyJones yes it happens with pact 9.15.4.

> Thanks for the helpful report. If upgrading doesn't help, you might want to see also [#446 (comment)](https://github.com/pact-foundation/pact-js/issues/446#issuecomment-636538469)
> 
> If you could please re-run the tests with the environment variable `BACKTRACE=true` set and share the output/logs, that might help.

Hi, [here](https://gist.github.com/kiennt23/0762b0aa13875bca209875ce479fea15) is the log with backtrace enable, seems like it is the same issue. However, from the comment it says to update rack, how can I do that?

**Comment by mefellows** [comment]
Could you please share the pact file? It seems there is something in the cookies causing issues here

**Comment by kiennt23** [comment]
> Could you please share the pact file? It seems there is something in the cookies causing issues here

This is the cookie I received from the real response `JSESSIONID=DB300144B6B40F2B8AC6BFF95E01782B; Path=; Secure; HttpOnly`, the `Path` could be the problematic one.

This is the [pact file](https://gist.github.com/kiennt23/fb8041ba7c8774cafcdf71ad11ed1f19).

**Comment by TimothyJones** [comment]
@bethesque : Any ideas on this one?

**Comment by kiennt23** [comment]
Hi guys, any update for the issue?

**Comment by mefellows** [comment]
Hi @kiennt23, it's been a long weekend here in Australia and the maintainers of the relevant repositories have all been away. Please give us a few more days to look into it in any detail.

But for now, I'd look at experimenting with the values of the cookies in your Pact to see if you can eventually get the test to stop failing with this error - that would be very helpful for us.

**Comment by kiennt23** [comment]
Hi @mefellows,
Thanks for the advice, however, in my pact I don't set the expectation for the cookies. The issue is with the verifier. It seems like the issue with pact verifier when it parses the response from the provider API. IMO, the `=` sign at the end of the string is quite common in the cookie with the base64 encoded value.

**Comment by bethesque** [comment]
Here's the code that is throwing the error:

https://github.com/rack/rack/blob/2.1.4/lib/rack/mock.rb#L242

My guess is this is happening.

```ruby
irb(main):007:0> name, value = "foo=".split("=")
=> ["foo"]
irb(main):008:0> name
=> "foo"
irb(main):009:0> value
=> nil
```

**Comment by kiennt23** [comment]
Hi guys, any update on this? What is the recommendation to fix this one? It is blocking use actually.

**Comment by mefellows** [comment]
This issue is no longer relevant with the 10.x.x code base. Closing.
