### ISSUE TITLE
internal error in Neon module

### ISSUE THREAD

**Issue by m-ruhl** [pact-foundation/pact-js#643]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: docker: adoptopenjdk/openjdk11:jdk-11.0.7_10-alpine
- **Consumer Pact library**: _v10.0.0-beta.34_
- **Provider Pact library**: _---_
- **Node Version**: `14.16.0`

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

If I run the consumer test on my local device (Windows) machine everything works.
So I expect to run it also in the docker image.

### Actual behaviour

If the test is executed in the docker container on a CI build it fails.

### Relevant log files

```
    internal error in Neon module: assertion failed: `(left == right)`
      left: `22`,
     right: `0`

      63 |                 });
      64 |
    > 65 |             await provider.executeTest(async (mockserver: any) => {
         |                            ^
      66 |                 authenticatedApi.defaults.baseURL = mockserver.url;
      67 |
      68 |                 await expectSaga(

      at PactV3.executeTest (node_modules/@pact-foundation/src/v3/pact.ts:228:30)
      at Object.<anonymous> (.../Sagas.pact.test.ts:65:28)

  ● ... 401

    internal error in Neon module: Once instance has previously been poisoned

      91 |                 });
      92 |
    > 93 |             await provider.executeTest(async (mockserver: any) => {
         |                            ^
      94 |                 authenticatedApi.defaults.baseURL = mockserver.url;
      95 |
      96 |                 await expectSaga(

      at PactV3.executeTest (node_modules/@pact-foundation/src/v3/pact.ts:228:30)
      at Object.<anonymous> (.../Sagas.pact.test.ts:93:28)
```

**Comment by TimothyJones** [comment]
Thanks for the report! We're looking at moving away from neon, which will avoid this problem.

In the meantime, could you tell us more about this problem? What did you run to generate this error?

**Comment by mefellows** [comment]
Closing, Neon is gone.
