### ISSUE TITLE
Question on provider.verify() in consumer test?

### ISSUE THREAD

**Issue by MichaelSu1983** [pact-foundation/pact-js#65]
In examples/e2e/test/consumer.spec.js, I find the below test. 
```
describe('when interacting with Animal Service', () => {
    it('should validate the interactions and create a contract', () => {
      return provider.verify()
    })
  })
```

**Question: I don't understand what "provider.verify()" does? Is this mandatory to be included in a test? or I can remove it. After I remove it, I can still see log and pact file are generated and test is run as well.** 

I have a test like this:

```
describe('CRUD operations:', () => {
    describe('POST',() => {
      before((done) => {
        provider.addInteraction().then(() => { done(); });
      });

      it('POST', (done) => {
            done();
          })
          .catch(done);
      });

      it('successfully verifies', () => provider.verify());
    });

    describe('PUT',() => {
      before((done) => {
        provider.addInteraction().then(() => { done(); });
      });

      it('PUT', (done) => {
            done();
          })
          .catch(done);
      });

      it('successfully verifies', () => provider.verify());
    });

  });
```

**Comment by mefellows** [comment]
Thanks @MichaelSu1983, perhaps our documentation is not very clear on this.

The `provider.verify()` step is _key_ to the Pact tests. Verify checks that the interactions you've registered and expected to be present were in fact called by the function you were testing (e.g. `it('POST', ...)`).

Without it, you are registering expectations and creating a contract with those expectations in it, but you aren't sure if your code is actually a) calling the API(s) or b) sending the right data or c) using the data that is coming back. This is marginally better than pure documentation.

**Comment by MichaelSu1983** [comment]
Thanks @mefellows for the confirmation. Now I see. 

So one more thing, is the way I structure tests correct? 

should I return provider.verify() like the example, or leave "it('successfully verifies', () => provider.verify());" as separate test? or I can write it in one case "afterEach(() => provider.verify());"?

**Comment by mefellows** [comment]
It's a promise so you return it or explicitly complete it or you might not get the feedback if it passed or failed.

In terms of where it should go, It's up to you really, and your style.

It's probably nicer to have the `verify()` called in the same test scope so you know if it fails which test it relates to but some people like to keep them separate for readability etc.

**Comment by lirantal** [comment]
I understand the confusion here. I think we need to explain it better in the example and the docs.
