### ISSUE TITLE
Difficult to understand the Gitub framework for JS-Pact

### ISSUE THREAD

**Issue by ramchandrmishra** [pact-foundation/pact-js#66]
Hi,
I am new to webservices. Hence, finding difficult to understand the implementation of JS-Pact. Can you provide me some documents or links so that it I can understand how to proceed step by step for pact implementation.

**Comment by mefellows** [comment]
Have you looked at the Tutorials or Examples in this repository? https://github.com/pact-foundation/pact-js#tutorial-60-minutes
