### ISSUE TITLE
[V3] eachKeyLike doesn't ignore the key's value when matching

### ISSUE THREAD

**Issue by francislobo** [pact-foundation/pact-js#662]
### Software versions

- **OS**: Win 10
- **Consumer Pact library**:  "@pact_foundation/pact": "10.0.0-beta.34", "jest-pact": "0.9.0-beta.v3",  
- **Provider Pact library**:  pact-jvm-provider-gradle', version: '4.0.10'
- **Node Version**: v12.13.1

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

For an example data [shown here](https://gist.github.com/francislobo/329d85e843ab00f49840d7d1250785f1), the PACT generated using PACT JVM and PACT JS are different.
Specifically [this section](https://gist.github.com/francislobo/e85f651bb7dabe759f310c3b387c691b#file-theconsumer-theprovider-json-L43)generated from the eachkeylike matchers. This breaks the eachkeylike matcher where the actual key should be ignored and only the value (contents) of the key must be matched.

[Pact generated from JS](https://gist.github.com/francislobo/9a78a9939bfd0a66e690df80b76c196a)
[Pact generated from JVM](https://gist.github.com/francislobo/e85f651bb7dabe759f310c3b387c691b)  
NOTE: there are some extra pattern matchers on the request path of JVM PACT. I hadn't added them on the JS part as I was just getting started (I assume that shouldnt change how eachKeyLike works)

[JS code used to generate the contract](https://gist.github.com/francislobo/9f519c13973dc5b9b1edaf8163519c12)

### Actual behaviour

The PACTs should be identical for the eachkeylike section

### Steps to reproduce

_How can someone else reproduce this bug?_
The gist files has all the code required to reproduce this

### Relevant log files
none

[Slack conversation pertaining to this issue](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1620164070259800)

**Comment by mefellows** [comment]
Thanks @francislobo, I'll take a look at this on Monday.

**Comment by YOU54F** [comment]
Just noted that this is still an issue

Failing verification

https://github.com/pact-foundation/pact-js/runs/8017993797?check_suite_focus=true#step:4:7084

Comment in example code

https://github.com/pact-foundation/pact-js/blob/e2e_example_matchers/examples/v3/e2e/test/consumer.spec.js

**Comment by mefellows** [comment]
I think this might be related to #952 .

**Comment by mefellows** [comment]
Fixed in #1103 and https://github.com/pact-foundation/pact-js-core/pull/462. Latest release in the core going out shortly, which is a transitive dependency that will get pulled in with new installs/updates.
