### ISSUE TITLE
Pact doesn't get generated at the specified folder

### ISSUE THREAD

**Issue by carlosesh** [pact-foundation/pact-js#663]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. macOS BigSur 11.2.3
- **Consumer Pact library**:  @pact-foundation/pact 9.15.5
- **Node Version**: 10.18.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Pact gets added to Pact folder
It also fails sometimes and sometimes passes, it throws th

### Actual behaviour

Pact is not under the pact folder even when all verifications pass
Sometimes passes, other times fails, no apparent reason

### Steps to reproduce

Run The test
```js
import UserService from './UserService';
import mockFetch from '../../test-helpers/mockFetch/mockFetch';

const path = require('path');
const {Pact} = require("@pact-foundation/pact")

// Setup Pact
const mockProvider = new Pact({
    consumer: 'consumer',
    provider: process.env.PACT_PROVIDER ? process.env.PACT_PROVIDER : 'provider',
    log: path.resolve(process.cwd(), "logs", "pact.log"),
    dir: path.resolve(process.cwd(), "pacts"),
    logLevel: 'DEBUG',
});

describe('Pact with user/profile API', () => {
    beforeAll(() => mockProvider.setup());
    afterEach(() => mockProvider.verify());
    afterAll(() => mockProvider.finalize());

    describe('/service/user/profile', () => {
        describe('when the a get request is made to the user/profile endpoing', () => {
            const expectedBody = {id: 11, firstName: 'Jerry', lastName: 'Garcia'};
            beforeAll(() => {
                mockProvider.addInteraction({
                    state: 'there is a user',
                    uponReceiving: 'a request to get a user profile',
                    withRequest: {
                        path: '/user/profile',
                        method: 'GET',
                    },
                    willRespondWith: {
                        body: expectedBody,
                        status: 200,
                        headers: {Accept: "application/json"},
                    },
                })
            })

            it('will get the user details', () => {
                window.fetch = mockFetch(200, expectedBody);

                UserService.getProfile().then(res => {
                    expect(res).toBe(expectedBody);
                })
            })
        })
    })
})
```

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._
## When Tests passes but no pact is added to pact folder
```json
I, [2021-05-12T21:10:24.836974 #41319]  INFO -- : Verifying - interactions matched
I, [2021-05-12T21:10:24.843478 #41319]  INFO -- : Registered expected interaction GET /service/user/profile
D, [2021-05-12T21:10:24.844579 #41319] DEBUG -- : {
  "description": "a request to get a user profile",
  "providerState": "there is a user",
  "request": {
    "method": "GET",
    "path": "/user/profile"
  },
  "response": {
    "status": 200,
    "headers": {
      "Accept": "application/json"
    },
    "body": {
      "id": 11,
      "firstName": "Jerry",
      "lastName": "Garcia"
    }
  },
  "metadata": null
}
I, [2021-05-12T21:10:24.865385 #41319]  INFO -- : Cleared interactions
```
## When test fails (sporadic failures)
```json
I, [2021-05-12T21:39:00.126586 #45237]  INFO -- : Registered expected interaction GET /user/profile
W, [2021-05-12T21:39:00.128106 #45237]  WARN -- : Verifying - actual interactions do not match expected interactions. 
Missing requests:
	GET /user/profile



W, [2021-05-12T21:39:00.128349 #45237]  WARN -- : Missing requests:
	GET /user/profile



D, [2021-05-12T21:39:00.128320 #45237] DEBUG -- : {
  "description": "a request to get a user profile",
  "providerState": "there is a user",
  "request": {
    "method": "GET",
    "path": "/user/profile"
  },
  "response": {
    "status": 200,
    "headers": {
      "Accept": "application/json"
    },
    "body": {
      "id": 11,
      "firstName": "Jerry",
      "lastName": "Garcia"
    }
  },
  "metadata": null
}
I, [2021-05-12T21:39:00.226458 #45237]  INFO -- : Cleared interactions

```

**Comment by TimothyJones** [comment]
You will need to wait for your api call in your test- at the moment the promise is not waited on, so it’s creating a race condition.

**Comment by carlosesh** [comment]
> You will need to wait for your api call in your test- at the moment the promise is not waited on, so it’s creating a race condition.

So you mean something like?
```javascript
it('will get the user details', async () => {
    window.fetch = mockFetch(200, expectedBody);

    UserService.getProfile().then(res => {
        expect(res).toBe(expectedBody);
    })
})
```

**Comment by TimothyJones** [comment]
Yes, that’s right. This what it means in the checklist / FAQ where it mentions unhandled promises. I wish there was a way pact could detect this case, but since it’s happening outside pact, I don’t believe we can.

This is a common mistake, so if you can see a way to improve the wording to make the need to handle the promise clearer, I would welcome suggestions.

**Comment by mefellows** [comment]
What does `mockFetch` do? Your code actually needs to make the API call, so if this does what it sounds like, you don't want that behaviour, otherwise Pact will never see you making the correct call.

In either case, both of those logs indicate your code is not making the API call, so that is why it will never show up in the pact file.

I'll leave the ticket open for now, but it seems it's a test setup problem.

**Comment by TimothyJones** [comment]
Good catch, Matt! 

```
import mockFetch from '../../test-helpers/mockFetch/mockFetch';
```
^ This is supposed to be your actual client code, not a test helper / mock.

**Comment by TimothyJones** [comment]
Also, there are other unhandled promises in your test code - for example, `provider.addInteraction()` returns a promise, so you will need to change your code to either:

```
    beforeAll(() =>  // note the implicit return - your code currently has a bracket here so it is not returning the promise
                mockProvider.addInteraction({
```
or

```
    beforeAll(async () => {
                await mockProvider.addInteraction({
```

**Comment by TimothyJones** [comment]
For examples, check out the [examples folder](https://github.com/pact-foundation/pact-js/tree/master/examples). 

It looks like you might be using Jest - there's a helper that handles some of the boilerplate setup for you - have a look at the [example test here](https://github.com/pact-foundation/pact-js/blob/master/examples/jest/__tests__/index.spec.js) and [the documentation here](https://github.com/pact-foundation/jest-pact)

**Comment by carlosesh** [comment]
@TimothyJones I followed the approach mentioned for the `beforeAll`. So I'm handling that now.
Also, I understand that the purpose of PACT is to not mock api calls because it creates a mock server that handles the requests, however, when I call the method for getting the users it shows as `ReferenceError: fetch is not defined` and I looked almost everywhere and it was mentioned that it could only be tested if mocked.

Here is the method for reference.

```javascript
static async getProfile() {
    const response = await fetch('/user/profile', {
        method: 'GET',
        headers: {
            Accept: 'application/json',
        },
        credentials: 'same-origin',
        referrerPolicy: 'no-referrer',
    });

    if (response.status === 200) {
        return response.json();
    }

    throw new HTTPError(response.status);
}
```

And I couldn't really find one place where it says how to approach this with PACT. Any advice here?

**Comment by mefellows** [comment]
Right, so fetch isn't available in node, only in browser based environments
or tools that support it (I suspect Karma and the like do).

So if you don't mock it out, you'll get that problem.

If you do mock it out, you're not actually testing it (which is the whole
purpose here).

You could use Pact Web, but we really want to deprecate that.

I'll have to have a think tomorrow

**Comment by mefellows** [comment]
Maybe a polyfill like https://github.com/node-fetch/node-fetch could work?

**Comment by carlosesh** [comment]
Interesting, let me give it a shot @mefellows

**Comment by TimothyJones** [comment]
So this is a node environment vs browser environment thing- fetch is only available in the browser, but jest runs tests in a node environment. You’ll hit this issue with any testing library with jest, since it’s because of what environment you’re running the tests in (node), and not the testing library.

To fix this without modifying your code, you can use something like https://github.com/matthew-andrews/isomorphic-fetch . This will also give you the advantage that it gives a consistent api for fetch (as the link explains, fetch isn’t consistent across browsers- one of the reasons that raw fetch has fallen out of fashion a bit).

You won’t be able to mock the call to fetch and have your pact tests pass, because the pact mock server expects your code to actually hit it. 

If you test by mocking fetch and looking at the arguments, then you’re marking your own exam by checking that the arguments to the call were what you passed to the call. Pact gives more test confidence because you tell the pact server what your expectations are and then check that your call resulted in the behaviour you expect. It also has the added advantage that you can replay that request against the server during pact verification.

Does that help?

**Comment by TimothyJones** [comment]
Haha! Cross posted with Matt 😝

**Comment by carlosesh** [comment]
Well, turns out that it now works, I did have to include a fetch library for node as you mentioned but also  some work was done from the devs side, here is the working code if curious. (It also generates pacts).

```javascript
require('isomorphic-fetch');
import UserService from './UserService';

const path = require('path');
const {Pact} = require("@pact-foundation/pact")

// Setup Pact
const mockProvider = new Pact({
    consumer: 'crimsom-dark',
    provider: process.env.PACT_PROVIDER ? process.env.PACT_PROVIDER : 'hbr-ms-user',
    log: path.resolve(process.cwd(), "logs", "pact.log"),
    dir: path.resolve(process.cwd(), "pacts"),
    logLevel: 'DEBUG',
});

describe('Pact with user/profile API', () => {
    beforeAll(() => mockProvider.setup());
    afterEach(() => mockProvider.verify());
    afterAll(() => mockProvider.finalize());

    describe('/user/profile', () => {
        describe('when the a get request is made to the service/user/profile endpoint', () => {
            const expectedBody = {id: 11, firstName: 'Jerry', lastName: 'Garcia'};

            const successResponse = {
                body: expectedBody,
                status: 200,
                headers: {"Content-Type": "application/json",},
            }

            const request = {
                uponReceiving: 'a request to get a user profile',
                withRequest: {
                    path: '/service/user/profile',
                    method: 'GET',
                    headers: {Accept: "application/json"}
                }
            }

            beforeEach(async () => {
                const interaction = {
                    state: 'there is a user',
                    ...request,
                    willRespondWith: successResponse,
                }
                return mockProvider.addInteraction(interaction)
            })

            it('will get the user details', async () => {
                const baseUrl = mockProvider.mockService.baseUrl
                await UserService.getProfile({baseURL:baseUrl}).then(res => {
                    expect(res).toStrictEqual(expectedBody);
                })
            })
        })
    })
})
```
