### ISSUE TITLE
unable to install pact dependencies for any version

### ISSUE THREAD

**Issue by mangeshppatil** [pact-foundation/pact-js#664]
7 http fetch GET 200 https://nexus.opst.c1.vanguard.com/repository/vanguard_npm_group/@pact-foundation%2fpact-node 331ms
8 silly pacote range manifest for @pact-foundation/pact-node@^10.11.1 fetched in 373ms
5898 verbose stack Error: @pact-foundation/pact-node@10.12.2 postinstall: `node postinstall.js`
5898 verbose stack Exit status 1
5898 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
5898 verbose stack     at EventEmitter.emit (events.js:315:20)
5898 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
5898 verbose stack     at ChildProcess.emit (events.js:315:20)
5898 verbose stack     at maybeClose (internal/child_process.js:1048:16)
5898 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
5899 verbose pkgid @pact-foundation/pact-node@10.12.2

5905 error code ELIFECYCLE
5906 error errno 1
5907 error @pact-foundation/pact-node@10.12.2 postinstall: `node postinstall.js`
5907 error Exit status 1
5908 error Failed at the @pact-foundation/pact-node@10.12.2 postinstall script.

**Comment by TimothyJones** [comment]
This looks like a failure of the postinstall script, but doesn’t seem to have the details of the postinstall failure. Could you include the full log?

Also, this looks like a custom npm install- could you tell us more about that, please?

**Comment by individual-it** [comment]
please check if you have the `ignore-scripts` option enabled, it should be disabled, see #666
