### ISSUE TITLE
Expose FFI consumer API in pact-core

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#675]
Because we're dealing with a FFI, and we have a builder style DSL, we need a "handle" to a Rust object that crosses a memory boundary as we build up the interactions. The rust library has such an interface, and you can see the spike here: https://github.com/pact-foundation/pact-js/blob/spike/ffi-provider/src/native/consumerTest.js

I would suggest that `pact-core` simply expose the FFI interface (perhaps with additional error handling) and the actual DSL be built and managed in the `pact` lib.

Care will need to be taken here to have some nice error handling at the boundary, to catch segfaults and other nasties.

**Comment by mefellows** [comment]
PR matching via FFI: https://github.com/pact-foundation/pact-reference/pull/100
PR messages via FFI: https://github.com/pact-foundation/pact-reference/pull/101

**Comment by TimothyJones** [comment]
Do we _need_ a handle? The Ruby library built up the interaction as one object and then passed it over once it was complete - would a similar pattern work here?

**Comment by mefellows** [comment]
It works in a similar way, just at each separate request/response (description, path, query, status etc.) component rather than the entire request/response in one go. I can't remember why it was done this way than just accepting a giant blob of JSON. 

It could probably/possibly be done, but I'm not sure what advantages we'd get from it.

Of course, we don't need to use the handle itself for any builder pattern - we could queue it all up in local state and issue all of the calls in one go. So there is still some flexibility in it.

Maybe I'm missing something?
