### ISSUE TITLE
Pact how to do contract testing by hitting the real service url

### ISSUE THREAD

**Issue by hemantp2001** [pact-foundation/pact-js#69]
hi, 
In my application I am consuming a service and I want to generate a pact file by actually hitting the provider service url. Right now I notice that my current code is always going to Mock provider and then only Pact file is getting generated. This is due to the below PactproiderRule configuration
@Rule
	public PactProviderRule rule = new PactProviderRule("weatherprovider",
			PactSpecVersion.V3, this);
My run test code is as below: 
assertEquals(new WeatherService(rule.getConfig().url()).getMaxTemp().toString(),"{\"MaxTemp\":300.01}"); 

rule.getconfig() is always hitting mockprovider getconfig method.

Can someone please guide me on how to hit the real provider service url from my consuming application ?

**Comment by mefellows** [comment]
This looks to be Java code, did you mean to raise at the Pact JVM repo?

**Comment by mefellows** [comment]
Closing, no response.
