### ISSUE TITLE
Make it clear that scripts in package.json can be used for publish and can-i-deploy (etc)

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#711]
At the moment, most of the examples use a `publish.js` for publication. This isn't the most developer-friendly pattern, since it means you're essentially copying boilerplate tooling around each time you use pact.

We have binstubs exposed by pact-js-core/pact-node- we should:

1) Update the examples to have package.json scripts that use the binstubs directly
2) Improve the documentation to make it clear that you can use these binstubs

**Comment by TimothyJones** [comment]
Here's an example line using the binstubs directly https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/package.json#L11

We should change (at least) the instructions here: https://github.com/pact-foundation/pact-js#publishing-pacts-to-a-broker

**Comment by TimothyJones** [comment]
While we're there we could move all the credentials to environment variables too (since they're hard coded throughout)

**Comment by bethesque** [comment]
❤️

**Comment by danielglazer** [comment]
I would like to make the docs more beginner friendly and tackle this issue if possible. this looks like a good place to start. is this still relevant @TimothyJones ?

**Comment by TimothyJones** [comment]
Yes, I believe it is still relevant (I am no longer a maintainer)

**Comment by mefellows** [comment]
Thanks @danielglazer, that'd be great. I think the examples are all up to date now, it's just the documentation piece.

**Comment by mefellows** [comment]
This is done, closing!
