### ISSUE TITLE
examples/jest produces "Pact Binary Error: WARN: Ignoring unsupported matching rules"

### ISSUE THREAD

**Issue by jason-crawford-xio** [pact-foundation/pact-js#718]
_Thank YOU for your work on Pact_

### Software versions

- **OS**: 15.11
- **Consumer Pact library**:  master on 2021/07/27 e596c9,   or v9.16.0.
- **Provider Pact library**: N/A
- **Node Version**: v14.17.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

The examples provided with pact-js to run cleanly on the second run in addition to the first.   Or that the README.txt mention the behavior and why it should be expected and/or what additional corrective steps to take.

### Actual behaviour

Running the examples/jest twice results in

``` 
[2021-07-27 22:28:10.800 +0000] ERROR (57226 on Jasons-MacBook-Pro.local): pact-node@10.12.2: Pact Binary Error: WARN: Ignoring unsupported matching rules {"min"=>1} for path $['query']['catId'][]
WARN: Ignoring unsupported matching rules {"match"=>"type"} for path $['query']['catId'][][*]*
```

yet the test passes.

### Steps to reproduce

```
git clone https://github.com/pact-foundation/pact-js.git
cd pact-js
# git checkout v9.16.0.  # optional change of version
cd examples/jest
npm install
npm test
npm test
```

### Relevant log files

_Please let me know what relevant files you would need to see and how to produce them._

**Comment by TimothyJones** [comment]
This is the nicest edit to the issue template I’ve seen yet! ☺️

@bethesque Do you know about this warning? It happens in the query part of the URL. I think we’ve talked about it before, but I don’t remember the conclusion.

**Comment by TimothyJones** [comment]
The part of the example that generates the warning is:

```
          query: {
            "catId[]": Matchers.eachLike("1"),
          },
```

@jason-crawford-xio : I'm guessing a bit, but I _think_ what's happening here is that the core is refusing to match on type in the query string, since it must be a `string` inside the `eachLike` (otherwise it can't go in the query string). However, in this case, it *is* a string inside the `eachLike`. It feels like it would be better not to warn if the matcher is (correctly) specifying that the item must be a string.

**Comment by TimothyJones** [comment]
You're right that it would be good to mention this in the readme if it's not something that's easy to fix.

**Comment by jason-crawford-xio** [comment]
Perhaps this quirk could be an opportunity to hold the hands of the newbies trying the example and lead them on their first few steps of the journey learning about a part of pact and pact-js.

**Comment by TimothyJones** [comment]
Hah! Yes, indeed. It’s not great to have an unnecessary warning message in the example.

**Comment by bethesque** [comment]
I've tried to fix this so many times, I can't even remember. Every time I think I've fixed it, it seems to bounce back. I'm sorry, I just don't have time to look at it again right now, but I agree, it's a bad user experience.

**Comment by jason-crawford-xio** [comment]
@bethesque Thanks for the time you put in for the community.

**Comment by mefellows** [comment]
This issue is no longer present in the 10.x.x branch, closing.
