### ISSUE TITLE
Setup ARM builds for libpact_ffi

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#729]
To support the new M1 Mac, we need ARM builds on the `aarch64-apple-darwin` target.

We may be able to use GH Actions Mac agents if they are updated, or run AWS gravitron mac agents as a custom runner.

See also https://stackoverflow.com/questions/66849112/how-do-i-cross-compile-a-rust-application-from-macos-x86-to-macos-silicon

_examples using GH actions_
* https://github.com/ruffle-rs/ruffle/blob/26a1ffc0c9c95c705a30ced8aa86817ee9f27f7e/.github/workflows/release_nightly.yml
* https://github.com/helgoboss/realearn/blob/99d4e7745224cf0b3b1428b3473ace65ca8a453c/.github/workflows/macos-aarch64.yml

**Comment by mefellows** [comment]
Progress: https://github.com/pact-foundation/pact-reference/actions/runs/1120174922

**Comment by TimothyJones** [comment]
This is awesome! Should it be on `pact-reference`, though?

**Comment by mefellows** [comment]
Yes it probably should, I just converted the task on the project board. I'll move now.
