### ISSUE TITLE
Use matchers when verifying metadata

### ISSUE THREAD

**Issue by mduesterhoeft** [pact-foundation/pact-js#745]
### Feature description

Since [v10.0.0-beta.45](https://github.com/pact-foundation/pact-js/releases/tag/v10.0.0-beta.45) `metaData` present in the consumer contract is verified. 

It would be great if we could also use matches when verifying metadata.

Something like this should be working.

```
  "messages": [
    {
      "matchingRules": {
        "body": {},
        "metaData": {
          "$.traceId": { "combine": "AND", "matchers": [{ "match": "type" }] }
        }
      },
      "metaData": {
        "traceId": "8bf558a2-0b0d-457e-b1b2-75800352d637"
      }
    }
  ]
```
### Use case

The metaData object contains a `traceId` which is change whenever the consumer contract is published. The verification should just make sure that the field exists and carries a string. A match by value is not useful.

**Comment by mefellows** [comment]
Thanks @mduesterhoeft. I just took a quick look at the source and it seems matchers should be applied.

Could you please set the log level to trace and share an appropriately redacted log? That will help us diagnose what went wrong.

**Comment by mefellows** [comment]
Actually, on closer inspection that output is a bit confusing - `metaData` should actually be `metadata`.

The core knows how to read in both `metaData` and `metadata` at the interaction level, but not for the matching rules.

But it shouldn't actually be generating that. This might be a bug in Pact JS (not sure _how_ yet) or in the version of the FFI we are using.

**Comment by TimothyJones** [comment]
Can you tell us which pact framework + version produced the pact file?

**Comment by mduesterhoeft** [comment]
@mefellows do you already have an idea on when you can fit this in. If you explain how you envision a solution I would also be happy to give it a try and come up with a PR.

**Comment by mefellows** [comment]
Thanks @mduesterhoeft, apologies for the delay in my response.

I don't have the answer right now I'm afraid. I just had a look through the rust source code and it seems any references to "metaData" have been addressed.

With the next release of the beta, I'm hoping this problem should be resolved. 

cc: @uglyog as he may be able to provide a little more detail.

**Comment by mefellows** [comment]
In the meantime, i'd remove it from your consumer test until we fix the validation (which I assume you're probably doing!) or you could potentially post-process the pact file to replace `metaData` with `metadata` to see if it gets picked up properly.

**Comment by NiklasEi** [comment]
> In the meantime, i'd remove it from your consumer test until we fix the validation (which I assume you're probably doing!) or you could potentially post-process the pact file to replace `metaData` with `metadata` to see if it gets picked up properly.

We tried it with `metadata`, but then the metadata is ignored. At the moment we just hardcode one value.

**Comment by mefellows** [comment]
👍

**Comment by mduesterhoeft** [comment]
> With the next release of the beta, I'm hoping this problem should be resolved.

@mefellows Hi there - do you have any update for me on this topic? I am also totally ready to get my hands dirty to fix this issue with a PR from my side. But I would need an initial pointer, solution idea to get started.

**Comment by mefellows** [comment]
Thanks @mduesterhoeft. I'm not sure if it has been resolved.

You could

1. run a quick test on the most recent beta just to check if it's been fixed
2. if not, take a look around at https://github.com/pact-foundation/pact-reference/tree/master/rust. I haven't been in the rust core for a while, but @uglyog might be able to give you some advice (perhaps worth chatting with us in [this](https://pact-foundation.slack.com/archives/C02BXLDJ7JR) channel)

**Comment by mduesterhoeft** [comment]
Thanks @mefellows 

> run a quick test on the most recent beta just to check if it's been fixed
I did that before bothering you again. I have the same issue with the latest beta.

If the solution would be in the rust core I am afraid I cannot help. I was hoping that this was in the js world still.

**Comment by Kampfmoehre** [comment]
Hi, I have a similar problem, I am using matchers in message consumer metadata like this

```js
.withMetadata({
  contentType: "application/json", // Working
  correlationId: Matchers.string("nCB3FYqJIugLvQZ2b1dV") // Not Working
})
```
but the generated Pact file contains only the example value
```json
{
  "consumer": {},
  "messages": [
    {
      "contents": {
        // ...
      },
      "matchingRules": {
        "body": {
          "$.name": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          }
        }
      },
      "metadata": {
        "contentType": "application/json",
        "correlationId": "nCB3FYqJIugLvQZ2b1dV",
      },
      "providerStates": [
        {
          // ...
        }
      ]
    }
  ]
}

```
This causes the provider tests to fail since the correlationId is a generated value that changes each time, the test output looks like this
```
    1.1) has matching metadata
           Expected message metadata 'correlationId' to have value '"nCB3FYqJIugLvQZ2b1dV"' but was '"YUqJ2pQhyYPqS5k1W5-5"'
```

Both use PactJS 10.0.1. I have tried MatchersV3 instead but that gives my TypeScript errors since the withMetdata method expects Matchers. Is there anything else I can provide to help with this?

**Comment by TimothyJones** [comment]
> my TypeScript errors since the withMetdata method expects Matchers

This probably is a mistake in the pact v10 types - I think it would be more correct to give a V3 matcher there. However, I believe the `string` matcher is identical in both spec versions, so it's not the source of the problem (if you want to confirm it doesn't fix the problem, you can try `as Matcher<string>`).

Update: I think I found the issue:

https://github.com/pact-foundation/pact-js/blob/master/src/messageConsumerPact.ts#L178

Could you try patching that line in your node_modules? I'm guessing a bit, but I think it should say:

`typeof v === 'string' ? v : JSON.stringify(v)`

@mefellows if this does fix it, I think pact-js should just pass the whole thing down to the core, and the core should do the conversion.

**Comment by Kampfmoehre** [comment]
@TimothyJones I tested your line and Pact json now looks like this
```json
{
        "correlationId": "{\"value\":\"nCB3FYqJIugLvQZ2b1dV\",\"pact:matcher:type\":\"type\"}"
}
```

**Comment by TimothyJones** [comment]
Ah 😅 apologies. 

I think the next culprit is in the rust core. I’ll leave this for a maintainer to look at.

**Comment by rholshausen** [comment]
@Kampfmoehre That is wrong, there are only matching rules for the body
```
"matchingRules": {
        "body": {
          "$.name": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          }
        }
      },
```

**Comment by rholshausen** [comment]
The matching rules for the metadata are not being created in the Pact file.

**Comment by mefellows** [comment]
> The matching rules for the metadata are not being created in the Pact file.

Does the rust core support matching rules on the metadata? I think that's the question.

**Comment by rieckpil** [comment]
Can anyone confirm that matching rules are supported? I'm struggling to get the matching rules for metadata for an asynchronous message (Pact V4) working. The pact file properly generates matching rules for the metadata to do some type comparisons, e.g.:

```
{
  "consumer": {
    "name": "test"
  },
  "interactions": [
    {
      "matchingRules": {
        "body": {
          "$.businessUnitGroupId": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          }
        },
        "metadata": {
          "Insert-Time": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          }
       }
   },
      "metadata": {
        "Correlation-Id": "bc0c3b06-2123-4824-a866-25767a060249",
        "Insert-Time": "2022-05-26T06:34:24.123Z",
        "Tenant-Id": "CIR7nQwtS0rA6t0S6ejd",
        "contentType": "application/json"
      },
```

But somehow the trace log state there is no matching rule defined and fall back to an equality check

```
2022-12-07T14:07:34.829777Z TRACE ThreadId(02) pactffi_verifier_execute{handle=0x128e1d4d0}:verify_interaction{interaction="a receipt layout with mandatory attributes"}: pact_models::matchingrules: matcher_is_defined: for category metadata and path ["Insert-Time"] -> false
2022-12-07T14:07:34.829780Z DEBUG ThreadId(02) pactffi_verifier_execute{handle=0x128e1d4d0}:verify_interaction{interaction="test"}: pact_matching::json: JSON -> JSON: Comparing '"2022-05-26T06:34:24.123Z"' to '"2022-12-07T14:07:34.807Z"' using Equality -> Err(Expected '2022-05-26T06:34:24.123Z' to be equal to '2022-12-07T14:07:34.807Z')
```

**Comment by mefellows** [comment]
Could you please re-test? The latest version should support this now.

**Comment by TezzM0** [comment]
This still seems to be happening for me with version 12.1.1.

When I include metadata in the pact like so:
```
      .withMetadata({
        'message-id': uuid("a0d38a09-f2da-46cf-8267-3cd575056606"),
        'message-type': 'create-product',
      })
```

It generates a pact contract that looks like this:
```
{
      "contents": {
        "body": {
          "createdAt": "2015-08-06T16:53:10.123+01:00",
          "id": "6551bfe2a3168487de1773dd",
          "updatedAt": "2015-08-06T16:53:10.123+01:00"
        },
        "headers": {
          "message-id": "5892a89d-c665-4dc2-939a-8a0d1f7744cc",
          "message-type": "create-product"
        }
      },
      "description": "A product created event",
      "matchingRules": {
        "body": {
          "$.body": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          },
          "$.body.createdAt": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d(:?[0-5]\\d)?|Z)$"
              }
            ]
          },
          "$.body.id": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "^[a-fA-F0-9]{24}$"
              }
            ]
          },
          "$.body.updatedAt": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d(:?[0-5]\\d)?|Z)$"
              }
            ]
          },
          "$.headers": {
            "combine": "AND",
            "matchers": [
              {
                "match": "type"
              }
            ]
          },
          "$.headers['message-id']": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$"
              }
            ]
          }
        }
      },
      "metadata": {
        "contentType": "application/json",
        "message-id": "a0d38a09-f2da-46cf-8267-3cd575056606",
        "message-type": "create-product"
      }
    },
```

The header matching rules are now included in the pact, which I didn't see happening previously (not sure which version I last tried with, sorry) - but they aren't used by the provider during verification:

```
A product created event (1s 994ms loading, 3ms verification)
    generates a message which
      includes metadata
        "message-type" with value "create-product" (OK)
        "message-id" with value "a0d38a09-f2da-46cf-8267-3cd575056606" (FAILED)
        "contentType" with value "application/json" (OK)
      has a matching body (OK)

Pending Failures:
1) Verifying a pact between repeat-rewards and product-catalogue - A product created event
    1.1) has matching metadata
           Expected message metadata 'message-id' to have value '"a0d38a09-f2da-46cf-8267-3cd575056606"' but was '"569079cd-611c-47a0-9968-ddf88ac6badc"'
```

It still requires the UUID to match exactly, rather than using the regex specified in the matchers.

**Comment by mefellows** [comment]
I think this would be resolved via this change: https://github.com/pact-foundation/pact-reference/pull/343/files

**Comment by ferrisbuhler** [comment]
I checked with pact-js 12.1.2 and 12.2.0. For both versions
* `MessageConsumerPact` refuses to accept V3 matchers (such as `MatchersV3.uuid()` in metadata
* no matchers are generated in the "Pact" contract for the metadata.

Any news on this? Any workarounds to be recommended?

**Comment by mefellows** [comment]
This should be fixed now - thanks all!
