### ISSUE TITLE
Add support for publishing verification results with a branch using the pact-ruby-standalone

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#750]
The Pact Broker now supports branches as first class entities. You can read more about this here: https://github.com/pact-foundation/docs.pact.io/blob/feat/deployments-and-releases/website/blog/2021-07-04-why-we-are-getting-rid-of-tags.md

To allow users to use this feature:

* Upgrade the pact-ruby-standalone to at least version `1.88.70`
* Add an appropriately prefixed "branch" property to the user facing interface (make it match the existing provider name, tag, and version properties)
* Pass the branch through to the pact provider verifier CLI using the parameter `--provider-version-branch`

**Comment by mefellows** [comment]
Added PRs to the two core packages that need to support this for the 2 pact js packages to support it.

I tested locally with the pact-node branch (the main/most commonly used one):

![Screen Shot 2021-11-15 at 3 42 51 pm](https://user-images.githubusercontent.com/53900/141723664-4d65cd7a-5450-4f19-a24f-1d5f8043f80e.png)

**Comment by mefellows** [comment]
Releasing new version with support for this.
