### ISSUE TITLE
Proposal: Convert to TypeScript

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js#76]
We already have TypeScript bindings, which are neat, it's time to make the whole code base type safe!

I'd think we need to look at the following:

- [x] Convert all code to TypeScript!
- [x] Make all tests pass
- [x] Upgrade to latest `@pact-foundation/pact-node` 5.1.x
- [x] Creating the scaffolding to enable a staged migration from JS => TS
- [x] Modifying the TravisCI builds to publishing ES5 compatible code
- [x] Updating WebPack configuration to parse TS
- [x]  Moving parts of pact-node to this repository, or adding type declarations to that repository
- [x] #92
- [x] #117
- [x] All examples pass and are run as part of CI
- [x] Bring across the standard release process from master
- [x] Remove old "docs" folder (TS annotations are live and better)
- [x] Removing the old type declarations
- [x] Port latest karma examples (a62d00f6ae3f5eee5c7ffbf9f889e47d8c2e17c9 and 93cba30da3aca81d3e5f0dc79dd972beda89c8fd)
- [x] Add in type checks / guards for common native JS scenarios
- [x] Ensure style/formatting consistent throughout (e.g. semi-colon use, spacing, editor config etc. - update lint rules and ensure they are applied)
- [x] Ensuring compatibility with `pact-web`, refactor common code and create test for `pact-web` to prove it
- [x] Review #119 and make any backwards incompatible change as part of this
- [x] #120 More matchers?
- [x] Review tests
- [x] Fix any remaining _TODOs_
- [x] Release under Pact Foundation (#116)
- [x] Review public facing API (Clean up packaging)
 - [x] Write TS integration test

Changes from master that need to come across before this becomes a thing:

- [x] #115 
- [x] #114 
- [x] #101 
- [x] #99 
- [x] #96
- [x] #80 
- [x] #127 #126

**Comment by mboudreau** [comment]
What's the progress on this?  I might be able to use my experience in TS to help out.

**Comment by mefellows** [comment]
It's probably around 90% complete - see https://github.com/pact-foundation/pact-js/tree/feat/typescript.

I think I have the next couple of nights free (incl. tonight) so after tending to other issues/PR's etc. i'll get it into as good a shape as I can and then perhaps we can collab on getting it over the line?

**Comment by mboudreau** [comment]
Sounds good bud.

**Comment by mefellows** [comment]
@mboudreau see above checklist. 

I think we're at the point where it's about adding all of the type / other guards in, getting some cleanliness happening and getting a beta `5.x.x` out to start testing with other components / implementations.

**Comment by mefellows** [comment]
Closing: Beta now available at https://www.npmjs.com/package/@pact-foundation/pact and code merged to master for any cleanup.
