### ISSUE TITLE
Please update pact publication examples to set the branch instead of --tag-with-git-branch

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#777]
If I have time, I'll see if I can do this, but would love some new contributor help!

**Comment by TimothyJones** [comment]
Why do we need this? Isn’t it better to tag with the git branch?

**Comment by TimothyJones** [comment]
If this is about setting the branch rather than the tag, isn't that change better made in the CLI?

**Comment by mefellows** [comment]
See https://docs.pact.io/pact_broker/branches/.

**Comment by bethesque** [comment]
It's already in the CLI. If we're officially deprecating the pact publishing javascript wrapper, then I guess there's not much point adding it, but if it's still supported (but not encouraged) then it would be good to add it.

**Comment by bethesque** [comment]
> Isn’t it better to tag with the git branch?

No, it's better to `--branch` with the git branch. Using tags for branches is no longer recommended.

**Comment by TimothyJones** [comment]
Is there —mark-branch-from-git? It would be ideal if the CLI can do this, I think.

**Comment by bethesque** [comment]
`--auto-detect-version-properties`

**Comment by TimothyJones** [comment]
Oh that’s great! We’ll use that :)

**Comment by TimothyJones** [comment]
Fixed!
