### ISSUE TITLE
Pact JS's disk install size is very large

### ISSUE THREAD

**Issue by pastelsky** [pact-foundation/pact-js#780]
I noticed that `pact` and its dependencies occupy 100+ MB in our `node_modules` folder. This is primarily because `@pact-foundation/standalone` ships with ruby runtimes for all possible platforms. 

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OSX 10.11.5
- **Consumer Pact library**:         Pact JS 4.3.2
- **Node Version**: v12.12

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Pact JS occupies a reasonable size on disk, and only ships with code that will be executed

### Actual behavior

<img width="198" alt="Screenshot 2021-12-02 at 10 01 52 PM" src="https://user-images.githubusercontent.com/8946207/144463316-871426a6-f94a-4a6d-9956-a0ec302eeadb.png">

### Steps to reproduce

Install `pact@4.3.2`, do a `du -sh` in the installed directory.

**Comment by TimothyJones** [comment]
Please upgrade to the latest version.

**Comment by mefellows** [comment]
This version is super old > 4 years in fact. Any reason why you're not on a newer version?

Note the package changed from just `pact` to `@pact-foundation/pact` after version 4.
