### ISSUE TITLE
update nestjs examples to work with new nestjs-pact (support nestjs v8)

### ISSUE THREAD

**Issue by omermorad** [pact-foundation/pact-js#801]
### Feature description
Update NestJS examples to work with new `pact-nestjs`

**Comment by omermorad** [comment]
I'm working on a PR #800 which updates to the new `nestjs-pact` version (support nestjs v8.0)

References from `nestjs-pact` repo:
https://github.com/omermorad/nestjs-pact/pull/9
https://github.com/omermorad/nestjs-pact/issues/8

**Comment by mefellows** [comment]
Closed as these changes are merged - thanks!
