### ISSUE TITLE
Shouldn't need to URL encode name of provider in verification settings

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-js#81]
In the documentation for the js workshop, the provider name needed to be URL encoded. I think this should be handled by the publish code, not by the user.

https://github.com/DiUS/pact-workshop-js/#step-13---using-a-pact-broker
```
let opts = {
  provider: 'Our%20Provider',
  providerBaseUrl: 'http://localhost:8081',
  providerStatesUrl: 'http://localhost:8081/states',
  providerStatesSetupUrl: 'http://localhost:8081/setup',
  pactBrokerUrl: 'https://test.pact.dius.com.au/',
  tags: ['prod'],
  pactBrokerUsername: 'dXfltyFMgNOFZAxr8io9wJ37iUpY42M',
  pactBrokerPassword: 'O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1',
  publishVerificationResult: true,
  providerVersion: '1.1.0'
}
```

**Comment by mefellows** [comment]
Agree, that's a bit shit of us.

**Comment by mefellows** [comment]
I've just reviewed this and it's not actually necessary. Although the README has the escaping, it's actually not in the code, and the code works just fine. 

I've updated that README to correct this.

Closing.
