### ISSUE TITLE
Pact accepts spec 3 but it doesn't do it

### ISSUE THREAD

**Issue by danymarques** [pact-foundation/pact-js#838]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OSX 12.2.1_
- **Consumer Pact library**: Pact JS v9.17.2
- **Provider Pact library**: 
- **Node Version**: v14.19.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Pact should throw an error if when it is initialized with the spec version set to 3.

### Actual behaviour

Pact happily accepts the version 3 of the spec and writes ```  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    }
  }``` in the contract file. However Pact JS doesn't produce the contract in v3.

### Steps to reproduce

- [ ] Clone https://github.com/danymarques/pact-js
- [ ] ```cd examples/jest```
- [ ] ```npm ci```
- [ ] ```npm test```

**Comment by TimothyJones** [comment]
Jest-pact just passes the variable along- the problem is in pact-js, which should probably check the variable before passing it along to the ruby binary. 

I’m surprised it writes spec version 3 into the generated contract, though.

**Comment by TimothyJones** [comment]
^ I've opened a PR which improves the situation by throwing an error when something other than `spec: 2` is used.
