### ISSUE TITLE
Setting up pact tests for NestJs

### ISSUE THREAD

**Issue by jithinjosejacob** [pact-foundation/pact-js#863]
I am trying to set up pact tests for nestjs examples provided

https://github.com/pact-foundation/pact-js/tree/master/examples/nestjs-provider

https://github.com/pact-foundation/pact-js/tree/master/examples/nestjs-consumer

1) Run npm ci on nestjs-provider

2) Then run npm start on nestjs-provider

3) Run npm ci on nestjs-consumer

4) Then run npm start on nestjs-consumer

_Actual Result_

I could see below error on localhost:8080

{"statusCode":404,"message":"Cannot GET /","error":"Not Found"}

Is this somehow related to missing upgrade - https://github.com/pact-foundation/pact-js/pull/800

**Comment by YOU54F** [comment]
When you start the consumer, it is looking for the provider based on this

`process.env.API_HOST || "http://localhost:8081"`, so if you haven't set an env var, it default.

https://github.com/pact-foundation/pact-js/blob/cadfceefdefaeec6a1abc8e71d36edc9f2c50d9a/examples/nestjs-consumer/src/app.service.ts#L9

The provider starts on port 3000

https://github.com/pact-foundation/pact-js/blob/cadfceefdefaeec6a1abc8e71d36edc9f2c50d9a/examples/nestjs-provider/src/main.ts#L9

in the pact tests, you don't start both code bases together, and this example wasn't to represent this.

If you set your `API_HOST` env var to localhost:3000 you can see the app running with both the provider and consumer, but that is generally out of scope of examples in this main repository. The main point we are trying to showcase is the Pact testing framework on either the consumer or provider side, which is testable in isolation.

**Comment by YOU54F** [comment]
> Is this somehow related to missing upgrade - #800

It's not, although I have got that on my list of things to pick up, but requires upstream changes in the nestjs-pact

**Comment by jithinjosejacob** [comment]
okk, let me try it out, i just need a simple example for nestjs

**Comment by jithinjosejacob** [comment]
Would be great if you can add a readme to this examples, good for starters to get it setup quickly

**Comment by YOU54F** [comment]
Hi @jithinjosejacob thanks for all the feedback,

Hope these examples help someone along the way

https://github.com/YOU54F/nestjs-pact-test
