### ISSUE TITLE
GLIBC version issue from pact js vs beta node:14-slim, node:16-slim

### ISSUE THREAD

**Issue by harris-linktree** [pact-foundation/pact-js#888]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. public docker image node14-slim/node16-slim
- **Consumer Pact library**:  "10.0.0-beta.60"
- **Provider Pact library**: 
- **Node Version**: 14/16

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

contract tests are running

### Actual behaviour

complaints about GLIBC version from node 14/16 container. however, node-18 slim works as expected
```
    /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.so)
```

### Steps to reproduce
[pact-demo.zip](https://github.com/pact-foundation/pact-js/files/9067684/pact-demo.zip)

1 download pact-demo.zip
2 unzip then go do unziped folder
3 run `docker build --platform linux/amd64 -t test-pact-beta .` (for mac m1)
 or run `docker build  -t test-pact-beta .`
4 after build image, run `docker run test-pact-beta`

_How can someone else reproduce this bug?_
same as above

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._

**Comment by mefellows** [comment]
Thanks @harris-linktree , much appreciated.

**Comment by mefellows** [comment]
OK so I took a look at this tonight and the reason is that we need a version of libc >= 2.29.

I've updated our official Docker [guidance](https://docs.pact.io/docker) to clarify that. We'll also see if it's possible to link against a slightly older version to increase compatibility

**Comment by mefellows** [comment]
Closing - we now link to 2.24 as per the linked issue above.
