### ISSUE TITLE
'There was a problem starting the mock service: %s', resp.text E   RuntimeError: ('There was a problem starting the mock service: %s', '<HTML>\r\n\t\t\t\t<HEAD>\r\n\t\t\t\t\t<TITLE>Network Error

### ISSUE THREAD

**Issue by ShashankAmbastha1** [pact-foundation/pact-js#889]
I am getting 'Network error' while starting pact service. is anyone having solution

_Thank you for reporting an issue! We appreciate it very much. Issues are a big input into the priorities for Pact-JS development_

_NOTE: If your issue is a how-to question, it is probably better asked in the pact-foundation slack channel, https://slack.pact.io/ _

_This is the template for issues that aren't feature requests or bug reports. If your issue is a feature request or bug report, please use the relevant template from https://github.com/pact-foundation/pact-js/issues/new/choose - these will cover off the most common questions we ask and speed up a fix_

_If you're reading this thinking "Hmmm, it is bug report/feature request, but neither of those templates work for what I want to report", then please feel free to ignore the template in whatever way you think best suits your issue. We trust you, you're awesome_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

**Comment by mefellows** [comment]
Can you please check your proxy settings? My guess is there is a proxy interfering with the requests. See the troubleshooting guide in the readme
