### ISSUE TITLE
rename and upgrade @pact-foundation/pact-node@10.17.2 to @pact-foundation/pact-core@13.x.x

### ISSUE THREAD

**Issue by rbedemann** [pact-foundation/pact-js#890]
### Checklist

Before making a feature request, I have: 

- [x] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js/issues?q=is%3Aissue)
- [x] Checked the documentation to see if it is possible to do what I want already 

### Feature description

`@pact-foundation/pact-node` apparently got renamed in version [10.12.0](https://github.com/pact-foundation/pact-js-core/compare/v10.11.11...v10.12.0) to `@pact-foundation/pact-core`. `pact-js` currently uses version [10.17.2](https://github.com/pact-foundation/pact-js/blob/181d8a28f1aa55502d6103cadb6ae4b2c52f7ebf/package.json#L96) while version [13.6.2](https://github.com/pact-foundation/pact-js-core/releases/tag/v13.6.2) is already available. We'd love to see this package being renamed and upgraded.

### Use case
As we're currently facing some issue with our corporate proxy while downloading the pact binary (back in the days done via needle), we hope this version upgrade to the latest pact-core version could resolve this issue.

**Comment by mefellows** [comment]
Thanks for submitting a PR @rbedemann, much appreciated.

**Comment by mefellows** [comment]
See #891 for more.
