### ISSUE TITLE
Module not found: Error with React 17+ in Cypress

### ISSUE THREAD

**Issue by Maxim-Filimonov** [pact-foundation/pact-js#892]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Mac OSX 12.4
- **Consumer Pact library**: _@pact-foundation/pact-web@9.18.1
- **Provider Pact library**: N/A
- **Node Version**: v16.15.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Being able to require pact-web in pact tests to use `Matchers` when running cypress tests.

### Actual behaviour

Error is thrown:
```
Module not found: Error: Can't resolve '@pact-foundation/pact-web' in '/Users/maxim/src/conpago/example-cypress-pact-from-scratch/cypress/e2e'
resolve '@pact-foundation/pact-web' in '/Users/maxim/src/conpago/example-cypress-pact-from-scratch/cypress/e2e'
  Parsed request is a module
  using description file: /Users/maxim/src/conpago/example-cypress-pact-from-scratch/package.json (relative path: ./cypress/e2e)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
```

### Steps to reproduce

_How can someone else reproduce this bug?_
In one terminal:
```
npm install
npm start
```
In second terminal
```
npm cypress-run
```

[Reproduction repository](https://github.com/Maxim-Filimonov/reproduction-cypress-pact-web-cannot-resolve)

In this [example](https://github.com/pactflow/example-consumer-cypress) its working with cypress. I tried updating to the latest cypress, and it still works. I presume maybe issue is related to changes to pact-web or react itself. Not sure 🤔

**Comment by Maxim-Filimonov** [comment]
After further investigation. I singled out the [commit](https://github.com/Maxim-Filimonov/reproduction-cypress-pact-react-16/commit/9dd3113e165d773dfe839d24fa95978507c8ceed) which fails it in another repo with old version of react(16). 

Will try react 17.

**Comment by mefellows** [comment]
Support for pact web was dropped in: 9.18.0

https://github.com/pact-foundation/pact-js/compare/v9.17.3...v9.18.0

You should pin the version of pact web you need to versions prior to this.

**Comment by Maxim-Filimonov** [comment]
Ah ) Thanks for explaining.
Is there any reason for that? Wondering cause isn't it a legitimate use case to use pact with cypress this way? Or I'm missing something.

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-js/issues/626 for background.

You can still use Cypress and Pact together. 

This is an example where you can create a small plugin for Cypress to use it within tests: https://github.com/pactflow/example-consumer-cypress

We also have a Cypress Adapter (https://docs.cypress.io/plugins/directory) that will automatically take your Cypress mocks and make a contract from there. This is for use to work with Pactflow's bi-directional contract testing feature, but I wouldn't use it directly with Pact (because provider states and matchers won't be generated).
