### ISSUE TITLE
V3 Consumer test can never fail

### ISSUE THREAD

**Issue by klassm** [pact-foundation/pact-js#904]
### Software versions

- **OS**: Mac OSX 12.4
- **Consumer Pact library**: Pact JS 10.0.0 (@pact-foundation/pact)
- **Provider Pact library**: Pact JS 10.0.0 (@pact-foundation/pact)
- **Node Version**: 16.14.2

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures **(removed from readme?)**
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [x] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

When a consumer test runs and fails, the whole test case fails.

### Actual behaviour

The result of the expectation is ignored.

### Steps to reproduce

Please see the reproducing repository at [https://github.com/klassm/pact-consumer-can-never-fail/blob/master/tests/contract/bla.spec.ts](https://github.com/klassm/pact-consumer-can-never-fail/blob/master/tests/contract/bla.spec.ts).

In effect create a consumer test which does nothing more than an expectation that always fails. The test always goes green, whereas actually it should always be red.

```ts
describe('Some test that never fails', () => {
  const pactOptions: PactOptions = {
    dir: path.resolve(process.cwd(), 'tests', 'contract', 'pacts'),
    log: path.resolve(process.cwd(), 'tests', 'contract', 'logs', 'somelog.log'),
    consumer: 'Consumer',
    provider: 'Provider',
    logLevel: 'trace',
  };

  const provider = new PactV3(pactOptions);

    it('minimal', async () => {
      await provider.executeTest(async () => {
        expect(true).toBe(false);
      });
    });

    it('minimal returning', () => {
      return provider.executeTest(async () => {
        expect(true).toBe(false);
      });
    });
});
```

### Relevant log files

Please see the outcome of the [Github Actions](https://github.com/klassm/pact-consumer-can-never-fail/runs/7555255892?check_suite_focus=true)

You can also see the expectation failing in the log, but the build being still green afterwards.

**Comment by mefellows** [comment]
Thanks for picking this up. I... don't know how this wasn't detected given the length was actually out in the wild prior to major release. `v10.0.01` now live!
