### ISSUE TITLE
pact-web.js file is missing when installing @pact-foundation/pact-web through yarn

### ISSUE THREAD

**Issue by kaashan** [pact-foundation/pact-js#915]
Hi,

In our angular project, we have added "@pact-foundation/pact-web": "^9.16.1" under devDependencies. When we install the project dependencies through yarn (installed as a local dependency), it is observed that pact-web.js file (and pact-web.js.map) is not present (under node_modules/@pact-foundation/pact-web folder) in the downloaded package. When we perform an install through npm install the file is present.

**Use case:**
a) install yarn as a local dependency inside angular project by running command _npm install --no-package-lock --no-shrinkwrap --no-save yarn@1.22.19_
b) install project dependencies through yarn by running command _node_modules/yarn/bin/yarn install --ignore-engines_
c) Then we run a script(defined in angular.json file) through yarn which points to pact-web.js file under node_modules/@pact-foundation/pact-web folder

```
"generate-pacts": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
        "main": "app/pact-test-main.ts",
        "polyfills": "app/polyfills.ts",
        "karmaConfig": "./karma.conf.pact.js",
        "tsConfig": "app/tsconfig.pact.json",
        "scripts": [
          "node_modules/@pact-foundation/pact-web/pact-web.js"
        ]
      }
 },
```

This results in below error as the file could not be found:
**An unhandled exception occurred: Script file node_modules/@pact-foundation/pact-web/pact-web.js does not exist.**

Do we know why the pack-web.js file went missing when installed through yarn? Is there some additional config that needs to be in place for the pact-web.js file to have been generated?

**Software versions**
OS: Mac OS BgSur v11.6
Node version: v12.22.12
NPM version: v6.14.16
Angular version: v9
yarn version: v1.22.

_pact-web package folder structure when installed through yarn_
<img width="236" alt="pact-web_folder_contents_using_yarn_install" src="https://user-images.githubusercontent.com/22172255/184160502-f402e9b7-b041-49b0-ba0e-50008ae86310.png">

_pact-web package folder structure when installed through npm_
<img width="236" alt="pact-web_folder_contents_using_npm_install" src="https://user-images.githubusercontent.com/22172255/184160515-7d0d3afa-b716-4134-8e38-15d0983b6468.png">
19

**Comment by mefellows** [comment]
Pact Web is no more - please see #626 and the release notes.

You'll need to pin Pact to the specific version you need if you want to keep using it.
