### ISSUE TITLE
10.X.X publishes verification results when publishVerificationResult is set to false

### ISSUE THREAD

**Issue by adamwitko** [pact-foundation/pact-js#917]
### Software versions

- **OS**: Mac OSX 12.3
- **Consumer Pact library**: @pact-foundation/pact@10.1.0
- **Provider Pact library**: @pact-foundation/pact@10.1.0
- **Node Version**: 18.7.0

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [X] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Setting `publishVerificationResult` to `false` to not publish the verification results to the broker.

### Actual behaviour

Verification results are being published to the broker.

### Steps to reproduce

- Set `publishVerificationResult: false` in your Verifier options
- Execute
- Go to your Pact Broker to see that your verification run has uploaded a new set of results

**Comment by mefellows** [comment]
Apologies for the delay in responding, I believe the latest core should have solved this Adam.
