### ISSUE TITLE
Typescript bindings are not present in standalone pact-web npm package

### ISSUE THREAD

**Issue by KevinTHicks** [pact-foundation/pact-js#92]
* Package used: `pact-web: "2.7.0"`

The correct bindings are already being made by the core package but they do not seem to be copied when making the pact-web package. I have made a local work around by porting them manually into my project , but it seems like a minor oversight.

Thank you for your work on this!

**Comment by mefellows** [comment]
Thanks @KevinTHicks, we are in the process of converting the project to Typescript proper and refactoring the `pact-web` module. We'll make sure we don't forget this module!

**Comment by mefellows** [comment]
Note these are now available in the `6.x.x` release branch (also note that the repository has moved under the pact-foundation).
