### ISSUE TITLE
Feature request: support option to not fail if no pacts found

### ISSUE THREAD

**Issue by adamwitko** [pact-foundation/pact-js#941]
### Software versions

- **OS**: Mac OSX 12.3
- **Consumer Pact library**: @pact-foundation/pact@10.1.0
- **Provider Pact library**: @pact-foundation/pact@10.1.0
- **Node Version**: 18.7.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

When a provider does not find any pacts to verify the verification resolves with the relevant output describing the result. This means any test libraries do not fail as the promise is resolved.

### Actual behaviour

When a provider does not find any pacts to verify for the consumer version selectors, an error inside the Rust pact_verifier is failing the verification run.

### Steps to reproduce

- Set your options to a standard looking configuration such as the following where there are no consumer pacts published that match the consumerVersionSelectors defined:

```javascript
 const verifierOptions = {
      publishVerificationResult: false,
      provider: 'my-service',
      providerBaseUrl: 'http://localhost:8000',
      providerVersion: '09fe6815',
      providerBranch: 'my-branch',
      logLevel: 'debug',
      pactBrokerUrl: 'https://my-broker/',
      enablePending: true,
      consumerVersionSelectors: [
        { mainBranch: true },
        { deployedOrReleased: true },
        { matchingBranch: true }
      ],
    }
    
 await new Verifier(verifierOptions).verifyProvider()
```

### Relevant log files

[debug.log](https://github.com/pact-foundation/pact-js/files/9315827/debug.log)

**Comment by TimothyJones** [comment]
What does can-i-deploy do if you ask about a provider with no consumers? I don’t think it should fail- it’s safe to deploy a provider with no consumers.

If it doesn’t fail, then I think pact verify with no consumers shouldn’t fail either (although I think it should warn). If pact verify fails when there are no consumers, then we can never end up deploying a provider with no consumers.

For these reasons, I prefer not failing when there are no pacts found by default. If it doesn’t fail, you don’t have to special case an initial deploy. If it does fail, you do.

**Comment by adamwitko** [comment]
@TimothyJones this was my understanding of how the previous versions of @pact-foundation/pact-js behaved. I too had understood that it is absolutely fine for provider to exist with no consumer. That is an expected scenario, especially when teams are starting off with Pact or creating new provider services.

**Comment by mefellows** [comment]
Yep, it's just that once you have consumers it's harder to detect this use case without additional checks. That could be worth exploring. e.g. If there are consumers of a provider, but no pacts are found, this is probably a configuration issue. If there are no consumers, then you'd always expect an empty list of pacts to verify.

cc: @bethesque

**Comment by adamwitko** [comment]
Hey is there any movement on this issue that anyone knows about? 

This is stopping me rolling out v10 of this package as we cannot establish providers before there are pact for it to verify. It's a bit of a big blocker for our pipelines as we can't create consumer pacts before the provider exists and have them be deployable, and we can't create providers before the consumer pacts exists to verify with v10.

Can I help out at all?

**Comment by mefellows** [comment]
Hi Adam. The Pact core now supports the feature via the `set_no_pacts_is_error` C interface (https://github.com/pact-foundation/pact-reference/blob/c128d22b838400d035ba900bedc4432bf98f1d5a/rust/pact_ffi/src/verifier/handle.rs#L220-L222).

We first need to expose this C interface to Node:

1. A new method will need to be added to pact-js-core C inerface (https://github.com/pact-foundation/pact-js-core/blob/master/native/provider.cc and the header file)
1. The new c interface will need to be registered and exposed to Node via https://github.com/pact-foundation/pact-js-core/blob/master/native/addon.cc

Then we can add the types to the core:

1. A new optional parameter `failIfNoPactsFound` will need to be added to the verifier [types](https://github.com/pact-foundation/pact-js-core/blob/master/src/verifier/types.ts#L21)
1. A validation routine (copy any other boolean field validator) for the method: https://github.com/pact-foundation/pact-js-core/blob/master/src/verifier/validateOptions.ts#L189

Once released, this will make the type available to Pact JS :)

**Comment by mefellows** [comment]
Closed, the PR above completes this feature.
