### ISSUE TITLE
`eachKeyLike` matcher isn't eachKeyLike, it is eachValueLike (also rust core version needs a bump)

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js#952]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: All
- **Consumer Pact library**: 10.1.4
- **Provider Pact library**:N/A
- **Node Version**: N/A
- 
### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

As per https://github.com/pact-foundation/pact-reference/issues/216 , `eachLike` doesn't match correctly.  This object:

```
{
  "john-doe1": {
    "brown-fox": {
      "jumps": "over",
      "the": "lazy dog"
    }
  },
  "john-doe2": {
    "brown-fox2": {
      "jumps": "over",
      "the": "lazy dog"
    }
  }
}
```
should be matched by

```
Matchers.eachKeyLike(
   "some string", 
   Matchers.eachKeyLike(
      "some-string", 
      Matchers.eachKeyLike(
         "some-string",
         Matchers.string())))
```

### Actual behaviour

It is not matched - the match only applies at the first level.

### Steps to reproduce

As above

### Extra information

To get the fix, we'll need to bump the rust core to at least 0.3.12.

Also, as @uglyog pointed out:

> BTW, the eachKeyLike function is incorrectly named. It should be something like eachValueLike.

Probably the right fix for this is:

* Rename the existing `eachKeyLike` to `eachValueLike`
* Add the `eachKeyLike` matcher (this is a breaking change, since the signature for `eachKeyLike` would describe something different to what it currently does / and currently is documented to do)
* Update the documentation to match
* For bonus points, I think there's also an `eachKeyValueLike` matcher which could be added

**Comment by mefellows** [comment]
Thanks for raising/moving this here Tim.

The `pact-core` package release just went out with the new fix. This will come in by default based on our dependency rules, but next change we can enforce that too.

As for the functions, I'm confused about how we support the (intended) `eachKeyLike` function (matching keys, not values), so will need some support on how we implement that from @uglyog. Will use this ticket to track that activity.

**Comment by mefellows** [comment]
Update on this issue. `eachKeyLike` should use set `pact:matcher:type: "eachKey"` as documented here: https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/IntegrationJson.md

**Comment by eburi** [comment]
👋 Hi,
There has been no changes related to this issue, #662 and #1077 - is there anything I can do so that this bug will be addressed?
