### ISSUE TITLE
Static XML returned by `willRespondWith` for Header 'Content-Type': 'application/xml'

### ISSUE THREAD

**Issue by Daniel-Kempf** [pact-foundation/pact-js#959]
### Software versions
OS: Ubuntu 22.04 LTS
Consumer Pact library: 10.1.4
Node Version: 16.6.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

The passed XML string is present in response body of pact file when header `'Content-Type': 'application/xml'` is set in `willRespondWith` function.

### Actual behaviour

When using header `'Content-Type': 'application/xml'` a static XML string is returned as response body.

### Steps to reproduce

Define a consumer pact that has something like this in `willRespondWith()`:
```
.willRespondWith({
    status: 200,
    headers: { 'Content-Type': 'application/xml' },
    body: MatchersV3.like(`<?xml version="1.0" encoding="utf-8"?><TEST><ABC></ABC></TEST>`),
})
``` 
Will produce a pact file like this:
```
"response": {
  "body": "<?xml version='1.0'?>",
  "headers": {
    "Content-Type": "application/xml"
    },
  "status": 200
}
```

**Comment by mefellows** [comment]
The `MatchersV3.like` matcher is used to specify it matching a string value - it doesn't look at what's contained within the string itself. 

You should use the `XmlBuilder` class for this. See https://github.com/pact-foundation/pact-js/blob/master/docs/xml.md and this example https://github.com/pact-foundation/pact-js/blob/master/examples/v3/todo-consumer/test/consumer.spec.js#L75.

I'll close this ticket off for now as invalid.
