### ISSUE TITLE
MessageConsumerPact TypeError on import

### ISSUE THREAD

**Issue by douglaseggleton** [pact-foundation/pact-js#966]
### Software versions

- **OS**: Mac OSX 13.0
- **Consumer Pact library**: Pact JS 10.1.4
- **Provider Pact library**: n/a
- **Node Version**: v16.16.0
### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

`MessageConsumerPact` should be imported correctly.

### Actual behaviour

An error (See relevant log fils) is raised `TypeError: (0 , pact_core_1.makeConsumerAsyncMessagePact) is not a function`

### Steps to reproduce

1. Create a new node project and add `@pact-foundation/pact` as a dev dependency.
2. Import the `MessageConsumerPact` package

```js
const { MessageConsumerPact } = require("@pact-foundation/pact");

new MessageConsumerPact({});
```
3. Run the script in a node environment.

See example https://codesandbox.io/s/black-fire-qhvcn5?file=/src/index.js

### Relevant log files

```
TypeError: (0 , pact_core_1.makeConsumerAsyncMessagePact) is not a function
    at new MessageConsumerPact (/sandbox/node_modules/@pact-foundation/pact/src/messageConsumerPact.js:58:66)
    at Object.<anonymous> (/sandbox/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
    ```

**Comment by douglaseggleton** [comment]
This looks to only be an issue on `latest` / `v10` and not `v9`

**Comment by mefellows** [comment]
Thanks @douglaseggleton, this is because I removed a method instead of aliasing it as I meant to in `pact-core` (a key dependency). I believe pinning `pact-core` to [13.10.0](https://www.npmjs.com/package/@pact-foundation/pact-core/v/13.10.0) should fix it for the time being. I will fix that asap .

**Comment by mefellows** [comment]
Should be fixed now @douglaseggleton, code sandbox seems to be down for me, but running your repro locally works (it fails for another reason - missing args - but providig the correct arguments I can get a passing test now).

Thanks for raising, and my apologies for the issue!


<img width="808" alt="Screen Shot 2022-11-02 at 1 07 07 pm" src="https://user-images.githubusercontent.com/53900/199378184-eb7f7390-1abe-4679-91fb-4bdb3d8425a9.png">
