### ISSUE TITLE
For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\contract- testing-nodejs-pact\consumer.spec.js)

### ISSUE THREAD

**Issue by SridharMurari** [pact-foundation/pact-js#967]
_I amnot sure if this issues already addressed if yes please send me the link I am getting following error 
For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\contract-
testing-nodejs-pact\consumer.spec.js)

Regards
Sridhar

**Comment by mefellows** [comment]
Hi @SridharMurari, it looks like you haven't properly handled a promise somewhere.

But the issue as current stated is poorly worded and lacks any information we can use to help. We have an issue template for a reason. Closing this one, please re-create a new one with the issue template populated.
