### ISSUE TITLE
Getting `Cannot find module 'dsl/message'` error in 10.2.0

### ISSUE THREAD

**Issue by qmg-akara** [pact-foundation/pact-js#974]
Hi guys, thanks for the great work!

We just upgraded to version 10.2.0 but our `yarn lint` is failing due to 2 import paths:
```
node_modules/.store/@pact-foundation-pact-npm-10.2.0-8ecf80a526/node_modules/@pact-foundation/pact/src/dsl/verifier/proxy/types.d.ts:4:34 - error TS2307: Cannot find module 'dsl/message' or its corresponding type declarations.

4 import { MessageProviders } from 'dsl/message';
                                   ~~~~~~~~~~~~~

node_modules/.store/@pact-foundation-pact-npm-10.2.0-8ecf80a526/node_modules/@pact-foundation/pact/src/dsl/verifier/types.d.ts:2:40 - error TS2307: Cannot find module 'dsl/options' or its corresponding type declarations.

2 import { MessageProviderOptions } from 'dsl/options';
                                         ~~~~~~~~~~~~~
```

Are aliased import paths typo or intentional?

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac OSX 10.11.5_
- **Consumer Pact library**: _Pact JS v10.2.0_
- **Provider Pact library**: _N/A_
- **Node Version**: `18`

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

No linting error

### Actual behaviour

Getting the above errors

### Steps to reproduce

It can be tested with a fresh install

### Relevant log files

See above

**Comment by mefellows** [comment]
Gah! I really need to find a way to prevent my editor from using relative imports, and investigate if this can be easily added to our CI to fail a build.

I'll get a patch out ASAP.

(also, thank you for the kind words)

**Comment by qmg-akara** [comment]
Thanks for the quick fix!

**Comment by mefellows** [comment]
You're welcome

**Comment by TimothyJones** [comment]
The problem is that if you're using aliases or a baseurl typescript doesn't convert the import paths on compilation, and as far as I know you can't make it convert them (unless you compile with something like babel or webpack as a post processing step)

> I really need to find a way to prevent my editor from using aliased import

I don't remember which editor you use, but in VS Code this is under TypeScript › Preferences: Import Module Specifier. 

Not using `baseUrl` at all is another solution, of course. It probably shouldn't be set in a library anyway.

**Comment by TimothyJones** [comment]
I guess this isn't picked up at test time because ts-jest just runs the typescript :/

**Comment by mefellows** [comment]
> I don't remember which editor you use, but in VS Code this is under TypeScript › Preferences: Import Module Specifier.

Ah yes, thanks - I've made that change now.

> Not using baseUrl at all is another solution, of course. It probably shouldn't be set in a library anyway.

Removing this makes it a compilation error, which I think is what we want (I added that change in yesterday, and found two more imports). Thanks for the tips everyone.

**Comment by TimothyJones** [comment]
I read the docs for that option after my comment last night, and it is there in typescript as a convenience for systems that use a different import structure or have a post processing step that moves files around. So we shouldn’t have had it set anyway. Probably my fault, sorry!
