### ISSUE TITLE
Upgrade Pact FFI Library to 0.3.15

### ISSUE THREAD

**Issue by rholshausen** [pact-foundation/pact-js#983]
This fixes:
* Verification results across multiple pacts accumulate, publishing invalid results (https://github.com/pact-foundation/pact-reference/issues/231)

**Comment by mefellows** [comment]
Thanks, was waiting for the artifacts to build.

Just pushed up the changes to the pact-js-core now - if build succeeds, I'll release ASAP.

**Comment by mefellows** [comment]
`pact-core` 13.12.2 released. Pact JS should pull that dependency in transitively, but i'll do an update shortly to ensure it's there as a minimum.
